// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_overview.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminOverviewCurrentCounts = `-- name: GetAdminOverviewCurrentCounts :one
SELECT
    (SELECT count(*)::bigint FROM party_rooms WHERE status IN ('lobby', 'playing')) AS active_rooms,
    (SELECT count(*)::bigint FROM game_sessions WHERE status IN ('active', 'suspended')) AS running_games,
    (SELECT count(*)::bigint FROM users AS account WHERE account.created_at >= $1::timestamptz AND account.created_at < $2::timestamptz) AS new_users,
    (SELECT count(*)::bigint FROM users AS account WHERE account.status = 'suspended') AS suspended_users,
    (SELECT count(*)::bigint
       FROM admin_user_command_receipts AS receipt
      WHERE receipt.command = 'unsuspend'
        AND receipt.outcome = 'executed'
        AND receipt.completed_at >= $1::timestamptz
        AND receipt.completed_at < $2::timestamptz) AS unsuspended_users,
    (SELECT count(*)::bigint
       FROM game_sessions AS session
      WHERE session.status = 'cancelled'
        AND session.ended_at >= $1::timestamptz
        AND session.ended_at < $2::timestamptz) AS abnormal_terminations,
    (SELECT count(*)::bigint
       FROM admin_repair_operations AS repair
      WHERE repair.state = 'executed'
        AND repair.executed_at >= $1::timestamptz
        AND repair.executed_at < $2::timestamptz) AS emergency_repairs
`

type GetAdminOverviewCurrentCountsParams struct {
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

type GetAdminOverviewCurrentCountsRow struct {
	ActiveRooms          int64 `json:"active_rooms"`
	RunningGames         int64 `json:"running_games"`
	NewUsers             int64 `json:"new_users"`
	SuspendedUsers       int64 `json:"suspended_users"`
	UnsuspendedUsers     int64 `json:"unsuspended_users"`
	AbnormalTerminations int64 `json:"abnormal_terminations"`
	EmergencyRepairs     int64 `json:"emergency_repairs"`
}

// GetAdminOverviewCurrentCounts
//
//	SELECT
//	    (SELECT count(*)::bigint FROM party_rooms WHERE status IN ('lobby', 'playing')) AS active_rooms,
//	    (SELECT count(*)::bigint FROM game_sessions WHERE status IN ('active', 'suspended')) AS running_games,
//	    (SELECT count(*)::bigint FROM users AS account WHERE account.created_at >= $1::timestamptz AND account.created_at < $2::timestamptz) AS new_users,
//	    (SELECT count(*)::bigint FROM users AS account WHERE account.status = 'suspended') AS suspended_users,
//	    (SELECT count(*)::bigint
//	       FROM admin_user_command_receipts AS receipt
//	      WHERE receipt.command = 'unsuspend'
//	        AND receipt.outcome = 'executed'
//	        AND receipt.completed_at >= $1::timestamptz
//	        AND receipt.completed_at < $2::timestamptz) AS unsuspended_users,
//	    (SELECT count(*)::bigint
//	       FROM game_sessions AS session
//	      WHERE session.status = 'cancelled'
//	        AND session.ended_at >= $1::timestamptz
//	        AND session.ended_at < $2::timestamptz) AS abnormal_terminations,
//	    (SELECT count(*)::bigint
//	       FROM admin_repair_operations AS repair
//	      WHERE repair.state = 'executed'
//	        AND repair.executed_at >= $1::timestamptz
//	        AND repair.executed_at < $2::timestamptz) AS emergency_repairs
func (q *Queries) GetAdminOverviewCurrentCounts(ctx context.Context, arg GetAdminOverviewCurrentCountsParams) (GetAdminOverviewCurrentCountsRow, error) {
	row := q.db.QueryRow(ctx, getAdminOverviewCurrentCounts, arg.WindowStart, arg.WindowEnd)
	var i GetAdminOverviewCurrentCountsRow
	err := row.Scan(
		&i.ActiveRooms,
		&i.RunningGames,
		&i.NewUsers,
		&i.SuspendedUsers,
		&i.UnsuspendedUsers,
		&i.AbnormalTerminations,
		&i.EmergencyRepairs,
	)
	return i, err
}

const listAdminOverviewAttentionItems = `-- name: ListAdminOverviewAttentionItems :many
WITH room_attention AS (
    SELECT 'room'::text AS attention_kind,
           room.room_id AS resource_id,
           room.room_id,
           room.status AS status_code,
           (array_remove(ARRAY[
               CASE WHEN room.active_session_id IS NULL THEN 'room.session_missing' END,
               CASE WHEN session.session_id IS NULL AND room.active_session_id IS NOT NULL THEN 'room.session_not_found' END,
               CASE WHEN session.session_id IS NOT NULL AND session.room_id <> room.room_id THEN 'room.session_room_mismatch' END,
               CASE WHEN session.session_id IS NOT NULL AND session.game_id <> room.active_game_id THEN 'room.game_mismatch' END,
               CASE WHEN session.session_id IS NOT NULL AND session.status NOT IN ('active', 'suspended') THEN 'room.session_inactive' END
           ]::text[], NULL))::text[] AS reason_codes,
           room.updated_at AS observed_at
    FROM party_rooms AS room
    LEFT JOIN game_sessions AS session ON session.session_id = room.active_session_id
    WHERE room.status = 'playing'
      AND (
          room.active_session_id IS NULL
          OR session.session_id IS NULL
          OR session.room_id <> room.room_id
          OR session.game_id <> room.active_game_id
          OR session.status NOT IN ('active', 'suspended')
      )
), game_attention AS (
    SELECT 'game'::text AS attention_kind,
           session.session_id AS resource_id,
           session.room_id,
           session.status AS status_code,
           (array_remove(ARRAY[
               CASE WHEN room.room_id IS NULL THEN 'game.room_not_found' END,
               CASE WHEN room.room_id IS NOT NULL AND room.status <> 'playing' THEN 'game.room_not_playing' END,
               CASE WHEN room.room_id IS NOT NULL AND room.active_session_id IS DISTINCT FROM session.session_id THEN 'game.session_link_mismatch' END,
               CASE WHEN room.room_id IS NOT NULL AND room.active_game_id IS DISTINCT FROM session.game_id THEN 'game.catalog_link_mismatch' END
           ]::text[], NULL))::text[] AS reason_codes,
           session.updated_at AS observed_at
    FROM game_sessions AS session
    LEFT JOIN party_rooms AS room ON room.room_id = session.room_id
    WHERE session.status IN ('active', 'suspended')
      AND (
          room.room_id IS NULL
          OR room.status <> 'playing'
          OR room.active_session_id IS DISTINCT FROM session.session_id
          OR room.active_game_id IS DISTINCT FROM session.game_id
      )
)
SELECT attention_kind, resource_id, room_id, status_code, reason_codes, observed_at
FROM (
    SELECT attention_kind, resource_id, room_id, status_code, reason_codes, observed_at FROM room_attention
    UNION ALL
    SELECT attention_kind, resource_id, room_id, status_code, reason_codes, observed_at FROM game_attention
) AS attention
ORDER BY observed_at DESC, attention_kind, resource_id
LIMIT $1
`

type ListAdminOverviewAttentionItemsParams struct {
	PageSize int32 `json:"page_size"`
}

type ListAdminOverviewAttentionItemsRow struct {
	AttentionKind string             `json:"attention_kind"`
	ResourceID    pgtype.UUID        `json:"resource_id"`
	RoomID        pgtype.UUID        `json:"room_id"`
	StatusCode    string             `json:"status_code"`
	ReasonCodes   []string           `json:"reason_codes"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
}

// ListAdminOverviewAttentionItems
//
//	WITH room_attention AS (
//	    SELECT 'room'::text AS attention_kind,
//	           room.room_id AS resource_id,
//	           room.room_id,
//	           room.status AS status_code,
//	           (array_remove(ARRAY[
//	               CASE WHEN room.active_session_id IS NULL THEN 'room.session_missing' END,
//	               CASE WHEN session.session_id IS NULL AND room.active_session_id IS NOT NULL THEN 'room.session_not_found' END,
//	               CASE WHEN session.session_id IS NOT NULL AND session.room_id <> room.room_id THEN 'room.session_room_mismatch' END,
//	               CASE WHEN session.session_id IS NOT NULL AND session.game_id <> room.active_game_id THEN 'room.game_mismatch' END,
//	               CASE WHEN session.session_id IS NOT NULL AND session.status NOT IN ('active', 'suspended') THEN 'room.session_inactive' END
//	           ]::text[], NULL))::text[] AS reason_codes,
//	           room.updated_at AS observed_at
//	    FROM party_rooms AS room
//	    LEFT JOIN game_sessions AS session ON session.session_id = room.active_session_id
//	    WHERE room.status = 'playing'
//	      AND (
//	          room.active_session_id IS NULL
//	          OR session.session_id IS NULL
//	          OR session.room_id <> room.room_id
//	          OR session.game_id <> room.active_game_id
//	          OR session.status NOT IN ('active', 'suspended')
//	      )
//	), game_attention AS (
//	    SELECT 'game'::text AS attention_kind,
//	           session.session_id AS resource_id,
//	           session.room_id,
//	           session.status AS status_code,
//	           (array_remove(ARRAY[
//	               CASE WHEN room.room_id IS NULL THEN 'game.room_not_found' END,
//	               CASE WHEN room.room_id IS NOT NULL AND room.status <> 'playing' THEN 'game.room_not_playing' END,
//	               CASE WHEN room.room_id IS NOT NULL AND room.active_session_id IS DISTINCT FROM session.session_id THEN 'game.session_link_mismatch' END,
//	               CASE WHEN room.room_id IS NOT NULL AND room.active_game_id IS DISTINCT FROM session.game_id THEN 'game.catalog_link_mismatch' END
//	           ]::text[], NULL))::text[] AS reason_codes,
//	           session.updated_at AS observed_at
//	    FROM game_sessions AS session
//	    LEFT JOIN party_rooms AS room ON room.room_id = session.room_id
//	    WHERE session.status IN ('active', 'suspended')
//	      AND (
//	          room.room_id IS NULL
//	          OR room.status <> 'playing'
//	          OR room.active_session_id IS DISTINCT FROM session.session_id
//	          OR room.active_game_id IS DISTINCT FROM session.game_id
//	      )
//	)
//	SELECT attention_kind, resource_id, room_id, status_code, reason_codes, observed_at
//	FROM (
//	    SELECT attention_kind, resource_id, room_id, status_code, reason_codes, observed_at FROM room_attention
//	    UNION ALL
//	    SELECT attention_kind, resource_id, room_id, status_code, reason_codes, observed_at FROM game_attention
//	) AS attention
//	ORDER BY observed_at DESC, attention_kind, resource_id
//	LIMIT $1
func (q *Queries) ListAdminOverviewAttentionItems(ctx context.Context, arg ListAdminOverviewAttentionItemsParams) ([]ListAdminOverviewAttentionItemsRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewAttentionItems, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminOverviewAttentionItemsRow{}
	for rows.Next() {
		var i ListAdminOverviewAttentionItemsRow
		if err := rows.Scan(
			&i.AttentionKind,
			&i.ResourceID,
			&i.RoomID,
			&i.StatusCode,
			&i.ReasonCodes,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewFailedBatchJobs = `-- name: ListAdminOverviewFailedBatchJobs :many
SELECT batch_job_id AS task_id,
       'user_batch'::text AS task_kind,
       state,
       COALESCE(error_message_key, 'admin.task.failed')::text AS stable_error_code,
       version,
       updated_at
FROM admin_batch_jobs
WHERE state = 'failed'
ORDER BY updated_at DESC, batch_job_id
LIMIT $1
`

type ListAdminOverviewFailedBatchJobsParams struct {
	PageSize int32 `json:"page_size"`
}

type ListAdminOverviewFailedBatchJobsRow struct {
	TaskID          pgtype.UUID        `json:"task_id"`
	TaskKind        string             `json:"task_kind"`
	State           string             `json:"state"`
	StableErrorCode string             `json:"stable_error_code"`
	Version         int64              `json:"version"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// ListAdminOverviewFailedBatchJobs
//
//	SELECT batch_job_id AS task_id,
//	       'user_batch'::text AS task_kind,
//	       state,
//	       COALESCE(error_message_key, 'admin.task.failed')::text AS stable_error_code,
//	       version,
//	       updated_at
//	FROM admin_batch_jobs
//	WHERE state = 'failed'
//	ORDER BY updated_at DESC, batch_job_id
//	LIMIT $1
func (q *Queries) ListAdminOverviewFailedBatchJobs(ctx context.Context, arg ListAdminOverviewFailedBatchJobsParams) ([]ListAdminOverviewFailedBatchJobsRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewFailedBatchJobs, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminOverviewFailedBatchJobsRow{}
	for rows.Next() {
		var i ListAdminOverviewFailedBatchJobsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskKind,
			&i.State,
			&i.StableErrorCode,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewFailedErasureJobs = `-- name: ListAdminOverviewFailedErasureJobs :many
SELECT erasure_job_id AS task_id,
       'user_erasure'::text AS task_kind,
       state,
       COALESCE(error_message_key, 'admin.task.failed')::text AS stable_error_code,
       attempt_count,
       version,
       updated_at
FROM admin_user_erasure_jobs
WHERE state = 'failed'
ORDER BY updated_at DESC, erasure_job_id
LIMIT $1
`

type ListAdminOverviewFailedErasureJobsParams struct {
	PageSize int32 `json:"page_size"`
}

type ListAdminOverviewFailedErasureJobsRow struct {
	TaskID          pgtype.UUID        `json:"task_id"`
	TaskKind        string             `json:"task_kind"`
	State           string             `json:"state"`
	StableErrorCode string             `json:"stable_error_code"`
	AttemptCount    int32              `json:"attempt_count"`
	Version         int64              `json:"version"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// ListAdminOverviewFailedErasureJobs
//
//	SELECT erasure_job_id AS task_id,
//	       'user_erasure'::text AS task_kind,
//	       state,
//	       COALESCE(error_message_key, 'admin.task.failed')::text AS stable_error_code,
//	       attempt_count,
//	       version,
//	       updated_at
//	FROM admin_user_erasure_jobs
//	WHERE state = 'failed'
//	ORDER BY updated_at DESC, erasure_job_id
//	LIMIT $1
func (q *Queries) ListAdminOverviewFailedErasureJobs(ctx context.Context, arg ListAdminOverviewFailedErasureJobsParams) ([]ListAdminOverviewFailedErasureJobsRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewFailedErasureJobs, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminOverviewFailedErasureJobsRow{}
	for rows.Next() {
		var i ListAdminOverviewFailedErasureJobsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskKind,
			&i.State,
			&i.StableErrorCode,
			&i.AttemptCount,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewMetricBuckets = `-- name: ListAdminOverviewMetricBuckets :many
SELECT metric_name, bucket_width, bucket_start, value, sampled_at, source_watermark
FROM admin_metric_buckets
WHERE bucket_width = $1
  AND bucket_start >= $2
  AND bucket_start < $3
ORDER BY metric_name, bucket_start
LIMIT $4
`

type ListAdminOverviewMetricBucketsParams struct {
	BucketWidth string             `json:"bucket_width"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	PageSize    int32              `json:"page_size"`
}

// ListAdminOverviewMetricBuckets
//
//	SELECT metric_name, bucket_width, bucket_start, value, sampled_at, source_watermark
//	FROM admin_metric_buckets
//	WHERE bucket_width = $1
//	  AND bucket_start >= $2
//	  AND bucket_start < $3
//	ORDER BY metric_name, bucket_start
//	LIMIT $4
func (q *Queries) ListAdminOverviewMetricBuckets(ctx context.Context, arg ListAdminOverviewMetricBucketsParams) ([]AdminMetricBucket, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewMetricBuckets,
		arg.BucketWidth,
		arg.WindowStart,
		arg.WindowEnd,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminMetricBucket{}
	for rows.Next() {
		var i AdminMetricBucket
		if err := rows.Scan(
			&i.MetricName,
			&i.BucketWidth,
			&i.BucketStart,
			&i.Value,
			&i.SampledAt,
			&i.SourceWatermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
