// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptAdminTotpStepCAS = `-- name: AcceptAdminTotpStepCAS :one
UPDATE admin_accounts
SET last_accepted_totp_step = $1,
    updated_at = $2
WHERE singleton_id = 1
  AND admin_id = $3
  AND status = 'active'
  AND admin_version = $4
  AND (last_accepted_totp_step IS NULL OR last_accepted_totp_step < $1)
RETURNING admin_id, admin_version, last_accepted_totp_step, updated_at
`

type AcceptAdminTotpStepCASParams struct {
	TotpStep             pgtype.Int8        `json:"totp_step"`
	AcceptedAt           pgtype.Timestamptz `json:"accepted_at"`
	AdminID              pgtype.UUID        `json:"admin_id"`
	ExpectedAdminVersion int64              `json:"expected_admin_version"`
}

type AcceptAdminTotpStepCASRow struct {
	AdminID              pgtype.UUID        `json:"admin_id"`
	AdminVersion         int64              `json:"admin_version"`
	LastAcceptedTotpStep pgtype.Int8        `json:"last_accepted_totp_step"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// AcceptAdminTotpStepCAS
//
//	UPDATE admin_accounts
//	SET last_accepted_totp_step = $1,
//	    updated_at = $2
//	WHERE singleton_id = 1
//	  AND admin_id = $3
//	  AND status = 'active'
//	  AND admin_version = $4
//	  AND (last_accepted_totp_step IS NULL OR last_accepted_totp_step < $1)
//	RETURNING admin_id, admin_version, last_accepted_totp_step, updated_at
func (q *Queries) AcceptAdminTotpStepCAS(ctx context.Context, arg AcceptAdminTotpStepCASParams) (AcceptAdminTotpStepCASRow, error) {
	row := q.db.QueryRow(ctx, acceptAdminTotpStepCAS,
		arg.TotpStep,
		arg.AcceptedAt,
		arg.AdminID,
		arg.ExpectedAdminVersion,
	)
	var i AcceptAdminTotpStepCASRow
	err := row.Scan(
		&i.AdminID,
		&i.AdminVersion,
		&i.LastAcceptedTotpStep,
		&i.UpdatedAt,
	)
	return i, err
}

const activatePendingAdminTotpEnrollmentCAS = `-- name: ActivatePendingAdminTotpEnrollmentCAS :one
UPDATE admin_totp_enrollments
SET status = 'active',
    expires_at = NULL,
    activated_at = $1
WHERE admin_id = $2
  AND enrollment_id = $3
  AND status = 'pending'
  AND admin_version = $4
  AND expires_at > $1
RETURNING enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
          operation_id, created_at, expires_at, activated_at, disabled_at
`

type ActivatePendingAdminTotpEnrollmentCASParams struct {
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	AdminID              pgtype.UUID        `json:"admin_id"`
	EnrollmentID         pgtype.UUID        `json:"enrollment_id"`
	ExpectedAdminVersion int64              `json:"expected_admin_version"`
}

// ActivatePendingAdminTotpEnrollmentCAS
//
//	UPDATE admin_totp_enrollments
//	SET status = 'active',
//	    expires_at = NULL,
//	    activated_at = $1
//	WHERE admin_id = $2
//	  AND enrollment_id = $3
//	  AND status = 'pending'
//	  AND admin_version = $4
//	  AND expires_at > $1
//	RETURNING enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
//	          operation_id, created_at, expires_at, activated_at, disabled_at
func (q *Queries) ActivatePendingAdminTotpEnrollmentCAS(ctx context.Context, arg ActivatePendingAdminTotpEnrollmentCASParams) (AdminTotpEnrollment, error) {
	row := q.db.QueryRow(ctx, activatePendingAdminTotpEnrollmentCAS,
		arg.ActivatedAt,
		arg.AdminID,
		arg.EnrollmentID,
		arg.ExpectedAdminVersion,
	)
	var i AdminTotpEnrollment
	err := row.Scan(
		&i.EnrollmentID,
		&i.AdminID,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
		&i.Status,
		&i.AdminVersion,
		&i.OperationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ActivatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const bootstrapAdminPasswordCAS = `-- name: BootstrapAdminPasswordCAS :one
UPDATE admin_accounts
SET status = 'setup_required',
    password_hash = $1,
    password_algorithm = $2,
    password_parameters = $3,
    password_version = password_version + 1,
    admin_version = admin_version + 1,
    updated_at = $4
WHERE singleton_id = 1
  AND status = 'bootstrap_pending'
  AND password_hash IS NULL
  AND admin_version = $5
RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
`

type BootstrapAdminPasswordCASParams struct {
	PasswordHash         pgtype.Text        `json:"password_hash"`
	PasswordAlgorithm    pgtype.Text        `json:"password_algorithm"`
	PasswordParameters   pgtype.Text        `json:"password_parameters"`
	ChangedAt            pgtype.Timestamptz `json:"changed_at"`
	ExpectedAdminVersion int64              `json:"expected_admin_version"`
}

type BootstrapAdminPasswordCASRow struct {
	SingletonID     int16              `json:"singleton_id"`
	AdminID         pgtype.UUID        `json:"admin_id"`
	Status          string             `json:"status"`
	PasswordVersion int64              `json:"password_version"`
	AdminVersion    int64              `json:"admin_version"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// BootstrapAdminPasswordCAS
//
//	UPDATE admin_accounts
//	SET status = 'setup_required',
//	    password_hash = $1,
//	    password_algorithm = $2,
//	    password_parameters = $3,
//	    password_version = password_version + 1,
//	    admin_version = admin_version + 1,
//	    updated_at = $4
//	WHERE singleton_id = 1
//	  AND status = 'bootstrap_pending'
//	  AND password_hash IS NULL
//	  AND admin_version = $5
//	RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
func (q *Queries) BootstrapAdminPasswordCAS(ctx context.Context, arg BootstrapAdminPasswordCASParams) (BootstrapAdminPasswordCASRow, error) {
	row := q.db.QueryRow(ctx, bootstrapAdminPasswordCAS,
		arg.PasswordHash,
		arg.PasswordAlgorithm,
		arg.PasswordParameters,
		arg.ChangedAt,
		arg.ExpectedAdminVersion,
	)
	var i BootstrapAdminPasswordCASRow
	err := row.Scan(
		&i.SingletonID,
		&i.AdminID,
		&i.Status,
		&i.PasswordVersion,
		&i.AdminVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeAdminAssistedRecoveryGrantCAS = `-- name: ConsumeAdminAssistedRecoveryGrantCAS :one
UPDATE admin_assisted_recovery_grants
SET status = 'consumed',
    consumed_at = $1,
    result_id = $2
WHERE assisted_grant_id = $3
  AND status = 'active'
  AND expires_at > $1
  AND attempt_count < max_attempts
RETURNING assisted_grant_id, user_id, status, consumed_at, result_id
`

type ConsumeAdminAssistedRecoveryGrantCASParams struct {
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
	ResultID        pgtype.UUID        `json:"result_id"`
	AssistedGrantID pgtype.UUID        `json:"assisted_grant_id"`
}

type ConsumeAdminAssistedRecoveryGrantCASRow struct {
	AssistedGrantID pgtype.UUID        `json:"assisted_grant_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Status          string             `json:"status"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
	ResultID        pgtype.UUID        `json:"result_id"`
}

// ConsumeAdminAssistedRecoveryGrantCAS
//
//	UPDATE admin_assisted_recovery_grants
//	SET status = 'consumed',
//	    consumed_at = $1,
//	    result_id = $2
//	WHERE assisted_grant_id = $3
//	  AND status = 'active'
//	  AND expires_at > $1
//	  AND attempt_count < max_attempts
//	RETURNING assisted_grant_id, user_id, status, consumed_at, result_id
func (q *Queries) ConsumeAdminAssistedRecoveryGrantCAS(ctx context.Context, arg ConsumeAdminAssistedRecoveryGrantCASParams) (ConsumeAdminAssistedRecoveryGrantCASRow, error) {
	row := q.db.QueryRow(ctx, consumeAdminAssistedRecoveryGrantCAS, arg.ConsumedAt, arg.ResultID, arg.AssistedGrantID)
	var i ConsumeAdminAssistedRecoveryGrantCASRow
	err := row.Scan(
		&i.AssistedGrantID,
		&i.UserID,
		&i.Status,
		&i.ConsumedAt,
		&i.ResultID,
	)
	return i, err
}

const consumeAdminChallengeCAS = `-- name: ConsumeAdminChallengeCAS :one
UPDATE admin_challenges
SET status = 'consumed',
    consumed_at = $1,
    replay_until = $2,
    operation_id = $3,
    request_digest = $4,
    result_id = $5
WHERE challenge_id = $6
  AND status = 'active'
  AND expires_at > $1
  AND attempt_count < max_attempts
  AND admin_version = $7
  AND password_version = $8
RETURNING challenge_id, status, consumed_at, replay_until, operation_id, request_digest, result_id
`

type ConsumeAdminChallengeCASParams struct {
	ConsumedAt              pgtype.Timestamptz `json:"consumed_at"`
	ReplayUntil             pgtype.Timestamptz `json:"replay_until"`
	OperationID             pgtype.Text        `json:"operation_id"`
	RequestDigest           []byte             `json:"request_digest"`
	ResultID                pgtype.UUID        `json:"result_id"`
	ChallengeID             pgtype.UUID        `json:"challenge_id"`
	ExpectedAdminVersion    int64              `json:"expected_admin_version"`
	ExpectedPasswordVersion int64              `json:"expected_password_version"`
}

type ConsumeAdminChallengeCASRow struct {
	ChallengeID   pgtype.UUID        `json:"challenge_id"`
	Status        string             `json:"status"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	ReplayUntil   pgtype.Timestamptz `json:"replay_until"`
	OperationID   pgtype.Text        `json:"operation_id"`
	RequestDigest []byte             `json:"request_digest"`
	ResultID      pgtype.UUID        `json:"result_id"`
}

// ConsumeAdminChallengeCAS
//
//	UPDATE admin_challenges
//	SET status = 'consumed',
//	    consumed_at = $1,
//	    replay_until = $2,
//	    operation_id = $3,
//	    request_digest = $4,
//	    result_id = $5
//	WHERE challenge_id = $6
//	  AND status = 'active'
//	  AND expires_at > $1
//	  AND attempt_count < max_attempts
//	  AND admin_version = $7
//	  AND password_version = $8
//	RETURNING challenge_id, status, consumed_at, replay_until, operation_id, request_digest, result_id
func (q *Queries) ConsumeAdminChallengeCAS(ctx context.Context, arg ConsumeAdminChallengeCASParams) (ConsumeAdminChallengeCASRow, error) {
	row := q.db.QueryRow(ctx, consumeAdminChallengeCAS,
		arg.ConsumedAt,
		arg.ReplayUntil,
		arg.OperationID,
		arg.RequestDigest,
		arg.ResultID,
		arg.ChallengeID,
		arg.ExpectedAdminVersion,
		arg.ExpectedPasswordVersion,
	)
	var i ConsumeAdminChallengeCASRow
	err := row.Scan(
		&i.ChallengeID,
		&i.Status,
		&i.ConsumedAt,
		&i.ReplayUntil,
		&i.OperationID,
		&i.RequestDigest,
		&i.ResultID,
	)
	return i, err
}

const consumeAdminRecoveryCodeCAS = `-- name: ConsumeAdminRecoveryCodeCAS :one
UPDATE admin_recovery_codes
SET status = 'consumed',
    consumed_at = $1
WHERE recovery_code_id = $2
  AND admin_id = $3
  AND set_version = $4
  AND status = 'active'
RETURNING recovery_code_id, admin_id, set_version, status, consumed_at
`

type ConsumeAdminRecoveryCodeCASParams struct {
	ConsumedAt         pgtype.Timestamptz `json:"consumed_at"`
	RecoveryCodeID     pgtype.UUID        `json:"recovery_code_id"`
	AdminID            pgtype.UUID        `json:"admin_id"`
	ExpectedSetVersion int64              `json:"expected_set_version"`
}

type ConsumeAdminRecoveryCodeCASRow struct {
	RecoveryCodeID pgtype.UUID        `json:"recovery_code_id"`
	AdminID        pgtype.UUID        `json:"admin_id"`
	SetVersion     int64              `json:"set_version"`
	Status         string             `json:"status"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
}

// ConsumeAdminRecoveryCodeCAS
//
//	UPDATE admin_recovery_codes
//	SET status = 'consumed',
//	    consumed_at = $1
//	WHERE recovery_code_id = $2
//	  AND admin_id = $3
//	  AND set_version = $4
//	  AND status = 'active'
//	RETURNING recovery_code_id, admin_id, set_version, status, consumed_at
func (q *Queries) ConsumeAdminRecoveryCodeCAS(ctx context.Context, arg ConsumeAdminRecoveryCodeCASParams) (ConsumeAdminRecoveryCodeCASRow, error) {
	row := q.db.QueryRow(ctx, consumeAdminRecoveryCodeCAS,
		arg.ConsumedAt,
		arg.RecoveryCodeID,
		arg.AdminID,
		arg.ExpectedSetVersion,
	)
	var i ConsumeAdminRecoveryCodeCASRow
	err := row.Scan(
		&i.RecoveryCodeID,
		&i.AdminID,
		&i.SetVersion,
		&i.Status,
		&i.ConsumedAt,
	)
	return i, err
}

const createAdminAssistedRecoveryGrant = `-- name: CreateAdminAssistedRecoveryGrant :one
INSERT INTO admin_assisted_recovery_grants (
    assisted_grant_id,
    user_id,
    selector,
    secret_hash,
    purpose,
    status,
    attempt_count,
    max_attempts,
    created_by_admin_id,
    created_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'active',
    0,
    $6,
    $7,
    $8,
    $9
)
RETURNING assisted_grant_id, user_id, selector, secret_hash, purpose, status,
          attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
          consumed_at, revoked_at, result_id
`

type CreateAdminAssistedRecoveryGrantParams struct {
	AssistedGrantID  pgtype.UUID        `json:"assisted_grant_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Selector         string             `json:"selector"`
	SecretHash       string             `json:"secret_hash"`
	Purpose          string             `json:"purpose"`
	MaxAttempts      int32              `json:"max_attempts"`
	CreatedByAdminID pgtype.UUID        `json:"created_by_admin_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

// CreateAdminAssistedRecoveryGrant
//
//	INSERT INTO admin_assisted_recovery_grants (
//	    assisted_grant_id,
//	    user_id,
//	    selector,
//	    secret_hash,
//	    purpose,
//	    status,
//	    attempt_count,
//	    max_attempts,
//	    created_by_admin_id,
//	    created_at,
//	    expires_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    'active',
//	    0,
//	    $6,
//	    $7,
//	    $8,
//	    $9
//	)
//	RETURNING assisted_grant_id, user_id, selector, secret_hash, purpose, status,
//	          attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
//	          consumed_at, revoked_at, result_id
func (q *Queries) CreateAdminAssistedRecoveryGrant(ctx context.Context, arg CreateAdminAssistedRecoveryGrantParams) (AdminAssistedRecoveryGrant, error) {
	row := q.db.QueryRow(ctx, createAdminAssistedRecoveryGrant,
		arg.AssistedGrantID,
		arg.UserID,
		arg.Selector,
		arg.SecretHash,
		arg.Purpose,
		arg.MaxAttempts,
		arg.CreatedByAdminID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i AdminAssistedRecoveryGrant
	err := row.Scan(
		&i.AssistedGrantID,
		&i.UserID,
		&i.Selector,
		&i.SecretHash,
		&i.Purpose,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.CreatedByAdminID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.ResultID,
	)
	return i, err
}

const createAdminChallenge = `-- name: CreateAdminChallenge :one
INSERT INTO admin_challenges (
    challenge_id,
    admin_id,
    selector,
    secret_hash,
    secret_key_version,
    purpose,
    audience,
    admin_version,
    password_version,
    origin_hash,
    request_flow_id,
    attempt_count,
    max_attempts,
    status,
    created_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    0,
    $12,
    'active',
    $13,
    $14
)
RETURNING challenge_id, admin_id, selector, secret_hash, secret_key_version, purpose,
          audience, admin_version, password_version, origin_hash, request_flow_id,
          attempt_count, max_attempts, status, created_at, expires_at, consumed_at,
          revoked_at, replay_until, operation_id, request_digest, result_id
`

type CreateAdminChallengeParams struct {
	ChallengeID      pgtype.UUID        `json:"challenge_id"`
	AdminID          pgtype.UUID        `json:"admin_id"`
	Selector         string             `json:"selector"`
	SecretHash       []byte             `json:"secret_hash"`
	SecretKeyVersion int32              `json:"secret_key_version"`
	Purpose          string             `json:"purpose"`
	Audience         string             `json:"audience"`
	AdminVersion     int64              `json:"admin_version"`
	PasswordVersion  int64              `json:"password_version"`
	OriginHash       []byte             `json:"origin_hash"`
	RequestFlowID    string             `json:"request_flow_id"`
	MaxAttempts      int32              `json:"max_attempts"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

// CreateAdminChallenge
//
//	INSERT INTO admin_challenges (
//	    challenge_id,
//	    admin_id,
//	    selector,
//	    secret_hash,
//	    secret_key_version,
//	    purpose,
//	    audience,
//	    admin_version,
//	    password_version,
//	    origin_hash,
//	    request_flow_id,
//	    attempt_count,
//	    max_attempts,
//	    status,
//	    created_at,
//	    expires_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    0,
//	    $12,
//	    'active',
//	    $13,
//	    $14
//	)
//	RETURNING challenge_id, admin_id, selector, secret_hash, secret_key_version, purpose,
//	          audience, admin_version, password_version, origin_hash, request_flow_id,
//	          attempt_count, max_attempts, status, created_at, expires_at, consumed_at,
//	          revoked_at, replay_until, operation_id, request_digest, result_id
func (q *Queries) CreateAdminChallenge(ctx context.Context, arg CreateAdminChallengeParams) (AdminChallenge, error) {
	row := q.db.QueryRow(ctx, createAdminChallenge,
		arg.ChallengeID,
		arg.AdminID,
		arg.Selector,
		arg.SecretHash,
		arg.SecretKeyVersion,
		arg.Purpose,
		arg.Audience,
		arg.AdminVersion,
		arg.PasswordVersion,
		arg.OriginHash,
		arg.RequestFlowID,
		arg.MaxAttempts,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i AdminChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.AdminID,
		&i.Selector,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.Purpose,
		&i.Audience,
		&i.AdminVersion,
		&i.PasswordVersion,
		&i.OriginHash,
		&i.RequestFlowID,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.ReplayUntil,
		&i.OperationID,
		&i.RequestDigest,
		&i.ResultID,
	)
	return i, err
}

const createAdminRecoveryCode = `-- name: CreateAdminRecoveryCode :one
INSERT INTO admin_recovery_codes (
    recovery_code_id,
    admin_id,
    selector,
    secret_hash,
    set_version,
    status,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'active',
    $6
)
RETURNING recovery_code_id, admin_id, selector, secret_hash, set_version, status,
          created_at, consumed_at, revoked_at
`

type CreateAdminRecoveryCodeParams struct {
	RecoveryCodeID pgtype.UUID        `json:"recovery_code_id"`
	AdminID        pgtype.UUID        `json:"admin_id"`
	Selector       string             `json:"selector"`
	SecretHash     string             `json:"secret_hash"`
	SetVersion     int64              `json:"set_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// CreateAdminRecoveryCode
//
//	INSERT INTO admin_recovery_codes (
//	    recovery_code_id,
//	    admin_id,
//	    selector,
//	    secret_hash,
//	    set_version,
//	    status,
//	    created_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    'active',
//	    $6
//	)
//	RETURNING recovery_code_id, admin_id, selector, secret_hash, set_version, status,
//	          created_at, consumed_at, revoked_at
func (q *Queries) CreateAdminRecoveryCode(ctx context.Context, arg CreateAdminRecoveryCodeParams) (AdminRecoveryCode, error) {
	row := q.db.QueryRow(ctx, createAdminRecoveryCode,
		arg.RecoveryCodeID,
		arg.AdminID,
		arg.Selector,
		arg.SecretHash,
		arg.SetVersion,
		arg.CreatedAt,
	)
	var i AdminRecoveryCode
	err := row.Scan(
		&i.RecoveryCodeID,
		&i.AdminID,
		&i.Selector,
		&i.SecretHash,
		&i.SetVersion,
		&i.Status,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin_sessions (
    session_id,
    admin_id,
    selector,
    secret_hash,
    secret_key_version,
    csrf_hash,
    kind,
    admin_version,
    password_version,
    attempt_count,
    max_attempts,
    created_at,
    last_seen_at,
    idle_expires_at,
    absolute_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    0,
    $10,
    $11,
    $11,
    $12,
    $13
)
RETURNING session_id, admin_id, selector, secret_hash, secret_key_version, csrf_hash,
          kind, admin_version, password_version, attempt_count, max_attempts, created_at,
          last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
`

type CreateAdminSessionParams struct {
	SessionID         pgtype.UUID        `json:"session_id"`
	AdminID           pgtype.UUID        `json:"admin_id"`
	Selector          string             `json:"selector"`
	SecretHash        []byte             `json:"secret_hash"`
	SecretKeyVersion  int32              `json:"secret_key_version"`
	CsrfHash          []byte             `json:"csrf_hash"`
	Kind              string             `json:"kind"`
	AdminVersion      int64              `json:"admin_version"`
	PasswordVersion   int64              `json:"password_version"`
	MaxAttempts       int32              `json:"max_attempts"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

// CreateAdminSession
//
//	INSERT INTO admin_sessions (
//	    session_id,
//	    admin_id,
//	    selector,
//	    secret_hash,
//	    secret_key_version,
//	    csrf_hash,
//	    kind,
//	    admin_version,
//	    password_version,
//	    attempt_count,
//	    max_attempts,
//	    created_at,
//	    last_seen_at,
//	    idle_expires_at,
//	    absolute_expires_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    0,
//	    $10,
//	    $11,
//	    $11,
//	    $12,
//	    $13
//	)
//	RETURNING session_id, admin_id, selector, secret_hash, secret_key_version, csrf_hash,
//	          kind, admin_version, password_version, attempt_count, max_attempts, created_at,
//	          last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.SessionID,
		arg.AdminID,
		arg.Selector,
		arg.SecretHash,
		arg.SecretKeyVersion,
		arg.CsrfHash,
		arg.Kind,
		arg.AdminVersion,
		arg.PasswordVersion,
		arg.MaxAttempts,
		arg.CreatedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.Selector,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.CsrfHash,
		&i.Kind,
		&i.AdminVersion,
		&i.PasswordVersion,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const createPendingAdminTotpEnrollment = `-- name: CreatePendingAdminTotpEnrollment :one
INSERT INTO admin_totp_enrollments (
    enrollment_id,
    admin_id,
    ciphertext,
    nonce,
    key_version,
    status,
    admin_version,
    operation_id,
    created_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'pending',
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (admin_id) WHERE status = 'pending' DO NOTHING
RETURNING enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
          operation_id, created_at, expires_at, activated_at, disabled_at
`

type CreatePendingAdminTotpEnrollmentParams struct {
	EnrollmentID pgtype.UUID        `json:"enrollment_id"`
	AdminID      pgtype.UUID        `json:"admin_id"`
	Ciphertext   []byte             `json:"ciphertext"`
	Nonce        []byte             `json:"nonce"`
	KeyVersion   int32              `json:"key_version"`
	AdminVersion int64              `json:"admin_version"`
	OperationID  string             `json:"operation_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// CreatePendingAdminTotpEnrollment
//
//	INSERT INTO admin_totp_enrollments (
//	    enrollment_id,
//	    admin_id,
//	    ciphertext,
//	    nonce,
//	    key_version,
//	    status,
//	    admin_version,
//	    operation_id,
//	    created_at,
//	    expires_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    'pending',
//	    $6,
//	    $7,
//	    $8,
//	    $9
//	)
//	ON CONFLICT (admin_id) WHERE status = 'pending' DO NOTHING
//	RETURNING enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
//	          operation_id, created_at, expires_at, activated_at, disabled_at
func (q *Queries) CreatePendingAdminTotpEnrollment(ctx context.Context, arg CreatePendingAdminTotpEnrollmentParams) (AdminTotpEnrollment, error) {
	row := q.db.QueryRow(ctx, createPendingAdminTotpEnrollment,
		arg.EnrollmentID,
		arg.AdminID,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyVersion,
		arg.AdminVersion,
		arg.OperationID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i AdminTotpEnrollment
	err := row.Scan(
		&i.EnrollmentID,
		&i.AdminID,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
		&i.Status,
		&i.AdminVersion,
		&i.OperationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ActivatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const disableActiveAdminTotpEnrollmentCAS = `-- name: DisableActiveAdminTotpEnrollmentCAS :one
UPDATE admin_totp_enrollments
SET status = 'disabled',
    ciphertext = NULL,
    nonce = NULL,
    disabled_at = $1
WHERE admin_id = $2
  AND enrollment_id = $3
  AND status = 'active'
  AND admin_version = $4
RETURNING enrollment_id, admin_id, status, disabled_at
`

type DisableActiveAdminTotpEnrollmentCASParams struct {
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	AdminID              pgtype.UUID        `json:"admin_id"`
	EnrollmentID         pgtype.UUID        `json:"enrollment_id"`
	ExpectedAdminVersion int64              `json:"expected_admin_version"`
}

type DisableActiveAdminTotpEnrollmentCASRow struct {
	EnrollmentID pgtype.UUID        `json:"enrollment_id"`
	AdminID      pgtype.UUID        `json:"admin_id"`
	Status       string             `json:"status"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
}

// DisableActiveAdminTotpEnrollmentCAS
//
//	UPDATE admin_totp_enrollments
//	SET status = 'disabled',
//	    ciphertext = NULL,
//	    nonce = NULL,
//	    disabled_at = $1
//	WHERE admin_id = $2
//	  AND enrollment_id = $3
//	  AND status = 'active'
//	  AND admin_version = $4
//	RETURNING enrollment_id, admin_id, status, disabled_at
func (q *Queries) DisableActiveAdminTotpEnrollmentCAS(ctx context.Context, arg DisableActiveAdminTotpEnrollmentCASParams) (DisableActiveAdminTotpEnrollmentCASRow, error) {
	row := q.db.QueryRow(ctx, disableActiveAdminTotpEnrollmentCAS,
		arg.DisabledAt,
		arg.AdminID,
		arg.EnrollmentID,
		arg.ExpectedAdminVersion,
	)
	var i DisableActiveAdminTotpEnrollmentCASRow
	err := row.Scan(
		&i.EnrollmentID,
		&i.AdminID,
		&i.Status,
		&i.DisabledAt,
	)
	return i, err
}

const getAdminAssistedRecoveryGrantForUpdate = `-- name: GetAdminAssistedRecoveryGrantForUpdate :one
SELECT assisted_grant_id, user_id, selector, secret_hash, purpose, status,
       attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
       consumed_at, revoked_at, result_id
FROM admin_assisted_recovery_grants
WHERE selector = $1
FOR UPDATE
`

type GetAdminAssistedRecoveryGrantForUpdateParams struct {
	Selector string `json:"selector"`
}

// GetAdminAssistedRecoveryGrantForUpdate
//
//	SELECT assisted_grant_id, user_id, selector, secret_hash, purpose, status,
//	       attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
//	       consumed_at, revoked_at, result_id
//	FROM admin_assisted_recovery_grants
//	WHERE selector = $1
//	FOR UPDATE
func (q *Queries) GetAdminAssistedRecoveryGrantForUpdate(ctx context.Context, arg GetAdminAssistedRecoveryGrantForUpdateParams) (AdminAssistedRecoveryGrant, error) {
	row := q.db.QueryRow(ctx, getAdminAssistedRecoveryGrantForUpdate, arg.Selector)
	var i AdminAssistedRecoveryGrant
	err := row.Scan(
		&i.AssistedGrantID,
		&i.UserID,
		&i.Selector,
		&i.SecretHash,
		&i.Purpose,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.CreatedByAdminID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.ResultID,
	)
	return i, err
}

const getAdminChallengeForUpdate = `-- name: GetAdminChallengeForUpdate :one
SELECT challenge_id, admin_id, selector, secret_hash, secret_key_version, purpose,
       audience, admin_version, password_version, origin_hash, request_flow_id,
       attempt_count, max_attempts, status, created_at, expires_at, consumed_at,
       revoked_at, replay_until, operation_id, request_digest, result_id
FROM admin_challenges
WHERE selector = $1
FOR UPDATE
`

type GetAdminChallengeForUpdateParams struct {
	Selector string `json:"selector"`
}

// GetAdminChallengeForUpdate
//
//	SELECT challenge_id, admin_id, selector, secret_hash, secret_key_version, purpose,
//	       audience, admin_version, password_version, origin_hash, request_flow_id,
//	       attempt_count, max_attempts, status, created_at, expires_at, consumed_at,
//	       revoked_at, replay_until, operation_id, request_digest, result_id
//	FROM admin_challenges
//	WHERE selector = $1
//	FOR UPDATE
func (q *Queries) GetAdminChallengeForUpdate(ctx context.Context, arg GetAdminChallengeForUpdateParams) (AdminChallenge, error) {
	row := q.db.QueryRow(ctx, getAdminChallengeForUpdate, arg.Selector)
	var i AdminChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.AdminID,
		&i.Selector,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.Purpose,
		&i.Audience,
		&i.AdminVersion,
		&i.PasswordVersion,
		&i.OriginHash,
		&i.RequestFlowID,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.ReplayUntil,
		&i.OperationID,
		&i.RequestDigest,
		&i.ResultID,
	)
	return i, err
}

const getAdminSessionForUpdate = `-- name: GetAdminSessionForUpdate :one
SELECT session_id, admin_id, selector, secret_hash, secret_key_version, csrf_hash,
       kind, admin_version, password_version, attempt_count, max_attempts, created_at,
       last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
FROM admin_sessions
WHERE selector = $1
FOR UPDATE
`

type GetAdminSessionForUpdateParams struct {
	Selector string `json:"selector"`
}

// GetAdminSessionForUpdate
//
//	SELECT session_id, admin_id, selector, secret_hash, secret_key_version, csrf_hash,
//	       kind, admin_version, password_version, attempt_count, max_attempts, created_at,
//	       last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
//	FROM admin_sessions
//	WHERE selector = $1
//	FOR UPDATE
func (q *Queries) GetAdminSessionForUpdate(ctx context.Context, arg GetAdminSessionForUpdateParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSessionForUpdate, arg.Selector)
	var i AdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.Selector,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.CsrfHash,
		&i.Kind,
		&i.AdminVersion,
		&i.PasswordVersion,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getPendingAdminTotpEnrollmentForUpdate = `-- name: GetPendingAdminTotpEnrollmentForUpdate :one
SELECT enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
       operation_id, created_at, expires_at, activated_at, disabled_at
FROM admin_totp_enrollments
WHERE admin_id = $1
  AND status = 'pending'
FOR UPDATE
`

type GetPendingAdminTotpEnrollmentForUpdateParams struct {
	AdminID pgtype.UUID `json:"admin_id"`
}

// GetPendingAdminTotpEnrollmentForUpdate
//
//	SELECT enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
//	       operation_id, created_at, expires_at, activated_at, disabled_at
//	FROM admin_totp_enrollments
//	WHERE admin_id = $1
//	  AND status = 'pending'
//	FOR UPDATE
func (q *Queries) GetPendingAdminTotpEnrollmentForUpdate(ctx context.Context, arg GetPendingAdminTotpEnrollmentForUpdateParams) (AdminTotpEnrollment, error) {
	row := q.db.QueryRow(ctx, getPendingAdminTotpEnrollmentForUpdate, arg.AdminID)
	var i AdminTotpEnrollment
	err := row.Scan(
		&i.EnrollmentID,
		&i.AdminID,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
		&i.Status,
		&i.AdminVersion,
		&i.OperationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ActivatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getSingletonAdminForUpdate = `-- name: GetSingletonAdminForUpdate :one
SELECT singleton_id, admin_id, username, status, password_hash, password_algorithm,
       password_parameters, password_version, admin_version, last_accepted_totp_step,
       created_at, updated_at
FROM admin_accounts
WHERE singleton_id = 1
FOR UPDATE
`

// GetSingletonAdminForUpdate
//
//	SELECT singleton_id, admin_id, username, status, password_hash, password_algorithm,
//	       password_parameters, password_version, admin_version, last_accepted_totp_step,
//	       created_at, updated_at
//	FROM admin_accounts
//	WHERE singleton_id = 1
//	FOR UPDATE
func (q *Queries) GetSingletonAdminForUpdate(ctx context.Context) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getSingletonAdminForUpdate)
	var i AdminAccount
	err := row.Scan(
		&i.SingletonID,
		&i.AdminID,
		&i.Username,
		&i.Status,
		&i.PasswordHash,
		&i.PasswordAlgorithm,
		&i.PasswordParameters,
		&i.PasswordVersion,
		&i.AdminVersion,
		&i.LastAcceptedTotpStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordAdminAssistedRecoveryFailureCAS = `-- name: RecordAdminAssistedRecoveryFailureCAS :one
UPDATE admin_assisted_recovery_grants
SET attempt_count = attempt_count + 1
WHERE assisted_grant_id = $1
  AND status = 'active'
  AND expires_at > $2
  AND attempt_count < max_attempts
RETURNING assisted_grant_id, attempt_count, max_attempts, status, expires_at
`

type RecordAdminAssistedRecoveryFailureCASParams struct {
	AssistedGrantID pgtype.UUID        `json:"assisted_grant_id"`
	AttemptedAt     pgtype.Timestamptz `json:"attempted_at"`
}

type RecordAdminAssistedRecoveryFailureCASRow struct {
	AssistedGrantID pgtype.UUID        `json:"assisted_grant_id"`
	AttemptCount    int32              `json:"attempt_count"`
	MaxAttempts     int32              `json:"max_attempts"`
	Status          string             `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

// RecordAdminAssistedRecoveryFailureCAS
//
//	UPDATE admin_assisted_recovery_grants
//	SET attempt_count = attempt_count + 1
//	WHERE assisted_grant_id = $1
//	  AND status = 'active'
//	  AND expires_at > $2
//	  AND attempt_count < max_attempts
//	RETURNING assisted_grant_id, attempt_count, max_attempts, status, expires_at
func (q *Queries) RecordAdminAssistedRecoveryFailureCAS(ctx context.Context, arg RecordAdminAssistedRecoveryFailureCASParams) (RecordAdminAssistedRecoveryFailureCASRow, error) {
	row := q.db.QueryRow(ctx, recordAdminAssistedRecoveryFailureCAS, arg.AssistedGrantID, arg.AttemptedAt)
	var i RecordAdminAssistedRecoveryFailureCASRow
	err := row.Scan(
		&i.AssistedGrantID,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const recordAdminChallengeFailureCAS = `-- name: RecordAdminChallengeFailureCAS :one
UPDATE admin_challenges
SET attempt_count = attempt_count + 1
WHERE challenge_id = $1
  AND status = 'active'
  AND expires_at > $2
  AND attempt_count < max_attempts
RETURNING challenge_id, attempt_count, max_attempts, status, expires_at
`

type RecordAdminChallengeFailureCASParams struct {
	ChallengeID pgtype.UUID        `json:"challenge_id"`
	AttemptedAt pgtype.Timestamptz `json:"attempted_at"`
}

type RecordAdminChallengeFailureCASRow struct {
	ChallengeID  pgtype.UUID        `json:"challenge_id"`
	AttemptCount int32              `json:"attempt_count"`
	MaxAttempts  int32              `json:"max_attempts"`
	Status       string             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// RecordAdminChallengeFailureCAS
//
//	UPDATE admin_challenges
//	SET attempt_count = attempt_count + 1
//	WHERE challenge_id = $1
//	  AND status = 'active'
//	  AND expires_at > $2
//	  AND attempt_count < max_attempts
//	RETURNING challenge_id, attempt_count, max_attempts, status, expires_at
func (q *Queries) RecordAdminChallengeFailureCAS(ctx context.Context, arg RecordAdminChallengeFailureCASParams) (RecordAdminChallengeFailureCASRow, error) {
	row := q.db.QueryRow(ctx, recordAdminChallengeFailureCAS, arg.ChallengeID, arg.AttemptedAt)
	var i RecordAdminChallengeFailureCASRow
	err := row.Scan(
		&i.ChallengeID,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeAdminChallenges = `-- name: RevokeAdminChallenges :execrows
UPDATE admin_challenges
SET status = 'revoked',
    revoked_at = $1
WHERE admin_id = $2
  AND status = 'active'
`

type RevokeAdminChallengesParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	AdminID   pgtype.UUID        `json:"admin_id"`
}

// RevokeAdminChallenges
//
//	UPDATE admin_challenges
//	SET status = 'revoked',
//	    revoked_at = $1
//	WHERE admin_id = $2
//	  AND status = 'active'
func (q *Queries) RevokeAdminChallenges(ctx context.Context, arg RevokeAdminChallengesParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAdminChallenges, arg.RevokedAt, arg.AdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAdminRecoveryCodeSet = `-- name: RevokeAdminRecoveryCodeSet :execrows
UPDATE admin_recovery_codes
SET status = 'revoked',
    revoked_at = $1
WHERE admin_id = $2
  AND set_version = $3
  AND status = 'active'
`

type RevokeAdminRecoveryCodeSetParams struct {
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	AdminID    pgtype.UUID        `json:"admin_id"`
	SetVersion int64              `json:"set_version"`
}

// RevokeAdminRecoveryCodeSet
//
//	UPDATE admin_recovery_codes
//	SET status = 'revoked',
//	    revoked_at = $1
//	WHERE admin_id = $2
//	  AND set_version = $3
//	  AND status = 'active'
func (q *Queries) RevokeAdminRecoveryCodeSet(ctx context.Context, arg RevokeAdminRecoveryCodeSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAdminRecoveryCodeSet, arg.RevokedAt, arg.AdminID, arg.SetVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAdminSessionCAS = `-- name: RevokeAdminSessionCAS :one
UPDATE admin_sessions
SET revoked_at = $1,
    revoke_reason = $2
WHERE session_id = $3
  AND revoked_at IS NULL
RETURNING session_id, revoked_at, revoke_reason
`

type RevokeAdminSessionCASParams struct {
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason pgtype.Text        `json:"revoke_reason"`
	SessionID    pgtype.UUID        `json:"session_id"`
}

type RevokeAdminSessionCASRow struct {
	SessionID    pgtype.UUID        `json:"session_id"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason pgtype.Text        `json:"revoke_reason"`
}

// RevokeAdminSessionCAS
//
//	UPDATE admin_sessions
//	SET revoked_at = $1,
//	    revoke_reason = $2
//	WHERE session_id = $3
//	  AND revoked_at IS NULL
//	RETURNING session_id, revoked_at, revoke_reason
func (q *Queries) RevokeAdminSessionCAS(ctx context.Context, arg RevokeAdminSessionCASParams) (RevokeAdminSessionCASRow, error) {
	row := q.db.QueryRow(ctx, revokeAdminSessionCAS, arg.RevokedAt, arg.RevokeReason, arg.SessionID)
	var i RevokeAdminSessionCASRow
	err := row.Scan(&i.SessionID, &i.RevokedAt, &i.RevokeReason)
	return i, err
}

const revokeAllAdminSessions = `-- name: RevokeAllAdminSessions :execrows
UPDATE admin_sessions
SET revoked_at = $1,
    revoke_reason = $2
WHERE admin_id = $3
  AND revoked_at IS NULL
`

type RevokeAllAdminSessionsParams struct {
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason pgtype.Text        `json:"revoke_reason"`
	AdminID      pgtype.UUID        `json:"admin_id"`
}

// RevokeAllAdminSessions
//
//	UPDATE admin_sessions
//	SET revoked_at = $1,
//	    revoke_reason = $2
//	WHERE admin_id = $3
//	  AND revoked_at IS NULL
func (q *Queries) RevokeAllAdminSessions(ctx context.Context, arg RevokeAllAdminSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllAdminSessions, arg.RevokedAt, arg.RevokeReason, arg.AdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAdminSessionCAS = `-- name: TouchAdminSessionCAS :one
UPDATE admin_sessions
SET last_seen_at = $1,
    idle_expires_at = LEAST($2::timestamptz, absolute_expires_at)
WHERE session_id = $3
  AND admin_version = $4
  AND password_version = $5
  AND revoked_at IS NULL
  AND idle_expires_at > $1
  AND absolute_expires_at > $1
RETURNING session_id, kind, last_seen_at, idle_expires_at, absolute_expires_at
`

type TouchAdminSessionCASParams struct {
	SeenAt                  pgtype.Timestamptz `json:"seen_at"`
	IdleExpiresAt           pgtype.Timestamptz `json:"idle_expires_at"`
	SessionID               pgtype.UUID        `json:"session_id"`
	ExpectedAdminVersion    int64              `json:"expected_admin_version"`
	ExpectedPasswordVersion int64              `json:"expected_password_version"`
}

type TouchAdminSessionCASRow struct {
	SessionID         pgtype.UUID        `json:"session_id"`
	Kind              string             `json:"kind"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

// TouchAdminSessionCAS
//
//	UPDATE admin_sessions
//	SET last_seen_at = $1,
//	    idle_expires_at = LEAST($2::timestamptz, absolute_expires_at)
//	WHERE session_id = $3
//	  AND admin_version = $4
//	  AND password_version = $5
//	  AND revoked_at IS NULL
//	  AND idle_expires_at > $1
//	  AND absolute_expires_at > $1
//	RETURNING session_id, kind, last_seen_at, idle_expires_at, absolute_expires_at
func (q *Queries) TouchAdminSessionCAS(ctx context.Context, arg TouchAdminSessionCASParams) (TouchAdminSessionCASRow, error) {
	row := q.db.QueryRow(ctx, touchAdminSessionCAS,
		arg.SeenAt,
		arg.IdleExpiresAt,
		arg.SessionID,
		arg.ExpectedAdminVersion,
		arg.ExpectedPasswordVersion,
	)
	var i TouchAdminSessionCASRow
	err := row.Scan(
		&i.SessionID,
		&i.Kind,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const transitionAdminStatusCAS = `-- name: TransitionAdminStatusCAS :one
UPDATE admin_accounts
SET status = $1,
    admin_version = admin_version + 1,
    updated_at = $2
WHERE singleton_id = 1
  AND admin_id = $3
  AND status = $4
  AND admin_version = $5
RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
`

type TransitionAdminStatusCASParams struct {
	NextStatus           string             `json:"next_status"`
	ChangedAt            pgtype.Timestamptz `json:"changed_at"`
	AdminID              pgtype.UUID        `json:"admin_id"`
	ExpectedStatus       string             `json:"expected_status"`
	ExpectedAdminVersion int64              `json:"expected_admin_version"`
}

type TransitionAdminStatusCASRow struct {
	SingletonID     int16              `json:"singleton_id"`
	AdminID         pgtype.UUID        `json:"admin_id"`
	Status          string             `json:"status"`
	PasswordVersion int64              `json:"password_version"`
	AdminVersion    int64              `json:"admin_version"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// TransitionAdminStatusCAS
//
//	UPDATE admin_accounts
//	SET status = $1,
//	    admin_version = admin_version + 1,
//	    updated_at = $2
//	WHERE singleton_id = 1
//	  AND admin_id = $3
//	  AND status = $4
//	  AND admin_version = $5
//	RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
func (q *Queries) TransitionAdminStatusCAS(ctx context.Context, arg TransitionAdminStatusCASParams) (TransitionAdminStatusCASRow, error) {
	row := q.db.QueryRow(ctx, transitionAdminStatusCAS,
		arg.NextStatus,
		arg.ChangedAt,
		arg.AdminID,
		arg.ExpectedStatus,
		arg.ExpectedAdminVersion,
	)
	var i TransitionAdminStatusCASRow
	err := row.Scan(
		&i.SingletonID,
		&i.AdminID,
		&i.Status,
		&i.PasswordVersion,
		&i.AdminVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminPasswordCAS = `-- name: UpdateAdminPasswordCAS :one
UPDATE admin_accounts
SET password_hash = $1,
    password_algorithm = $2,
    password_parameters = $3,
    password_version = password_version + 1,
    admin_version = admin_version + 1,
    updated_at = $4
WHERE singleton_id = 1
  AND admin_id = $5
  AND status = $6
  AND password_version = $7
  AND admin_version = $8
RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
`

type UpdateAdminPasswordCASParams struct {
	PasswordHash            pgtype.Text        `json:"password_hash"`
	PasswordAlgorithm       pgtype.Text        `json:"password_algorithm"`
	PasswordParameters      pgtype.Text        `json:"password_parameters"`
	ChangedAt               pgtype.Timestamptz `json:"changed_at"`
	AdminID                 pgtype.UUID        `json:"admin_id"`
	ExpectedStatus          string             `json:"expected_status"`
	ExpectedPasswordVersion int64              `json:"expected_password_version"`
	ExpectedAdminVersion    int64              `json:"expected_admin_version"`
}

type UpdateAdminPasswordCASRow struct {
	SingletonID     int16              `json:"singleton_id"`
	AdminID         pgtype.UUID        `json:"admin_id"`
	Status          string             `json:"status"`
	PasswordVersion int64              `json:"password_version"`
	AdminVersion    int64              `json:"admin_version"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// UpdateAdminPasswordCAS
//
//	UPDATE admin_accounts
//	SET password_hash = $1,
//	    password_algorithm = $2,
//	    password_parameters = $3,
//	    password_version = password_version + 1,
//	    admin_version = admin_version + 1,
//	    updated_at = $4
//	WHERE singleton_id = 1
//	  AND admin_id = $5
//	  AND status = $6
//	  AND password_version = $7
//	  AND admin_version = $8
//	RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
func (q *Queries) UpdateAdminPasswordCAS(ctx context.Context, arg UpdateAdminPasswordCASParams) (UpdateAdminPasswordCASRow, error) {
	row := q.db.QueryRow(ctx, updateAdminPasswordCAS,
		arg.PasswordHash,
		arg.PasswordAlgorithm,
		arg.PasswordParameters,
		arg.ChangedAt,
		arg.AdminID,
		arg.ExpectedStatus,
		arg.ExpectedPasswordVersion,
		arg.ExpectedAdminVersion,
	)
	var i UpdateAdminPasswordCASRow
	err := row.Scan(
		&i.SingletonID,
		&i.AdminID,
		&i.Status,
		&i.PasswordVersion,
		&i.AdminVersion,
		&i.UpdatedAt,
	)
	return i, err
}
