// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_export.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAdminExportJob = `-- name: ClaimAdminExportJob :one
WITH candidate AS (
    SELECT export_id
    FROM admin_export_jobs
    WHERE state = 'queued'
       OR (state = 'running' AND lease_until <= pg_catalog.clock_timestamp())
    ORDER BY created_at, export_id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE admin_export_jobs AS job
SET state = 'running',
    lease_owner = $1,
    lease_until = pg_catalog.clock_timestamp() + ($2::bigint * interval '1 second'),
    started_at = COALESCE(job.started_at, pg_catalog.clock_timestamp()),
    version = job.version + 1,
    updated_at = pg_catalog.clock_timestamp()
FROM candidate
WHERE job.export_id = candidate.export_id
RETURNING job.export_id, job.actor_admin_id, job.operation_id, job.request_digest, job.filter_schema_version, job.filter_snapshot, job.filter_digest, job.field_names, job.masking_policy, job.state, job.matched_users, job.exported_users, job.failed_users, job.result_object_key, job.result_digest, job.result_key_version, job.result_schema_version, job.result_expires_at, job.error_message_key, job.lease_owner, job.lease_until, job.version, job.created_at, job.started_at, job.completed_at, job.updated_at
`

type ClaimAdminExportJobParams struct {
	LeaseOwner   pgtype.Text `json:"lease_owner"`
	LeaseSeconds int64       `json:"lease_seconds"`
}

// ClaimAdminExportJob
//
//	WITH candidate AS (
//	    SELECT export_id
//	    FROM admin_export_jobs
//	    WHERE state = 'queued'
//	       OR (state = 'running' AND lease_until <= pg_catalog.clock_timestamp())
//	    ORDER BY created_at, export_id
//	    FOR UPDATE SKIP LOCKED
//	    LIMIT 1
//	)
//	UPDATE admin_export_jobs AS job
//	SET state = 'running',
//	    lease_owner = $1,
//	    lease_until = pg_catalog.clock_timestamp() + ($2::bigint * interval '1 second'),
//	    started_at = COALESCE(job.started_at, pg_catalog.clock_timestamp()),
//	    version = job.version + 1,
//	    updated_at = pg_catalog.clock_timestamp()
//	FROM candidate
//	WHERE job.export_id = candidate.export_id
//	RETURNING job.export_id, job.actor_admin_id, job.operation_id, job.request_digest, job.filter_schema_version, job.filter_snapshot, job.filter_digest, job.field_names, job.masking_policy, job.state, job.matched_users, job.exported_users, job.failed_users, job.result_object_key, job.result_digest, job.result_key_version, job.result_schema_version, job.result_expires_at, job.error_message_key, job.lease_owner, job.lease_until, job.version, job.created_at, job.started_at, job.completed_at, job.updated_at
func (q *Queries) ClaimAdminExportJob(ctx context.Context, arg ClaimAdminExportJobParams) (AdminExportJob, error) {
	row := q.db.QueryRow(ctx, claimAdminExportJob, arg.LeaseOwner, arg.LeaseSeconds)
	var i AdminExportJob
	err := row.Scan(
		&i.ExportID,
		&i.ActorAdminID,
		&i.OperationID,
		&i.RequestDigest,
		&i.FilterSchemaVersion,
		&i.FilterSnapshot,
		&i.FilterDigest,
		&i.FieldNames,
		&i.MaskingPolicy,
		&i.State,
		&i.MatchedUsers,
		&i.ExportedUsers,
		&i.FailedUsers,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ErrorMessageKey,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeAdminExportJobCAS = `-- name: CompleteAdminExportJobCAS :one
UPDATE admin_export_jobs
SET state = $1,
    matched_users = $2,
    exported_users = $3,
    failed_users = $4,
    result_object_key = $5,
    result_digest = $6,
    result_key_version = $7,
    lease_owner = NULL,
    lease_until = NULL,
    completed_at = $8,
    version = version + 1,
    updated_at = $8
WHERE export_id = $9
  AND state = 'running'
  AND lease_owner = $10
  AND version = $11
  AND lease_until > $8
  AND result_expires_at > $8
  AND $1 IN ('succeeded', 'partially_succeeded')
RETURNING export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
`

type CompleteAdminExportJobCASParams struct {
	NextState          string             `json:"next_state"`
	MatchedUsers       int64              `json:"matched_users"`
	ExportedUsers      int64              `json:"exported_users"`
	FailedUsers        int64              `json:"failed_users"`
	ResultObjectKey    pgtype.Text        `json:"result_object_key"`
	ResultDigest       []byte             `json:"result_digest"`
	ResultKeyVersion   pgtype.Int4        `json:"result_key_version"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ExportID           pgtype.UUID        `json:"export_id"`
	ExpectedLeaseOwner pgtype.Text        `json:"expected_lease_owner"`
	ExpectedVersion    int64              `json:"expected_version"`
}

// CompleteAdminExportJobCAS
//
//	UPDATE admin_export_jobs
//	SET state = $1,
//	    matched_users = $2,
//	    exported_users = $3,
//	    failed_users = $4,
//	    result_object_key = $5,
//	    result_digest = $6,
//	    result_key_version = $7,
//	    lease_owner = NULL,
//	    lease_until = NULL,
//	    completed_at = $8,
//	    version = version + 1,
//	    updated_at = $8
//	WHERE export_id = $9
//	  AND state = 'running'
//	  AND lease_owner = $10
//	  AND version = $11
//	  AND lease_until > $8
//	  AND result_expires_at > $8
//	  AND $1 IN ('succeeded', 'partially_succeeded')
//	RETURNING export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
func (q *Queries) CompleteAdminExportJobCAS(ctx context.Context, arg CompleteAdminExportJobCASParams) (AdminExportJob, error) {
	row := q.db.QueryRow(ctx, completeAdminExportJobCAS,
		arg.NextState,
		arg.MatchedUsers,
		arg.ExportedUsers,
		arg.FailedUsers,
		arg.ResultObjectKey,
		arg.ResultDigest,
		arg.ResultKeyVersion,
		arg.CompletedAt,
		arg.ExportID,
		arg.ExpectedLeaseOwner,
		arg.ExpectedVersion,
	)
	var i AdminExportJob
	err := row.Scan(
		&i.ExportID,
		&i.ActorAdminID,
		&i.OperationID,
		&i.RequestDigest,
		&i.FilterSchemaVersion,
		&i.FilterSnapshot,
		&i.FilterDigest,
		&i.FieldNames,
		&i.MaskingPolicy,
		&i.State,
		&i.MatchedUsers,
		&i.ExportedUsers,
		&i.FailedUsers,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ErrorMessageKey,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeAdminExportDownloadGrantCAS = `-- name: ConsumeAdminExportDownloadGrantCAS :one
UPDATE admin_export_download_grants AS download_grant
SET state = 'consumed',
    consumed_at = pg_catalog.clock_timestamp(),
    version = download_grant.version + 1
FROM admin_export_jobs AS export
WHERE download_grant.token_key_version = $1
  AND download_grant.token_digest = $2
  AND download_grant.state = 'active'
  AND download_grant.created_at <= pg_catalog.clock_timestamp()
  AND download_grant.expires_at > pg_catalog.clock_timestamp()
  AND download_grant.actor_admin_id = $3
  AND download_grant.session_id = $4
  AND export.export_id = download_grant.export_id
  AND export.version = download_grant.expected_export_version
  AND export.masking_policy = download_grant.masking_policy
  AND export.state IN ('succeeded', 'partially_succeeded')
  AND export.result_expires_at > pg_catalog.clock_timestamp()
RETURNING download_grant.grant_id, download_grant.export_id, download_grant.actor_admin_id, download_grant.session_id, download_grant.operation_id, download_grant.request_digest, download_grant.token_digest, download_grant.token_key_version, download_grant.expected_export_version, download_grant.masking_policy, download_grant.state, download_grant.created_at, download_grant.expires_at, download_grant.consumed_at, download_grant.revoked_at, download_grant.version, export.result_object_key, export.result_digest,
          export.result_key_version, export.result_schema_version, export.result_expires_at,
          export.version AS export_version
`

type ConsumeAdminExportDownloadGrantCASParams struct {
	TokenKeyVersion int32       `json:"token_key_version"`
	TokenDigest     []byte      `json:"token_digest"`
	ActorAdminID    pgtype.UUID `json:"actor_admin_id"`
	SessionID       pgtype.UUID `json:"session_id"`
}

type ConsumeAdminExportDownloadGrantCASRow struct {
	GrantID               pgtype.UUID        `json:"grant_id"`
	ExportID              pgtype.UUID        `json:"export_id"`
	ActorAdminID          pgtype.UUID        `json:"actor_admin_id"`
	SessionID             pgtype.UUID        `json:"session_id"`
	OperationID           string             `json:"operation_id"`
	RequestDigest         []byte             `json:"request_digest"`
	TokenDigest           []byte             `json:"token_digest"`
	TokenKeyVersion       int32              `json:"token_key_version"`
	ExpectedExportVersion int64              `json:"expected_export_version"`
	MaskingPolicy         string             `json:"masking_policy"`
	State                 string             `json:"state"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt            pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	Version               int64              `json:"version"`
	ResultObjectKey       pgtype.Text        `json:"result_object_key"`
	ResultDigest          []byte             `json:"result_digest"`
	ResultKeyVersion      pgtype.Int4        `json:"result_key_version"`
	ResultSchemaVersion   int32              `json:"result_schema_version"`
	ResultExpiresAt       pgtype.Timestamptz `json:"result_expires_at"`
	ExportVersion         int64              `json:"export_version"`
}

// ConsumeAdminExportDownloadGrantCAS
//
//	UPDATE admin_export_download_grants AS download_grant
//	SET state = 'consumed',
//	    consumed_at = pg_catalog.clock_timestamp(),
//	    version = download_grant.version + 1
//	FROM admin_export_jobs AS export
//	WHERE download_grant.token_key_version = $1
//	  AND download_grant.token_digest = $2
//	  AND download_grant.state = 'active'
//	  AND download_grant.created_at <= pg_catalog.clock_timestamp()
//	  AND download_grant.expires_at > pg_catalog.clock_timestamp()
//	  AND download_grant.actor_admin_id = $3
//	  AND download_grant.session_id = $4
//	  AND export.export_id = download_grant.export_id
//	  AND export.version = download_grant.expected_export_version
//	  AND export.masking_policy = download_grant.masking_policy
//	  AND export.state IN ('succeeded', 'partially_succeeded')
//	  AND export.result_expires_at > pg_catalog.clock_timestamp()
//	RETURNING download_grant.grant_id, download_grant.export_id, download_grant.actor_admin_id, download_grant.session_id, download_grant.operation_id, download_grant.request_digest, download_grant.token_digest, download_grant.token_key_version, download_grant.expected_export_version, download_grant.masking_policy, download_grant.state, download_grant.created_at, download_grant.expires_at, download_grant.consumed_at, download_grant.revoked_at, download_grant.version, export.result_object_key, export.result_digest,
//	          export.result_key_version, export.result_schema_version, export.result_expires_at,
//	          export.version AS export_version
func (q *Queries) ConsumeAdminExportDownloadGrantCAS(ctx context.Context, arg ConsumeAdminExportDownloadGrantCASParams) (ConsumeAdminExportDownloadGrantCASRow, error) {
	row := q.db.QueryRow(ctx, consumeAdminExportDownloadGrantCAS,
		arg.TokenKeyVersion,
		arg.TokenDigest,
		arg.ActorAdminID,
		arg.SessionID,
	)
	var i ConsumeAdminExportDownloadGrantCASRow
	err := row.Scan(
		&i.GrantID,
		&i.ExportID,
		&i.ActorAdminID,
		&i.SessionID,
		&i.OperationID,
		&i.RequestDigest,
		&i.TokenDigest,
		&i.TokenKeyVersion,
		&i.ExpectedExportVersion,
		&i.MaskingPolicy,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.Version,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ExportVersion,
	)
	return i, err
}

const createAdminExportDownloadGrant = `-- name: CreateAdminExportDownloadGrant :one
INSERT INTO admin_export_download_grants (
    grant_id, export_id, actor_admin_id, session_id, operation_id, request_digest,
    token_digest, token_key_version, expected_export_version, state,
    masking_policy, created_at, expires_at, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, 'active', $10,
    $11, $12, 1
)
ON CONFLICT (actor_admin_id, operation_id) DO UPDATE
SET operation_id = EXCLUDED.operation_id
WHERE admin_export_download_grants.request_digest = EXCLUDED.request_digest
RETURNING grant_id, export_id, actor_admin_id, session_id, operation_id, request_digest, token_digest, token_key_version, expected_export_version, masking_policy, state, created_at, expires_at, consumed_at, revoked_at, version
`

type CreateAdminExportDownloadGrantParams struct {
	GrantID               pgtype.UUID        `json:"grant_id"`
	ExportID              pgtype.UUID        `json:"export_id"`
	ActorAdminID          pgtype.UUID        `json:"actor_admin_id"`
	SessionID             pgtype.UUID        `json:"session_id"`
	OperationID           string             `json:"operation_id"`
	RequestDigest         []byte             `json:"request_digest"`
	TokenDigest           []byte             `json:"token_digest"`
	TokenKeyVersion       int32              `json:"token_key_version"`
	ExpectedExportVersion int64              `json:"expected_export_version"`
	MaskingPolicy         string             `json:"masking_policy"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

// CreateAdminExportDownloadGrant
//
//	INSERT INTO admin_export_download_grants (
//	    grant_id, export_id, actor_admin_id, session_id, operation_id, request_digest,
//	    token_digest, token_key_version, expected_export_version, state,
//	    masking_policy, created_at, expires_at, version
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6,
//	    $7, $8, $9, 'active', $10,
//	    $11, $12, 1
//	)
//	ON CONFLICT (actor_admin_id, operation_id) DO UPDATE
//	SET operation_id = EXCLUDED.operation_id
//	WHERE admin_export_download_grants.request_digest = EXCLUDED.request_digest
//	RETURNING grant_id, export_id, actor_admin_id, session_id, operation_id, request_digest, token_digest, token_key_version, expected_export_version, masking_policy, state, created_at, expires_at, consumed_at, revoked_at, version
func (q *Queries) CreateAdminExportDownloadGrant(ctx context.Context, arg CreateAdminExportDownloadGrantParams) (AdminExportDownloadGrant, error) {
	row := q.db.QueryRow(ctx, createAdminExportDownloadGrant,
		arg.GrantID,
		arg.ExportID,
		arg.ActorAdminID,
		arg.SessionID,
		arg.OperationID,
		arg.RequestDigest,
		arg.TokenDigest,
		arg.TokenKeyVersion,
		arg.ExpectedExportVersion,
		arg.MaskingPolicy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i AdminExportDownloadGrant
	err := row.Scan(
		&i.GrantID,
		&i.ExportID,
		&i.ActorAdminID,
		&i.SessionID,
		&i.OperationID,
		&i.RequestDigest,
		&i.TokenDigest,
		&i.TokenKeyVersion,
		&i.ExpectedExportVersion,
		&i.MaskingPolicy,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.Version,
	)
	return i, err
}

const createAdminExportJob = `-- name: CreateAdminExportJob :one
INSERT INTO admin_export_jobs (
    export_id, actor_admin_id, operation_id, request_digest, filter_schema_version,
    filter_snapshot, filter_digest, field_names, masking_policy, state,
    matched_users, exported_users, failed_users, result_schema_version,
    result_expires_at, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, 'queued',
    0, 0, 0, $10, $11, 1, $12, $12
)
ON CONFLICT (actor_admin_id, operation_id) DO UPDATE
SET operation_id = EXCLUDED.operation_id
WHERE admin_export_jobs.request_digest = EXCLUDED.request_digest
RETURNING export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
`

type CreateAdminExportJobParams struct {
	ExportID            pgtype.UUID        `json:"export_id"`
	ActorAdminID        pgtype.UUID        `json:"actor_admin_id"`
	OperationID         string             `json:"operation_id"`
	RequestDigest       []byte             `json:"request_digest"`
	FilterSchemaVersion int32              `json:"filter_schema_version"`
	FilterSnapshot      []byte             `json:"filter_snapshot"`
	FilterDigest        []byte             `json:"filter_digest"`
	FieldNames          []string           `json:"field_names"`
	MaskingPolicy       string             `json:"masking_policy"`
	ResultSchemaVersion int32              `json:"result_schema_version"`
	ResultExpiresAt     pgtype.Timestamptz `json:"result_expires_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

// CreateAdminExportJob
//
//	INSERT INTO admin_export_jobs (
//	    export_id, actor_admin_id, operation_id, request_digest, filter_schema_version,
//	    filter_snapshot, filter_digest, field_names, masking_policy, state,
//	    matched_users, exported_users, failed_users, result_schema_version,
//	    result_expires_at, version, created_at, updated_at
//	) VALUES (
//	    $1, $2, $3, $4, $5,
//	    $6, $7, $8, $9, 'queued',
//	    0, 0, 0, $10, $11, 1, $12, $12
//	)
//	ON CONFLICT (actor_admin_id, operation_id) DO UPDATE
//	SET operation_id = EXCLUDED.operation_id
//	WHERE admin_export_jobs.request_digest = EXCLUDED.request_digest
//	RETURNING export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
func (q *Queries) CreateAdminExportJob(ctx context.Context, arg CreateAdminExportJobParams) (AdminExportJob, error) {
	row := q.db.QueryRow(ctx, createAdminExportJob,
		arg.ExportID,
		arg.ActorAdminID,
		arg.OperationID,
		arg.RequestDigest,
		arg.FilterSchemaVersion,
		arg.FilterSnapshot,
		arg.FilterDigest,
		arg.FieldNames,
		arg.MaskingPolicy,
		arg.ResultSchemaVersion,
		arg.ResultExpiresAt,
		arg.CreatedAt,
	)
	var i AdminExportJob
	err := row.Scan(
		&i.ExportID,
		&i.ActorAdminID,
		&i.OperationID,
		&i.RequestDigest,
		&i.FilterSchemaVersion,
		&i.FilterSnapshot,
		&i.FilterDigest,
		&i.FieldNames,
		&i.MaskingPolicy,
		&i.State,
		&i.MatchedUsers,
		&i.ExportedUsers,
		&i.FailedUsers,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ErrorMessageKey,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdminExportResultCAS = `-- name: DeleteAdminExportResultCAS :one
UPDATE admin_export_jobs
SET state = 'deleted',
    result_object_key = NULL,
    result_digest = NULL,
    result_key_version = NULL,
    version = version + 1,
    updated_at = $1
WHERE export_id = $2
  AND version = $3
  AND state IN ('succeeded', 'partially_succeeded', 'expired')
RETURNING export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
`

type DeleteAdminExportResultCASParams struct {
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	ExportID        pgtype.UUID        `json:"export_id"`
	ExpectedVersion int64              `json:"expected_version"`
}

// DeleteAdminExportResultCAS
//
//	UPDATE admin_export_jobs
//	SET state = 'deleted',
//	    result_object_key = NULL,
//	    result_digest = NULL,
//	    result_key_version = NULL,
//	    version = version + 1,
//	    updated_at = $1
//	WHERE export_id = $2
//	  AND version = $3
//	  AND state IN ('succeeded', 'partially_succeeded', 'expired')
//	RETURNING export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
func (q *Queries) DeleteAdminExportResultCAS(ctx context.Context, arg DeleteAdminExportResultCASParams) (AdminExportJob, error) {
	row := q.db.QueryRow(ctx, deleteAdminExportResultCAS, arg.DeletedAt, arg.ExportID, arg.ExpectedVersion)
	var i AdminExportJob
	err := row.Scan(
		&i.ExportID,
		&i.ActorAdminID,
		&i.OperationID,
		&i.RequestDigest,
		&i.FilterSchemaVersion,
		&i.FilterSnapshot,
		&i.FilterDigest,
		&i.FieldNames,
		&i.MaskingPolicy,
		&i.State,
		&i.MatchedUsers,
		&i.ExportedUsers,
		&i.FailedUsers,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ErrorMessageKey,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireAdminExportResults = `-- name: ExpireAdminExportResults :many
UPDATE admin_export_jobs
SET state = 'expired',
    result_object_key = NULL,
    result_digest = NULL,
    result_key_version = NULL,
    completed_at = COALESCE(completed_at, $1),
    version = version + 1,
    updated_at = $1
WHERE state IN ('succeeded', 'partially_succeeded')
  AND result_expires_at <= $1
RETURNING export_id
`

type ExpireAdminExportResultsParams struct {
	Boundary pgtype.Timestamptz `json:"boundary"`
}

// ExpireAdminExportResults
//
//	UPDATE admin_export_jobs
//	SET state = 'expired',
//	    result_object_key = NULL,
//	    result_digest = NULL,
//	    result_key_version = NULL,
//	    completed_at = COALESCE(completed_at, $1),
//	    version = version + 1,
//	    updated_at = $1
//	WHERE state IN ('succeeded', 'partially_succeeded')
//	  AND result_expires_at <= $1
//	RETURNING export_id
func (q *Queries) ExpireAdminExportResults(ctx context.Context, arg ExpireAdminExportResultsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, expireAdminExportResults, arg.Boundary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var export_id pgtype.UUID
		if err := rows.Scan(&export_id); err != nil {
			return nil, err
		}
		items = append(items, export_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failAdminExportJobCAS = `-- name: FailAdminExportJobCAS :one
UPDATE admin_export_jobs
SET state = 'failed',
    matched_users = $1,
    exported_users = $2,
    failed_users = $3,
    error_message_key = $4,
    lease_owner = NULL,
    lease_until = NULL,
    completed_at = $5,
    version = version + 1,
    updated_at = $5
WHERE export_id = $6
  AND state = 'running'
  AND lease_owner = $7
  AND version = $8
  AND lease_until > $5
RETURNING export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
`

type FailAdminExportJobCASParams struct {
	MatchedUsers       int64              `json:"matched_users"`
	ExportedUsers      int64              `json:"exported_users"`
	FailedUsers        int64              `json:"failed_users"`
	ErrorMessageKey    pgtype.Text        `json:"error_message_key"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ExportID           pgtype.UUID        `json:"export_id"`
	ExpectedLeaseOwner pgtype.Text        `json:"expected_lease_owner"`
	ExpectedVersion    int64              `json:"expected_version"`
}

// FailAdminExportJobCAS
//
//	UPDATE admin_export_jobs
//	SET state = 'failed',
//	    matched_users = $1,
//	    exported_users = $2,
//	    failed_users = $3,
//	    error_message_key = $4,
//	    lease_owner = NULL,
//	    lease_until = NULL,
//	    completed_at = $5,
//	    version = version + 1,
//	    updated_at = $5
//	WHERE export_id = $6
//	  AND state = 'running'
//	  AND lease_owner = $7
//	  AND version = $8
//	  AND lease_until > $5
//	RETURNING export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
func (q *Queries) FailAdminExportJobCAS(ctx context.Context, arg FailAdminExportJobCASParams) (AdminExportJob, error) {
	row := q.db.QueryRow(ctx, failAdminExportJobCAS,
		arg.MatchedUsers,
		arg.ExportedUsers,
		arg.FailedUsers,
		arg.ErrorMessageKey,
		arg.CompletedAt,
		arg.ExportID,
		arg.ExpectedLeaseOwner,
		arg.ExpectedVersion,
	)
	var i AdminExportJob
	err := row.Scan(
		&i.ExportID,
		&i.ActorAdminID,
		&i.OperationID,
		&i.RequestDigest,
		&i.FilterSchemaVersion,
		&i.FilterSnapshot,
		&i.FilterDigest,
		&i.FieldNames,
		&i.MaskingPolicy,
		&i.State,
		&i.MatchedUsers,
		&i.ExportedUsers,
		&i.FailedUsers,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ErrorMessageKey,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminExportJob = `-- name: GetAdminExportJob :one
SELECT export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
FROM admin_export_jobs
WHERE export_id = $1
`

type GetAdminExportJobParams struct {
	ExportID pgtype.UUID `json:"export_id"`
}

// GetAdminExportJob
//
//	SELECT export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
//	FROM admin_export_jobs
//	WHERE export_id = $1
func (q *Queries) GetAdminExportJob(ctx context.Context, arg GetAdminExportJobParams) (AdminExportJob, error) {
	row := q.db.QueryRow(ctx, getAdminExportJob, arg.ExportID)
	var i AdminExportJob
	err := row.Scan(
		&i.ExportID,
		&i.ActorAdminID,
		&i.OperationID,
		&i.RequestDigest,
		&i.FilterSchemaVersion,
		&i.FilterSnapshot,
		&i.FilterDigest,
		&i.FieldNames,
		&i.MaskingPolicy,
		&i.State,
		&i.MatchedUsers,
		&i.ExportedUsers,
		&i.FailedUsers,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ErrorMessageKey,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminExportJobByOperation = `-- name: GetAdminExportJobByOperation :one
SELECT export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
FROM admin_export_jobs
WHERE actor_admin_id = $1
  AND operation_id = $2
`

type GetAdminExportJobByOperationParams struct {
	ActorAdminID pgtype.UUID `json:"actor_admin_id"`
	OperationID  string      `json:"operation_id"`
}

// GetAdminExportJobByOperation
//
//	SELECT export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
//	FROM admin_export_jobs
//	WHERE actor_admin_id = $1
//	  AND operation_id = $2
func (q *Queries) GetAdminExportJobByOperation(ctx context.Context, arg GetAdminExportJobByOperationParams) (AdminExportJob, error) {
	row := q.db.QueryRow(ctx, getAdminExportJobByOperation, arg.ActorAdminID, arg.OperationID)
	var i AdminExportJob
	err := row.Scan(
		&i.ExportID,
		&i.ActorAdminID,
		&i.OperationID,
		&i.RequestDigest,
		&i.FilterSchemaVersion,
		&i.FilterSnapshot,
		&i.FilterDigest,
		&i.FieldNames,
		&i.MaskingPolicy,
		&i.State,
		&i.MatchedUsers,
		&i.ExportedUsers,
		&i.FailedUsers,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ErrorMessageKey,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminExportJobForDownloadGrant = `-- name: GetAdminExportJobForDownloadGrant :one
SELECT export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
FROM admin_export_jobs
WHERE export_id = $1
FOR SHARE
`

type GetAdminExportJobForDownloadGrantParams struct {
	ExportID pgtype.UUID `json:"export_id"`
}

// GetAdminExportJobForDownloadGrant
//
//	SELECT export_id, actor_admin_id, operation_id, request_digest, filter_schema_version, filter_snapshot, filter_digest, field_names, masking_policy, state, matched_users, exported_users, failed_users, result_object_key, result_digest, result_key_version, result_schema_version, result_expires_at, error_message_key, lease_owner, lease_until, version, created_at, started_at, completed_at, updated_at
//	FROM admin_export_jobs
//	WHERE export_id = $1
//	FOR SHARE
func (q *Queries) GetAdminExportJobForDownloadGrant(ctx context.Context, arg GetAdminExportJobForDownloadGrantParams) (AdminExportJob, error) {
	row := q.db.QueryRow(ctx, getAdminExportJobForDownloadGrant, arg.ExportID)
	var i AdminExportJob
	err := row.Scan(
		&i.ExportID,
		&i.ActorAdminID,
		&i.OperationID,
		&i.RequestDigest,
		&i.FilterSchemaVersion,
		&i.FilterSnapshot,
		&i.FilterDigest,
		&i.FieldNames,
		&i.MaskingPolicy,
		&i.State,
		&i.MatchedUsers,
		&i.ExportedUsers,
		&i.FailedUsers,
		&i.ResultObjectKey,
		&i.ResultDigest,
		&i.ResultKeyVersion,
		&i.ResultSchemaVersion,
		&i.ResultExpiresAt,
		&i.ErrorMessageKey,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
