// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
WITH result AS (
    SELECT pg_catalog.to_jsonb(function_row) AS payload
    FROM append_audit_event(
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    ) AS function_row
)
SELECT (result.payload ->> 'appended_sequence')::bigint AS appended_sequence,
       decode(pg_catalog.substring(result.payload ->> 'appended_hash', 3), 'hex') AS appended_hash
FROM result
`

type AppendAuditEventParams struct {
	ChainID              string             `json:"chain_id"`
	ExpectedPreviousHash []byte             `json:"expected_previous_hash"`
	EventID              pgtype.UUID        `json:"event_id"`
	CanonicalEvent       []byte             `json:"canonical_event"`
	Signature            []byte             `json:"signature"`
	SigningKeyVersion    int32              `json:"signing_key_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type AppendAuditEventRow struct {
	AppendedSequence int64  `json:"appended_sequence"`
	AppendedHash     []byte `json:"appended_hash"`
}

// AppendAuditEvent
//
//	WITH result AS (
//	    SELECT pg_catalog.to_jsonb(function_row) AS payload
//	    FROM append_audit_event(
//	        $1,
//	        $2,
//	        $3,
//	        $4,
//	        $5,
//	        $6,
//	        $7
//	    ) AS function_row
//	)
//	SELECT (result.payload ->> 'appended_sequence')::bigint AS appended_sequence,
//	       decode(pg_catalog.substring(result.payload ->> 'appended_hash', 3), 'hex') AS appended_hash
//	FROM result
func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AppendAuditEventRow, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.ChainID,
		arg.ExpectedPreviousHash,
		arg.EventID,
		arg.CanonicalEvent,
		arg.Signature,
		arg.SigningKeyVersion,
		arg.CreatedAt,
	)
	var i AppendAuditEventRow
	err := row.Scan(&i.AppendedSequence, &i.AppendedHash)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT chain_id, sequence, event_id, previous_hash, canonical_event, event_hash,
       signature, signing_key_version, created_at
FROM audit_events_redacted
WHERE chain_id = $1
  AND sequence > $2
ORDER BY sequence
LIMIT $3
`

type ListAuditEventsParams struct {
	ChainID       string `json:"chain_id"`
	AfterSequence int64  `json:"after_sequence"`
	PageSize      int32  `json:"page_size"`
}

// ListAuditEvents
//
//	SELECT chain_id, sequence, event_id, previous_hash, canonical_event, event_hash,
//	       signature, signing_key_version, created_at
//	FROM audit_events_redacted
//	WHERE chain_id = $1
//	  AND sequence > $2
//	ORDER BY sequence
//	LIMIT $3
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEventsRedacted, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.ChainID, arg.AfterSequence, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEventsRedacted{}
	for rows.Next() {
		var i AuditEventsRedacted
		if err := rows.Scan(
			&i.ChainID,
			&i.Sequence,
			&i.EventID,
			&i.PreviousHash,
			&i.CanonicalEvent,
			&i.EventHash,
			&i.Signature,
			&i.SigningKeyVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readAuditHead = `-- name: ReadAuditHead :one
WITH result AS (
    SELECT pg_catalog.to_jsonb(function_row) AS payload
    FROM read_audit_head($1) AS function_row
)
SELECT (result.payload ->> 'sequence')::bigint AS sequence,
       decode(pg_catalog.substring(result.payload ->> 'head_hash', 3), 'hex') AS head_hash
FROM result
`

type ReadAuditHeadParams struct {
	ChainID string `json:"chain_id"`
}

type ReadAuditHeadRow struct {
	Sequence int64  `json:"sequence"`
	HeadHash []byte `json:"head_hash"`
}

// ReadAuditHead
//
//	WITH result AS (
//	    SELECT pg_catalog.to_jsonb(function_row) AS payload
//	    FROM read_audit_head($1) AS function_row
//	)
//	SELECT (result.payload ->> 'sequence')::bigint AS sequence,
//	       decode(pg_catalog.substring(result.payload ->> 'head_hash', 3), 'hex') AS head_hash
//	FROM result
func (q *Queries) ReadAuditHead(ctx context.Context, arg ReadAuditHeadParams) (ReadAuditHeadRow, error) {
	row := q.db.QueryRow(ctx, readAuditHead, arg.ChainID)
	var i ReadAuditHeadRow
	err := row.Scan(&i.Sequence, &i.HeadHash)
	return i, err
}

const resetAdminAccount = `-- name: ResetAdminAccount :one
WITH result AS (
    SELECT pg_catalog.to_jsonb(function_row) AS payload
    FROM reset_admin_account(
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11
    ) AS function_row
)
SELECT (result.payload ->> 'appended_sequence')::bigint AS appended_sequence,
       decode(pg_catalog.substring(result.payload ->> 'appended_hash', 3), 'hex') AS appended_hash
FROM result
`

type ResetAdminAccountParams struct {
	ExpectedPreviousHash []byte             `json:"expected_previous_hash"`
	EventID              pgtype.UUID        `json:"event_id"`
	CanonicalEvent       []byte             `json:"canonical_event"`
	Signature            []byte             `json:"signature"`
	SigningKeyVersion    int32              `json:"signing_key_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	PasswordHash         string             `json:"password_hash"`
	PasswordAlgorithm    string             `json:"password_algorithm"`
	PasswordParameters   string             `json:"password_parameters"`
	CheckpointEventID    pgtype.UUID        `json:"checkpoint_event_id"`
	CheckpointPayload    []byte             `json:"checkpoint_payload"`
}

type ResetAdminAccountRow struct {
	AppendedSequence int64  `json:"appended_sequence"`
	AppendedHash     []byte `json:"appended_hash"`
}

// ResetAdminAccount
//
//	WITH result AS (
//	    SELECT pg_catalog.to_jsonb(function_row) AS payload
//	    FROM reset_admin_account(
//	        $1,
//	        $2,
//	        $3,
//	        $4,
//	        $5,
//	        $6,
//	        $7,
//	        $8,
//	        $9,
//	        $10,
//	        $11
//	    ) AS function_row
//	)
//	SELECT (result.payload ->> 'appended_sequence')::bigint AS appended_sequence,
//	       decode(pg_catalog.substring(result.payload ->> 'appended_hash', 3), 'hex') AS appended_hash
//	FROM result
func (q *Queries) ResetAdminAccount(ctx context.Context, arg ResetAdminAccountParams) (ResetAdminAccountRow, error) {
	row := q.db.QueryRow(ctx, resetAdminAccount,
		arg.ExpectedPreviousHash,
		arg.EventID,
		arg.CanonicalEvent,
		arg.Signature,
		arg.SigningKeyVersion,
		arg.CreatedAt,
		arg.PasswordHash,
		arg.PasswordAlgorithm,
		arg.PasswordParameters,
		arg.CheckpointEventID,
		arg.CheckpointPayload,
	)
	var i ResetAdminAccountRow
	err := row.Scan(&i.AppendedSequence, &i.AppendedHash)
	return i, err
}
