// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_session.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireGameSessionOwnershipCAS = `-- name: AcquireGameSessionOwnershipCAS :one
UPDATE game_sessions
SET ownership_epoch = ownership_epoch + 1,
    updated_at = $1
WHERE session_id = $2
  AND state_version = $3
  AND ownership_epoch = $4
  AND status IN ('active', 'suspended')
RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
`

type AcquireGameSessionOwnershipCASParams struct {
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	SessionID              pgtype.UUID        `json:"session_id"`
	ExpectedStateVersion   int64              `json:"expected_state_version"`
	ExpectedOwnershipEpoch int64              `json:"expected_ownership_epoch"`
}

// AcquireGameSessionOwnershipCAS
//
//	UPDATE game_sessions
//	SET ownership_epoch = ownership_epoch + 1,
//	    updated_at = $1
//	WHERE session_id = $2
//	  AND state_version = $3
//	  AND ownership_epoch = $4
//	  AND status IN ('active', 'suspended')
//	RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
//	    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
//	    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
func (q *Queries) AcquireGameSessionOwnershipCAS(ctx context.Context, arg AcquireGameSessionOwnershipCASParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, acquireGameSessionOwnershipCAS,
		arg.UpdatedAt,
		arg.SessionID,
		arg.ExpectedStateVersion,
		arg.ExpectedOwnershipEpoch,
	)
	var i GameSession
	err := row.Scan(
		&i.SessionID,
		&i.RoomID,
		&i.GameID,
		&i.EngineVersion,
		&i.ProtocolVersion,
		&i.ClientVersion,
		&i.StateVersion,
		&i.OwnershipEpoch,
		&i.SnapshotVersion,
		&i.StateMessageType,
		&i.StateSchemaVersion,
		&i.StatePayload,
		&i.NextDeadlineAt,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const createGameActionReceipt = `-- name: CreateGameActionReceipt :one
INSERT INTO game_action_receipts (
    session_id,
    actor_user_id,
    action_id,
    request_digest,
    result_code,
    result_digest,
    committed_state_version,
    committed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (session_id, actor_user_id, action_id) DO NOTHING
RETURNING session_id, actor_user_id, action_id, request_digest, result_code,
    result_digest, committed_state_version, committed_at
`

type CreateGameActionReceiptParams struct {
	SessionID             pgtype.UUID        `json:"session_id"`
	ActorUserID           pgtype.UUID        `json:"actor_user_id"`
	ActionID              string             `json:"action_id"`
	RequestDigest         []byte             `json:"request_digest"`
	ResultCode            string             `json:"result_code"`
	ResultDigest          []byte             `json:"result_digest"`
	CommittedStateVersion int64              `json:"committed_state_version"`
	CommittedAt           pgtype.Timestamptz `json:"committed_at"`
}

// CreateGameActionReceipt
//
//	INSERT INTO game_action_receipts (
//	    session_id,
//	    actor_user_id,
//	    action_id,
//	    request_digest,
//	    result_code,
//	    result_digest,
//	    committed_state_version,
//	    committed_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8
//	)
//	ON CONFLICT (session_id, actor_user_id, action_id) DO NOTHING
//	RETURNING session_id, actor_user_id, action_id, request_digest, result_code,
//	    result_digest, committed_state_version, committed_at
func (q *Queries) CreateGameActionReceipt(ctx context.Context, arg CreateGameActionReceiptParams) (GameActionReceipt, error) {
	row := q.db.QueryRow(ctx, createGameActionReceipt,
		arg.SessionID,
		arg.ActorUserID,
		arg.ActionID,
		arg.RequestDigest,
		arg.ResultCode,
		arg.ResultDigest,
		arg.CommittedStateVersion,
		arg.CommittedAt,
	)
	var i GameActionReceipt
	err := row.Scan(
		&i.SessionID,
		&i.ActorUserID,
		&i.ActionID,
		&i.RequestDigest,
		&i.ResultCode,
		&i.ResultDigest,
		&i.CommittedStateVersion,
		&i.CommittedAt,
	)
	return i, err
}

const createGameSession = `-- name: CreateGameSession :one
INSERT INTO game_sessions (
    session_id,
    room_id,
    game_id,
    engine_version,
    protocol_version,
    client_version,
    state_version,
    ownership_epoch,
    snapshot_version,
    state_message_type,
    state_schema_version,
    state_payload,
    next_deadline_at,
    status,
    started_at,
    updated_at,
    ended_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
`

type CreateGameSessionParams struct {
	SessionID          pgtype.UUID        `json:"session_id"`
	RoomID             pgtype.UUID        `json:"room_id"`
	GameID             string             `json:"game_id"`
	EngineVersion      string             `json:"engine_version"`
	ProtocolVersion    string             `json:"protocol_version"`
	ClientVersion      string             `json:"client_version"`
	StateVersion       int64              `json:"state_version"`
	OwnershipEpoch     int64              `json:"ownership_epoch"`
	SnapshotVersion    int32              `json:"snapshot_version"`
	StateMessageType   string             `json:"state_message_type"`
	StateSchemaVersion int32              `json:"state_schema_version"`
	StatePayload       []byte             `json:"state_payload"`
	NextDeadlineAt     pgtype.Timestamptz `json:"next_deadline_at"`
	Status             string             `json:"status"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
}

// CreateGameSession
//
//	INSERT INTO game_sessions (
//	    session_id,
//	    room_id,
//	    game_id,
//	    engine_version,
//	    protocol_version,
//	    client_version,
//	    state_version,
//	    ownership_epoch,
//	    snapshot_version,
//	    state_message_type,
//	    state_schema_version,
//	    state_payload,
//	    next_deadline_at,
//	    status,
//	    started_at,
//	    updated_at,
//	    ended_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    $12,
//	    $13,
//	    $14,
//	    $15,
//	    $16,
//	    $17
//	)
//	RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
//	    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
//	    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, createGameSession,
		arg.SessionID,
		arg.RoomID,
		arg.GameID,
		arg.EngineVersion,
		arg.ProtocolVersion,
		arg.ClientVersion,
		arg.StateVersion,
		arg.OwnershipEpoch,
		arg.SnapshotVersion,
		arg.StateMessageType,
		arg.StateSchemaVersion,
		arg.StatePayload,
		arg.NextDeadlineAt,
		arg.Status,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.EndedAt,
	)
	var i GameSession
	err := row.Scan(
		&i.SessionID,
		&i.RoomID,
		&i.GameID,
		&i.EngineVersion,
		&i.ProtocolVersion,
		&i.ClientVersion,
		&i.StateVersion,
		&i.OwnershipEpoch,
		&i.SnapshotVersion,
		&i.StateMessageType,
		&i.StateSchemaVersion,
		&i.StatePayload,
		&i.NextDeadlineAt,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const createGameSessionEvent = `-- name: CreateGameSessionEvent :exec
INSERT INTO game_session_events (batch_id, event_ordinal, message_type, schema_version, payload)
VALUES (
    $1, $2, $3,
    $4, $5
)
`

type CreateGameSessionEventParams struct {
	BatchID       pgtype.UUID `json:"batch_id"`
	EventOrdinal  int32       `json:"event_ordinal"`
	MessageType   string      `json:"message_type"`
	SchemaVersion int32       `json:"schema_version"`
	Payload       []byte      `json:"payload"`
}

// CreateGameSessionEvent
//
//	INSERT INTO game_session_events (batch_id, event_ordinal, message_type, schema_version, payload)
//	VALUES (
//	    $1, $2, $3,
//	    $4, $5
//	)
func (q *Queries) CreateGameSessionEvent(ctx context.Context, arg CreateGameSessionEventParams) error {
	_, err := q.db.Exec(ctx, createGameSessionEvent,
		arg.BatchID,
		arg.EventOrdinal,
		arg.MessageType,
		arg.SchemaVersion,
		arg.Payload,
	)
	return err
}

const createGameSessionEventBatch = `-- name: CreateGameSessionEventBatch :one
INSERT INTO game_session_event_batches (
    batch_id,
    session_id,
    state_version,
    ownership_epoch,
    cause,
    actor_user_id,
    action_id,
    executed_at,
    random_seed,
    allocated_ids,
    input_message_type,
    input_schema_version,
    input_payload,
    event_count,
    committed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING batch_id, session_id, state_version, ownership_epoch, cause, actor_user_id,
    action_id, executed_at, random_seed, allocated_ids, input_message_type,
    input_schema_version, input_payload, event_count, committed_at
`

type CreateGameSessionEventBatchParams struct {
	BatchID            pgtype.UUID        `json:"batch_id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	StateVersion       int64              `json:"state_version"`
	OwnershipEpoch     int64              `json:"ownership_epoch"`
	Cause              string             `json:"cause"`
	ActorUserID        pgtype.UUID        `json:"actor_user_id"`
	ActionID           pgtype.Text        `json:"action_id"`
	ExecutedAt         pgtype.Timestamptz `json:"executed_at"`
	RandomSeed         []byte             `json:"random_seed"`
	AllocatedIds       []string           `json:"allocated_ids"`
	InputMessageType   string             `json:"input_message_type"`
	InputSchemaVersion int32              `json:"input_schema_version"`
	InputPayload       []byte             `json:"input_payload"`
	EventCount         int32              `json:"event_count"`
	CommittedAt        pgtype.Timestamptz `json:"committed_at"`
}

// CreateGameSessionEventBatch
//
//	INSERT INTO game_session_event_batches (
//	    batch_id,
//	    session_id,
//	    state_version,
//	    ownership_epoch,
//	    cause,
//	    actor_user_id,
//	    action_id,
//	    executed_at,
//	    random_seed,
//	    allocated_ids,
//	    input_message_type,
//	    input_schema_version,
//	    input_payload,
//	    event_count,
//	    committed_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    $12,
//	    $13,
//	    $14,
//	    $15
//	)
//	RETURNING batch_id, session_id, state_version, ownership_epoch, cause, actor_user_id,
//	    action_id, executed_at, random_seed, allocated_ids, input_message_type,
//	    input_schema_version, input_payload, event_count, committed_at
func (q *Queries) CreateGameSessionEventBatch(ctx context.Context, arg CreateGameSessionEventBatchParams) (GameSessionEventBatch, error) {
	row := q.db.QueryRow(ctx, createGameSessionEventBatch,
		arg.BatchID,
		arg.SessionID,
		arg.StateVersion,
		arg.OwnershipEpoch,
		arg.Cause,
		arg.ActorUserID,
		arg.ActionID,
		arg.ExecutedAt,
		arg.RandomSeed,
		arg.AllocatedIds,
		arg.InputMessageType,
		arg.InputSchemaVersion,
		arg.InputPayload,
		arg.EventCount,
		arg.CommittedAt,
	)
	var i GameSessionEventBatch
	err := row.Scan(
		&i.BatchID,
		&i.SessionID,
		&i.StateVersion,
		&i.OwnershipEpoch,
		&i.Cause,
		&i.ActorUserID,
		&i.ActionID,
		&i.ExecutedAt,
		&i.RandomSeed,
		&i.AllocatedIds,
		&i.InputMessageType,
		&i.InputSchemaVersion,
		&i.InputPayload,
		&i.EventCount,
		&i.CommittedAt,
	)
	return i, err
}

const createGameSessionParticipant = `-- name: CreateGameSessionParticipant :exec
INSERT INTO game_session_participants (session_id, user_id, seat_index)
VALUES ($1, $2, $3)
`

type CreateGameSessionParticipantParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    pgtype.UUID `json:"user_id"`
	SeatIndex int32       `json:"seat_index"`
}

// CreateGameSessionParticipant
//
//	INSERT INTO game_session_participants (session_id, user_id, seat_index)
//	VALUES ($1, $2, $3)
func (q *Queries) CreateGameSessionParticipant(ctx context.Context, arg CreateGameSessionParticipantParams) error {
	_, err := q.db.Exec(ctx, createGameSessionParticipant, arg.SessionID, arg.UserID, arg.SeatIndex)
	return err
}

const createGameSessionTimer = `-- name: CreateGameSessionTimer :exec
INSERT INTO game_session_timers (
    session_id, timer_id, expected_state_version, due_at, message_type, schema_version, payload
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
`

type CreateGameSessionTimerParams struct {
	SessionID            pgtype.UUID        `json:"session_id"`
	TimerID              string             `json:"timer_id"`
	ExpectedStateVersion int64              `json:"expected_state_version"`
	DueAt                pgtype.Timestamptz `json:"due_at"`
	MessageType          string             `json:"message_type"`
	SchemaVersion        int32              `json:"schema_version"`
	Payload              []byte             `json:"payload"`
}

// CreateGameSessionTimer
//
//	INSERT INTO game_session_timers (
//	    session_id, timer_id, expected_state_version, due_at, message_type, schema_version, payload
//	) VALUES (
//	    $1, $2, $3, $4,
//	    $5, $6, $7
//	)
func (q *Queries) CreateGameSessionTimer(ctx context.Context, arg CreateGameSessionTimerParams) error {
	_, err := q.db.Exec(ctx, createGameSessionTimer,
		arg.SessionID,
		arg.TimerID,
		arg.ExpectedStateVersion,
		arg.DueAt,
		arg.MessageType,
		arg.SchemaVersion,
		arg.Payload,
	)
	return err
}

const deleteGameSessionTimers = `-- name: DeleteGameSessionTimers :exec
DELETE FROM game_session_timers WHERE session_id = $1
`

type DeleteGameSessionTimersParams struct {
	SessionID pgtype.UUID `json:"session_id"`
}

// DeleteGameSessionTimers
//
//	DELETE FROM game_session_timers WHERE session_id = $1
func (q *Queries) DeleteGameSessionTimers(ctx context.Context, arg DeleteGameSessionTimersParams) error {
	_, err := q.db.Exec(ctx, deleteGameSessionTimers, arg.SessionID)
	return err
}

const getGameActionReceipt = `-- name: GetGameActionReceipt :one
SELECT session_id, actor_user_id, action_id, request_digest, result_code,
    result_digest, committed_state_version, committed_at
FROM game_action_receipts
WHERE session_id = $1
  AND actor_user_id = $2
  AND action_id = $3
`

type GetGameActionReceiptParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	ActionID    string      `json:"action_id"`
}

// GetGameActionReceipt
//
//	SELECT session_id, actor_user_id, action_id, request_digest, result_code,
//	    result_digest, committed_state_version, committed_at
//	FROM game_action_receipts
//	WHERE session_id = $1
//	  AND actor_user_id = $2
//	  AND action_id = $3
func (q *Queries) GetGameActionReceipt(ctx context.Context, arg GetGameActionReceiptParams) (GameActionReceipt, error) {
	row := q.db.QueryRow(ctx, getGameActionReceipt, arg.SessionID, arg.ActorUserID, arg.ActionID)
	var i GameActionReceipt
	err := row.Scan(
		&i.SessionID,
		&i.ActorUserID,
		&i.ActionID,
		&i.RequestDigest,
		&i.ResultCode,
		&i.ResultDigest,
		&i.CommittedStateVersion,
		&i.CommittedAt,
	)
	return i, err
}

const getGameSessionForShare = `-- name: GetGameSessionForShare :one
SELECT session_id, room_id, game_id, engine_version, protocol_version, client_version,
    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
FROM game_sessions
WHERE session_id = $1
FOR SHARE
`

type GetGameSessionForShareParams struct {
	SessionID pgtype.UUID `json:"session_id"`
}

// GetGameSessionForShare
//
//	SELECT session_id, room_id, game_id, engine_version, protocol_version, client_version,
//	    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
//	    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
//	FROM game_sessions
//	WHERE session_id = $1
//	FOR SHARE
func (q *Queries) GetGameSessionForShare(ctx context.Context, arg GetGameSessionForShareParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, getGameSessionForShare, arg.SessionID)
	var i GameSession
	err := row.Scan(
		&i.SessionID,
		&i.RoomID,
		&i.GameID,
		&i.EngineVersion,
		&i.ProtocolVersion,
		&i.ClientVersion,
		&i.StateVersion,
		&i.OwnershipEpoch,
		&i.SnapshotVersion,
		&i.StateMessageType,
		&i.StateSchemaVersion,
		&i.StatePayload,
		&i.NextDeadlineAt,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getGameSessionForUpdate = `-- name: GetGameSessionForUpdate :one
SELECT session_id, room_id, game_id, engine_version, protocol_version, client_version,
    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
FROM game_sessions
WHERE session_id = $1
FOR UPDATE
`

type GetGameSessionForUpdateParams struct {
	SessionID pgtype.UUID `json:"session_id"`
}

// GetGameSessionForUpdate
//
//	SELECT session_id, room_id, game_id, engine_version, protocol_version, client_version,
//	    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
//	    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
//	FROM game_sessions
//	WHERE session_id = $1
//	FOR UPDATE
func (q *Queries) GetGameSessionForUpdate(ctx context.Context, arg GetGameSessionForUpdateParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, getGameSessionForUpdate, arg.SessionID)
	var i GameSession
	err := row.Scan(
		&i.SessionID,
		&i.RoomID,
		&i.GameID,
		&i.EngineVersion,
		&i.ProtocolVersion,
		&i.ClientVersion,
		&i.StateVersion,
		&i.OwnershipEpoch,
		&i.SnapshotVersion,
		&i.StateMessageType,
		&i.StateSchemaVersion,
		&i.StatePayload,
		&i.NextDeadlineAt,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const listGameSessionEvents = `-- name: ListGameSessionEvents :many
SELECT batch_id, event_ordinal, message_type, schema_version, payload
FROM game_session_events
WHERE batch_id = $1
ORDER BY event_ordinal
`

type ListGameSessionEventsParams struct {
	BatchID pgtype.UUID `json:"batch_id"`
}

// ListGameSessionEvents
//
//	SELECT batch_id, event_ordinal, message_type, schema_version, payload
//	FROM game_session_events
//	WHERE batch_id = $1
//	ORDER BY event_ordinal
func (q *Queries) ListGameSessionEvents(ctx context.Context, arg ListGameSessionEventsParams) ([]GameSessionEvent, error) {
	rows, err := q.db.Query(ctx, listGameSessionEvents, arg.BatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameSessionEvent{}
	for rows.Next() {
		var i GameSessionEvent
		if err := rows.Scan(
			&i.BatchID,
			&i.EventOrdinal,
			&i.MessageType,
			&i.SchemaVersion,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameSessionParticipants = `-- name: ListGameSessionParticipants :many
SELECT session_id, user_id, seat_index
FROM game_session_participants
WHERE session_id = $1
ORDER BY seat_index, user_id
`

type ListGameSessionParticipantsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
}

// ListGameSessionParticipants
//
//	SELECT session_id, user_id, seat_index
//	FROM game_session_participants
//	WHERE session_id = $1
//	ORDER BY seat_index, user_id
func (q *Queries) ListGameSessionParticipants(ctx context.Context, arg ListGameSessionParticipantsParams) ([]GameSessionParticipant, error) {
	rows, err := q.db.Query(ctx, listGameSessionParticipants, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameSessionParticipant{}
	for rows.Next() {
		var i GameSessionParticipant
		if err := rows.Scan(&i.SessionID, &i.UserID, &i.SeatIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameSessionTimers = `-- name: ListGameSessionTimers :many
SELECT session_id, timer_id, expected_state_version, due_at, message_type, schema_version, payload
FROM game_session_timers
WHERE session_id = $1
ORDER BY timer_id
`

type ListGameSessionTimersParams struct {
	SessionID pgtype.UUID `json:"session_id"`
}

// ListGameSessionTimers
//
//	SELECT session_id, timer_id, expected_state_version, due_at, message_type, schema_version, payload
//	FROM game_session_timers
//	WHERE session_id = $1
//	ORDER BY timer_id
func (q *Queries) ListGameSessionTimers(ctx context.Context, arg ListGameSessionTimersParams) ([]GameSessionTimer, error) {
	rows, err := q.db.Query(ctx, listGameSessionTimers, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameSessionTimer{}
	for rows.Next() {
		var i GameSessionTimer
		if err := rows.Scan(
			&i.SessionID,
			&i.TimerID,
			&i.ExpectedStateVersion,
			&i.DueAt,
			&i.MessageType,
			&i.SchemaVersion,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameSessionStateCAS = `-- name: UpdateGameSessionStateCAS :one
UPDATE game_sessions
SET state_version = $1,
    snapshot_version = $2,
    state_message_type = $3,
    state_schema_version = $4,
    state_payload = $5,
    next_deadline_at = $6,
    status = $7,
    updated_at = $8,
    ended_at = $9
WHERE session_id = $10
  AND state_version = $11
  AND ownership_epoch = $12
  AND status = 'active'
RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
`

type UpdateGameSessionStateCASParams struct {
	StateVersion           int64              `json:"state_version"`
	SnapshotVersion        int32              `json:"snapshot_version"`
	StateMessageType       string             `json:"state_message_type"`
	StateSchemaVersion     int32              `json:"state_schema_version"`
	StatePayload           []byte             `json:"state_payload"`
	NextDeadlineAt         pgtype.Timestamptz `json:"next_deadline_at"`
	Status                 string             `json:"status"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	EndedAt                pgtype.Timestamptz `json:"ended_at"`
	SessionID              pgtype.UUID        `json:"session_id"`
	ExpectedStateVersion   int64              `json:"expected_state_version"`
	ExpectedOwnershipEpoch int64              `json:"expected_ownership_epoch"`
}

// UpdateGameSessionStateCAS
//
//	UPDATE game_sessions
//	SET state_version = $1,
//	    snapshot_version = $2,
//	    state_message_type = $3,
//	    state_schema_version = $4,
//	    state_payload = $5,
//	    next_deadline_at = $6,
//	    status = $7,
//	    updated_at = $8,
//	    ended_at = $9
//	WHERE session_id = $10
//	  AND state_version = $11
//	  AND ownership_epoch = $12
//	  AND status = 'active'
//	RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
//	    state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
//	    state_payload, next_deadline_at, status, started_at, updated_at, ended_at
func (q *Queries) UpdateGameSessionStateCAS(ctx context.Context, arg UpdateGameSessionStateCASParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, updateGameSessionStateCAS,
		arg.StateVersion,
		arg.SnapshotVersion,
		arg.StateMessageType,
		arg.StateSchemaVersion,
		arg.StatePayload,
		arg.NextDeadlineAt,
		arg.Status,
		arg.UpdatedAt,
		arg.EndedAt,
		arg.SessionID,
		arg.ExpectedStateVersion,
		arg.ExpectedOwnershipEpoch,
	)
	var i GameSession
	err := row.Scan(
		&i.SessionID,
		&i.RoomID,
		&i.GameID,
		&i.EngineVersion,
		&i.ProtocolVersion,
		&i.ClientVersion,
		&i.StateVersion,
		&i.OwnershipEpoch,
		&i.SnapshotVersion,
		&i.StateMessageType,
		&i.StateSchemaVersion,
		&i.StatePayload,
		&i.NextDeadlineAt,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}
