// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeCurrentUsernameCAS = `-- name: ChangeCurrentUsernameCAS :one
UPDATE users
SET username = $1,
    current_username_key = $2,
    username_changed_at = $3,
    updated_at = $3
WHERE user_id = $4
  AND status = 'active'
  AND username = $5
  AND current_username_key = $6
  AND username_changed_at = $7
  AND updated_at = $8
  AND username_changed_at <= $9
RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
`

type ChangeCurrentUsernameCASParams struct {
	DisplayUsername           pgtype.Text        `json:"display_username"`
	UsernameKey               pgtype.Text        `json:"username_key"`
	ChangedAt                 pgtype.Timestamptz `json:"changed_at"`
	UserID                    pgtype.UUID        `json:"user_id"`
	ExpectedDisplayUsername   pgtype.Text        `json:"expected_display_username"`
	ExpectedUsernameKey       pgtype.Text        `json:"expected_username_key"`
	ExpectedUsernameChangedAt pgtype.Timestamptz `json:"expected_username_changed_at"`
	ExpectedUpdatedAt         pgtype.Timestamptz `json:"expected_updated_at"`
	CooldownCutoff            pgtype.Timestamptz `json:"cooldown_cutoff"`
}

// ChangeCurrentUsernameCAS
//
//	UPDATE users
//	SET username = $1,
//	    current_username_key = $2,
//	    username_changed_at = $3,
//	    updated_at = $3
//	WHERE user_id = $4
//	  AND status = 'active'
//	  AND username = $5
//	  AND current_username_key = $6
//	  AND username_changed_at = $7
//	  AND updated_at = $8
//	  AND username_changed_at <= $9
//	RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
func (q *Queries) ChangeCurrentUsernameCAS(ctx context.Context, arg ChangeCurrentUsernameCASParams) (User, error) {
	row := q.db.QueryRow(ctx, changeCurrentUsernameCAS,
		arg.DisplayUsername,
		arg.UsernameKey,
		arg.ChangedAt,
		arg.UserID,
		arg.ExpectedDisplayUsername,
		arg.ExpectedUsernameKey,
		arg.ExpectedUsernameChangedAt,
		arg.ExpectedUpdatedAt,
		arg.CooldownCutoff,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Username,
		&i.CurrentUsernameKey,
		&i.UsernameChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimUsername = `-- name: ClaimUsername :one
INSERT INTO username_claims (
    username_key,
    display_username,
    status,
    owner_user_id,
    reserved_until,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    'active',
    $3,
    NULL,
    $4,
    $4
)
ON CONFLICT (username_key) DO UPDATE
SET display_username = EXCLUDED.display_username,
    status = 'active',
    owner_user_id = EXCLUDED.owner_user_id,
    reserved_until = NULL,
    updated_at = EXCLUDED.updated_at
WHERE username_claims.status = 'reserved'
  AND username_claims.reserved_until <= $4
RETURNING username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
`

type ClaimUsernameParams struct {
	UsernameKey     string             `json:"username_key"`
	DisplayUsername string             `json:"display_username"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	ClaimedAt       pgtype.Timestamptz `json:"claimed_at"`
}

// ClaimUsername
//
//	INSERT INTO username_claims (
//	    username_key,
//	    display_username,
//	    status,
//	    owner_user_id,
//	    reserved_until,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    $1,
//	    $2,
//	    'active',
//	    $3,
//	    NULL,
//	    $4,
//	    $4
//	)
//	ON CONFLICT (username_key) DO UPDATE
//	SET display_username = EXCLUDED.display_username,
//	    status = 'active',
//	    owner_user_id = EXCLUDED.owner_user_id,
//	    reserved_until = NULL,
//	    updated_at = EXCLUDED.updated_at
//	WHERE username_claims.status = 'reserved'
//	  AND username_claims.reserved_until <= $4
//	RETURNING username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
func (q *Queries) ClaimUsername(ctx context.Context, arg ClaimUsernameParams) (UsernameClaim, error) {
	row := q.db.QueryRow(ctx, claimUsername,
		arg.UsernameKey,
		arg.DisplayUsername,
		arg.OwnerUserID,
		arg.ClaimedAt,
	)
	var i UsernameClaim
	err := row.Scan(
		&i.UsernameKey,
		&i.DisplayUsername,
		&i.Status,
		&i.OwnerUserID,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeOnboardingUserCAS = `-- name: CompleteOnboardingUserCAS :one
UPDATE users
SET status = 'active',
    username = $1,
    current_username_key = $2,
    username_changed_at = $3,
    updated_at = $3
WHERE user_id = $4
  AND status = 'onboarding'
  AND username IS NULL
  AND current_username_key IS NULL
  AND username_changed_at IS NULL
  AND updated_at = $5
  AND created_at = $6
  AND created_at <= $3
  AND $3 >= $5
  AND created_at > $3 - INTERVAL '86400 seconds'
RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
`

type CompleteOnboardingUserCASParams struct {
	DisplayUsername   pgtype.Text        `json:"display_username"`
	UsernameKey       pgtype.Text        `json:"username_key"`
	ChangedAt         pgtype.Timestamptz `json:"changed_at"`
	UserID            pgtype.UUID        `json:"user_id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
	ExpectedCreatedAt pgtype.Timestamptz `json:"expected_created_at"`
}

// CompleteOnboardingUserCAS
//
//	UPDATE users
//	SET status = 'active',
//	    username = $1,
//	    current_username_key = $2,
//	    username_changed_at = $3,
//	    updated_at = $3
//	WHERE user_id = $4
//	  AND status = 'onboarding'
//	  AND username IS NULL
//	  AND current_username_key IS NULL
//	  AND username_changed_at IS NULL
//	  AND updated_at = $5
//	  AND created_at = $6
//	  AND created_at <= $3
//	  AND $3 >= $5
//	  AND created_at > $3 - INTERVAL '86400 seconds'
//	RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
func (q *Queries) CompleteOnboardingUserCAS(ctx context.Context, arg CompleteOnboardingUserCASParams) (User, error) {
	row := q.db.QueryRow(ctx, completeOnboardingUserCAS,
		arg.DisplayUsername,
		arg.UsernameKey,
		arg.ChangedAt,
		arg.UserID,
		arg.ExpectedUpdatedAt,
		arg.ExpectedCreatedAt,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Username,
		&i.CurrentUsernameKey,
		&i.UsernameChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeUserRecoveryCredentialCAS = `-- name: ConsumeUserRecoveryCredentialCAS :one
UPDATE user_recovery_credentials
SET status = 'consumed',
    consumed_at = $1
WHERE recovery_credential_id = $2
  AND user_id = $3
  AND version = $4
  AND status = 'active'
RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
          created_at, consumed_at, revoked_at, revoke_reason
`

type ConsumeUserRecoveryCredentialCASParams struct {
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
	RecoveryCredentialID pgtype.UUID        `json:"recovery_credential_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	ExpectedVersion      int64              `json:"expected_version"`
}

// ConsumeUserRecoveryCredentialCAS
//
//	UPDATE user_recovery_credentials
//	SET status = 'consumed',
//	    consumed_at = $1
//	WHERE recovery_credential_id = $2
//	  AND user_id = $3
//	  AND version = $4
//	  AND status = 'active'
//	RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
//	          created_at, consumed_at, revoked_at, revoke_reason
func (q *Queries) ConsumeUserRecoveryCredentialCAS(ctx context.Context, arg ConsumeUserRecoveryCredentialCASParams) (UserRecoveryCredential, error) {
	row := q.db.QueryRow(ctx, consumeUserRecoveryCredentialCAS,
		arg.ConsumedAt,
		arg.RecoveryCredentialID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i UserRecoveryCredential
	err := row.Scan(
		&i.RecoveryCredentialID,
		&i.UserID,
		&i.Selector,
		&i.SecretHash,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const createDeviceCredential = `-- name: CreateDeviceCredential :one
INSERT INTO device_credentials (
    credential_id,
    user_id,
    secret_hash,
    secret_key_version,
    csrf_hash,
    generation,
    label,
    created_at,
    last_seen_at,
    rotated_at,
    idle_expires_at,
    absolute_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    1,
    $6,
    $7,
    $7,
    $7,
    $8,
    $9
)
RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
          previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
          created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
          revoked_at, revoke_reason
`

type CreateDeviceCredentialParams struct {
	CredentialID      pgtype.UUID        `json:"credential_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	SecretHash        []byte             `json:"secret_hash"`
	SecretKeyVersion  int32              `json:"secret_key_version"`
	CsrfHash          []byte             `json:"csrf_hash"`
	Label             string             `json:"label"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

// CreateDeviceCredential
//
//	INSERT INTO device_credentials (
//	    credential_id,
//	    user_id,
//	    secret_hash,
//	    secret_key_version,
//	    csrf_hash,
//	    generation,
//	    label,
//	    created_at,
//	    last_seen_at,
//	    rotated_at,
//	    idle_expires_at,
//	    absolute_expires_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    1,
//	    $6,
//	    $7,
//	    $7,
//	    $7,
//	    $8,
//	    $9
//	)
//	RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
//	          previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
//	          created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
//	          revoked_at, revoke_reason
func (q *Queries) CreateDeviceCredential(ctx context.Context, arg CreateDeviceCredentialParams) (DeviceCredential, error) {
	row := q.db.QueryRow(ctx, createDeviceCredential,
		arg.CredentialID,
		arg.UserID,
		arg.SecretHash,
		arg.SecretKeyVersion,
		arg.CsrfHash,
		arg.Label,
		arg.CreatedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i DeviceCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.PreviousSecretHash,
		&i.PreviousSecretKeyVersion,
		&i.PreviousValidUntil,
		&i.CsrfHash,
		&i.Generation,
		&i.Label,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RotatedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id,
    status,
    created_at,
    updated_at
) VALUES (
    $1,
    'onboarding',
    $2,
    $2
)
RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
`

type CreateUserParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// CreateUser
//
//	INSERT INTO users (
//	    user_id,
//	    status,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    $1,
//	    'onboarding',
//	    $2,
//	    $2
//	)
//	RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UserID, arg.CreatedAt)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Username,
		&i.CurrentUsernameKey,
		&i.UsernameChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserRecoveryCredential = `-- name: CreateUserRecoveryCredential :one
INSERT INTO user_recovery_credentials (
    recovery_credential_id,
    user_id,
    selector,
    secret_hash,
    version,
    status,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'active',
    $6
)
RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
          created_at, consumed_at, revoked_at, revoke_reason
`

type CreateUserRecoveryCredentialParams struct {
	RecoveryCredentialID pgtype.UUID        `json:"recovery_credential_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Selector             string             `json:"selector"`
	SecretHash           string             `json:"secret_hash"`
	Version              int64              `json:"version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

// CreateUserRecoveryCredential
//
//	INSERT INTO user_recovery_credentials (
//	    recovery_credential_id,
//	    user_id,
//	    selector,
//	    secret_hash,
//	    version,
//	    status,
//	    created_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    'active',
//	    $6
//	)
//	RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
//	          created_at, consumed_at, revoked_at, revoke_reason
func (q *Queries) CreateUserRecoveryCredential(ctx context.Context, arg CreateUserRecoveryCredentialParams) (UserRecoveryCredential, error) {
	row := q.db.QueryRow(ctx, createUserRecoveryCredential,
		arg.RecoveryCredentialID,
		arg.UserID,
		arg.Selector,
		arg.SecretHash,
		arg.Version,
		arg.CreatedAt,
	)
	var i UserRecoveryCredential
	err := row.Scan(
		&i.RecoveryCredentialID,
		&i.UserID,
		&i.Selector,
		&i.SecretHash,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getActiveUserRecoveryCredentialForUpdate = `-- name: GetActiveUserRecoveryCredentialForUpdate :one
SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
       created_at, consumed_at, revoked_at, revoke_reason
FROM user_recovery_credentials
WHERE user_id = $1
  AND status = 'active'
FOR UPDATE
`

type GetActiveUserRecoveryCredentialForUpdateParams struct {
	UserID pgtype.UUID `json:"user_id"`
}

// GetActiveUserRecoveryCredentialForUpdate
//
//	SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
//	       created_at, consumed_at, revoked_at, revoke_reason
//	FROM user_recovery_credentials
//	WHERE user_id = $1
//	  AND status = 'active'
//	FOR UPDATE
func (q *Queries) GetActiveUserRecoveryCredentialForUpdate(ctx context.Context, arg GetActiveUserRecoveryCredentialForUpdateParams) (UserRecoveryCredential, error) {
	row := q.db.QueryRow(ctx, getActiveUserRecoveryCredentialForUpdate, arg.UserID)
	var i UserRecoveryCredential
	err := row.Scan(
		&i.RecoveryCredentialID,
		&i.UserID,
		&i.Selector,
		&i.SecretHash,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getDeviceCredentialForUpdate = `-- name: GetDeviceCredentialForUpdate :one
SELECT credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
       previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
       created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
       revoked_at, revoke_reason
FROM device_credentials
WHERE credential_id = $1
FOR UPDATE
`

type GetDeviceCredentialForUpdateParams struct {
	CredentialID pgtype.UUID `json:"credential_id"`
}

// GetDeviceCredentialForUpdate
//
//	SELECT credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
//	       previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
//	       created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
//	       revoked_at, revoke_reason
//	FROM device_credentials
//	WHERE credential_id = $1
//	FOR UPDATE
func (q *Queries) GetDeviceCredentialForUpdate(ctx context.Context, arg GetDeviceCredentialForUpdateParams) (DeviceCredential, error) {
	row := q.db.QueryRow(ctx, getDeviceCredentialForUpdate, arg.CredentialID)
	var i DeviceCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.PreviousSecretHash,
		&i.PreviousSecretKeyVersion,
		&i.PreviousValidUntil,
		&i.CsrfHash,
		&i.Generation,
		&i.Label,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RotatedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getDeviceIdentityForUpdate = `-- name: GetDeviceIdentityForUpdate :one
WITH selected_device AS MATERIALIZED (
    SELECT selected.user_id
    FROM device_credentials AS selected
    WHERE selected.credential_id = $1
),
locked_user AS MATERIALIZED (
    SELECT u.user_id, u.status, u.username, u.current_username_key,
           u.username_changed_at, u.created_at, u.updated_at
    FROM users AS u
    JOIN selected_device AS selected ON selected.user_id = u.user_id
    FOR UPDATE OF u
),
locked_device AS MATERIALIZED (
    SELECT d.credential_id, d.user_id, d.secret_hash, d.secret_key_version,
           d.previous_secret_hash, d.previous_secret_key_version, d.previous_valid_until,
           d.csrf_hash, d.generation, d.label, d.created_at, d.last_seen_at, d.rotated_at,
           d.idle_expires_at, d.absolute_expires_at, d.revoked_at, d.revoke_reason
    FROM device_credentials AS d
    JOIN locked_user AS locked ON locked.user_id = d.user_id
    WHERE d.credential_id = $1
    FOR UPDATE OF d
)
SELECT u.user_id AS user_id,
       u.status AS user_status,
       u.username AS user_username,
       u.current_username_key AS user_current_username_key,
       u.username_changed_at AS user_username_changed_at,
       u.created_at AS user_created_at,
       u.updated_at AS user_updated_at,
       d.credential_id,
       d.secret_hash,
       d.secret_key_version,
       d.previous_secret_hash,
       d.previous_secret_key_version,
       d.previous_valid_until,
       d.csrf_hash,
       d.generation,
       d.label,
       d.created_at AS device_created_at,
       d.last_seen_at,
       d.rotated_at,
       d.idle_expires_at,
       d.absolute_expires_at,
       d.revoked_at,
       d.revoke_reason
FROM locked_user AS u
JOIN locked_device AS d ON d.user_id = u.user_id
`

type GetDeviceIdentityForUpdateParams struct {
	TargetCredentialID pgtype.UUID `json:"target_credential_id"`
}

type GetDeviceIdentityForUpdateRow struct {
	UserID                   pgtype.UUID        `json:"user_id"`
	UserStatus               string             `json:"user_status"`
	UserUsername             pgtype.Text        `json:"user_username"`
	UserCurrentUsernameKey   pgtype.Text        `json:"user_current_username_key"`
	UserUsernameChangedAt    pgtype.Timestamptz `json:"user_username_changed_at"`
	UserCreatedAt            pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt            pgtype.Timestamptz `json:"user_updated_at"`
	CredentialID             pgtype.UUID        `json:"credential_id"`
	SecretHash               []byte             `json:"secret_hash"`
	SecretKeyVersion         int32              `json:"secret_key_version"`
	PreviousSecretHash       []byte             `json:"previous_secret_hash"`
	PreviousSecretKeyVersion pgtype.Int4        `json:"previous_secret_key_version"`
	PreviousValidUntil       pgtype.Timestamptz `json:"previous_valid_until"`
	CsrfHash                 []byte             `json:"csrf_hash"`
	Generation               int64              `json:"generation"`
	Label                    string             `json:"label"`
	DeviceCreatedAt          pgtype.Timestamptz `json:"device_created_at"`
	LastSeenAt               pgtype.Timestamptz `json:"last_seen_at"`
	RotatedAt                pgtype.Timestamptz `json:"rotated_at"`
	IdleExpiresAt            pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt        pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt                pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason             pgtype.Text        `json:"revoke_reason"`
}

// GetDeviceIdentityForUpdate
//
//	WITH selected_device AS MATERIALIZED (
//	    SELECT selected.user_id
//	    FROM device_credentials AS selected
//	    WHERE selected.credential_id = $1
//	),
//	locked_user AS MATERIALIZED (
//	    SELECT u.user_id, u.status, u.username, u.current_username_key,
//	           u.username_changed_at, u.created_at, u.updated_at
//	    FROM users AS u
//	    JOIN selected_device AS selected ON selected.user_id = u.user_id
//	    FOR UPDATE OF u
//	),
//	locked_device AS MATERIALIZED (
//	    SELECT d.credential_id, d.user_id, d.secret_hash, d.secret_key_version,
//	           d.previous_secret_hash, d.previous_secret_key_version, d.previous_valid_until,
//	           d.csrf_hash, d.generation, d.label, d.created_at, d.last_seen_at, d.rotated_at,
//	           d.idle_expires_at, d.absolute_expires_at, d.revoked_at, d.revoke_reason
//	    FROM device_credentials AS d
//	    JOIN locked_user AS locked ON locked.user_id = d.user_id
//	    WHERE d.credential_id = $1
//	    FOR UPDATE OF d
//	)
//	SELECT u.user_id AS user_id,
//	       u.status AS user_status,
//	       u.username AS user_username,
//	       u.current_username_key AS user_current_username_key,
//	       u.username_changed_at AS user_username_changed_at,
//	       u.created_at AS user_created_at,
//	       u.updated_at AS user_updated_at,
//	       d.credential_id,
//	       d.secret_hash,
//	       d.secret_key_version,
//	       d.previous_secret_hash,
//	       d.previous_secret_key_version,
//	       d.previous_valid_until,
//	       d.csrf_hash,
//	       d.generation,
//	       d.label,
//	       d.created_at AS device_created_at,
//	       d.last_seen_at,
//	       d.rotated_at,
//	       d.idle_expires_at,
//	       d.absolute_expires_at,
//	       d.revoked_at,
//	       d.revoke_reason
//	FROM locked_user AS u
//	JOIN locked_device AS d ON d.user_id = u.user_id
func (q *Queries) GetDeviceIdentityForUpdate(ctx context.Context, arg GetDeviceIdentityForUpdateParams) (GetDeviceIdentityForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getDeviceIdentityForUpdate, arg.TargetCredentialID)
	var i GetDeviceIdentityForUpdateRow
	err := row.Scan(
		&i.UserID,
		&i.UserStatus,
		&i.UserUsername,
		&i.UserCurrentUsernameKey,
		&i.UserUsernameChangedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.CredentialID,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.PreviousSecretHash,
		&i.PreviousSecretKeyVersion,
		&i.PreviousValidUntil,
		&i.CsrfHash,
		&i.Generation,
		&i.Label,
		&i.DeviceCreatedAt,
		&i.LastSeenAt,
		&i.RotatedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
FROM users
WHERE user_id = $1
`

type GetUserByIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
}

// GetUserByID
//
//	SELECT user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
//	FROM users
//	WHERE user_id = $1
func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Username,
		&i.CurrentUsernameKey,
		&i.UsernameChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameKey = `-- name: GetUserByUsernameKey :one
SELECT u.user_id, u.status, u.username, u.current_username_key, u.username_changed_at, u.created_at, u.updated_at
FROM username_claims AS claim
JOIN users AS u ON u.user_id = claim.owner_user_id
WHERE claim.username_key = $1
  AND claim.status = 'active'
  AND u.current_username_key = claim.username_key
`

type GetUserByUsernameKeyParams struct {
	UsernameKey string `json:"username_key"`
}

// GetUserByUsernameKey
//
//	SELECT u.user_id, u.status, u.username, u.current_username_key, u.username_changed_at, u.created_at, u.updated_at
//	FROM username_claims AS claim
//	JOIN users AS u ON u.user_id = claim.owner_user_id
//	WHERE claim.username_key = $1
//	  AND claim.status = 'active'
//	  AND u.current_username_key = claim.username_key
func (q *Queries) GetUserByUsernameKey(ctx context.Context, arg GetUserByUsernameKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameKey, arg.UsernameKey)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Username,
		&i.CurrentUsernameKey,
		&i.UsernameChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
FROM users
WHERE user_id = $1
FOR UPDATE
`

type GetUserForUpdateParams struct {
	UserID pgtype.UUID `json:"user_id"`
}

// GetUserForUpdate
//
//	SELECT user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
//	FROM users
//	WHERE user_id = $1
//	FOR UPDATE
func (q *Queries) GetUserForUpdate(ctx context.Context, arg GetUserForUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Username,
		&i.CurrentUsernameKey,
		&i.UsernameChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRecoveryCredentialBySelector = `-- name: GetUserRecoveryCredentialBySelector :one
SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
       created_at, consumed_at, revoked_at, revoke_reason
FROM user_recovery_credentials
WHERE selector = $1
`

type GetUserRecoveryCredentialBySelectorParams struct {
	Selector string `json:"selector"`
}

// GetUserRecoveryCredentialBySelector
//
//	SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
//	       created_at, consumed_at, revoked_at, revoke_reason
//	FROM user_recovery_credentials
//	WHERE selector = $1
func (q *Queries) GetUserRecoveryCredentialBySelector(ctx context.Context, arg GetUserRecoveryCredentialBySelectorParams) (UserRecoveryCredential, error) {
	row := q.db.QueryRow(ctx, getUserRecoveryCredentialBySelector, arg.Selector)
	var i UserRecoveryCredential
	err := row.Scan(
		&i.RecoveryCredentialID,
		&i.UserID,
		&i.Selector,
		&i.SecretHash,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getUserRecoveryCredentialForUpdate = `-- name: GetUserRecoveryCredentialForUpdate :one
SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
       created_at, consumed_at, revoked_at, revoke_reason
FROM user_recovery_credentials
WHERE recovery_credential_id = $1
  AND user_id = $2
  AND version = $3
FOR UPDATE
`

type GetUserRecoveryCredentialForUpdateParams struct {
	RecoveryCredentialID pgtype.UUID `json:"recovery_credential_id"`
	UserID               pgtype.UUID `json:"user_id"`
	ExpectedVersion      int64       `json:"expected_version"`
}

// GetUserRecoveryCredentialForUpdate
//
//	SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
//	       created_at, consumed_at, revoked_at, revoke_reason
//	FROM user_recovery_credentials
//	WHERE recovery_credential_id = $1
//	  AND user_id = $2
//	  AND version = $3
//	FOR UPDATE
func (q *Queries) GetUserRecoveryCredentialForUpdate(ctx context.Context, arg GetUserRecoveryCredentialForUpdateParams) (UserRecoveryCredential, error) {
	row := q.db.QueryRow(ctx, getUserRecoveryCredentialForUpdate, arg.RecoveryCredentialID, arg.UserID, arg.ExpectedVersion)
	var i UserRecoveryCredential
	err := row.Scan(
		&i.RecoveryCredentialID,
		&i.UserID,
		&i.Selector,
		&i.SecretHash,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getUsernameClaimForUpdate = `-- name: GetUsernameClaimForUpdate :one
SELECT username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
FROM username_claims
WHERE username_key = $1
FOR UPDATE
`

type GetUsernameClaimForUpdateParams struct {
	UsernameKey string `json:"username_key"`
}

// GetUsernameClaimForUpdate
//
//	SELECT username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
//	FROM username_claims
//	WHERE username_key = $1
//	FOR UPDATE
func (q *Queries) GetUsernameClaimForUpdate(ctx context.Context, arg GetUsernameClaimForUpdateParams) (UsernameClaim, error) {
	row := q.db.QueryRow(ctx, getUsernameClaimForUpdate, arg.UsernameKey)
	var i UsernameClaim
	err := row.Scan(
		&i.UsernameKey,
		&i.DisplayUsername,
		&i.Status,
		&i.OwnerUserID,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserDeviceCredentials = `-- name: ListUserDeviceCredentials :many
SELECT credential_id, user_id, generation, label, created_at, last_seen_at, rotated_at,
       idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
FROM device_credentials
WHERE user_id = $1
  AND ($2::boolean OR revoked_at IS NULL)
  AND (created_at, credential_id) > (
      $3::timestamptz,
      $4::uuid
  )
ORDER BY created_at, credential_id
LIMIT $5
`

type ListUserDeviceCredentialsParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	IncludeRevoked    bool               `json:"include_revoked"`
	AfterCreatedAt    pgtype.Timestamptz `json:"after_created_at"`
	AfterCredentialID pgtype.UUID        `json:"after_credential_id"`
	PageSize          int32              `json:"page_size"`
}

type ListUserDeviceCredentialsRow struct {
	CredentialID      pgtype.UUID        `json:"credential_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Generation        int64              `json:"generation"`
	Label             string             `json:"label"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	RotatedAt         pgtype.Timestamptz `json:"rotated_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason      pgtype.Text        `json:"revoke_reason"`
}

// ListUserDeviceCredentials
//
//	SELECT credential_id, user_id, generation, label, created_at, last_seen_at, rotated_at,
//	       idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
//	FROM device_credentials
//	WHERE user_id = $1
//	  AND ($2::boolean OR revoked_at IS NULL)
//	  AND (created_at, credential_id) > (
//	      $3::timestamptz,
//	      $4::uuid
//	  )
//	ORDER BY created_at, credential_id
//	LIMIT $5
func (q *Queries) ListUserDeviceCredentials(ctx context.Context, arg ListUserDeviceCredentialsParams) ([]ListUserDeviceCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listUserDeviceCredentials,
		arg.UserID,
		arg.IncludeRevoked,
		arg.AfterCreatedAt,
		arg.AfterCredentialID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDeviceCredentialsRow{}
	for rows.Next() {
		var i ListUserDeviceCredentialsRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.Generation,
			&i.Label,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RotatedAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveUsernameClaimCAS = `-- name: ReserveUsernameClaimCAS :one
UPDATE username_claims
SET status = 'reserved',
    reserved_until = $1,
    updated_at = $2
WHERE username_key = $3
  AND owner_user_id = $4
  AND status = 'active'
RETURNING username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
`

type ReserveUsernameClaimCASParams struct {
	ReservedUntil pgtype.Timestamptz `json:"reserved_until"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
	UsernameKey   string             `json:"username_key"`
	OwnerUserID   pgtype.UUID        `json:"owner_user_id"`
}

// ReserveUsernameClaimCAS
//
//	UPDATE username_claims
//	SET status = 'reserved',
//	    reserved_until = $1,
//	    updated_at = $2
//	WHERE username_key = $3
//	  AND owner_user_id = $4
//	  AND status = 'active'
//	RETURNING username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
func (q *Queries) ReserveUsernameClaimCAS(ctx context.Context, arg ReserveUsernameClaimCASParams) (UsernameClaim, error) {
	row := q.db.QueryRow(ctx, reserveUsernameClaimCAS,
		arg.ReservedUntil,
		arg.ChangedAt,
		arg.UsernameKey,
		arg.OwnerUserID,
	)
	var i UsernameClaim
	err := row.Scan(
		&i.UsernameKey,
		&i.DisplayUsername,
		&i.Status,
		&i.OwnerUserID,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeDeviceCredentialCAS = `-- name: RevokeDeviceCredentialCAS :one
UPDATE device_credentials
SET revoked_at = $1,
    revoke_reason = $2,
    generation = generation + 1
WHERE credential_id = $3
  AND user_id = $4
  AND generation = $5
  AND revoked_at IS NULL
RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
          previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
          created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
          revoked_at, revoke_reason
`

type RevokeDeviceCredentialCASParams struct {
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason       pgtype.Text        `json:"revoke_reason"`
	CredentialID       pgtype.UUID        `json:"credential_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	ExpectedGeneration int64              `json:"expected_generation"`
}

// RevokeDeviceCredentialCAS
//
//	UPDATE device_credentials
//	SET revoked_at = $1,
//	    revoke_reason = $2,
//	    generation = generation + 1
//	WHERE credential_id = $3
//	  AND user_id = $4
//	  AND generation = $5
//	  AND revoked_at IS NULL
//	RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
//	          previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
//	          created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
//	          revoked_at, revoke_reason
func (q *Queries) RevokeDeviceCredentialCAS(ctx context.Context, arg RevokeDeviceCredentialCASParams) (DeviceCredential, error) {
	row := q.db.QueryRow(ctx, revokeDeviceCredentialCAS,
		arg.RevokedAt,
		arg.RevokeReason,
		arg.CredentialID,
		arg.UserID,
		arg.ExpectedGeneration,
	)
	var i DeviceCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.PreviousSecretHash,
		&i.PreviousSecretKeyVersion,
		&i.PreviousValidUntil,
		&i.CsrfHash,
		&i.Generation,
		&i.Label,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RotatedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const revokeOtherDeviceCredentialsForRecovery = `-- name: RevokeOtherDeviceCredentialsForRecovery :many
UPDATE device_credentials
SET revoked_at = $1,
    revoke_reason = 'recovery',
    generation = generation + 1
WHERE user_id = $2
  AND credential_id <> $3
  AND revoked_at IS NULL
RETURNING credential_id, user_id, generation, label, created_at, last_seen_at, rotated_at,
          idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
`

type RevokeOtherDeviceCredentialsForRecoveryParams struct {
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	UserID                pgtype.UUID        `json:"user_id"`
	PreservedCredentialID pgtype.UUID        `json:"preserved_credential_id"`
}

type RevokeOtherDeviceCredentialsForRecoveryRow struct {
	CredentialID      pgtype.UUID        `json:"credential_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Generation        int64              `json:"generation"`
	Label             string             `json:"label"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	RotatedAt         pgtype.Timestamptz `json:"rotated_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason      pgtype.Text        `json:"revoke_reason"`
}

// RevokeOtherDeviceCredentialsForRecovery
//
//	UPDATE device_credentials
//	SET revoked_at = $1,
//	    revoke_reason = 'recovery',
//	    generation = generation + 1
//	WHERE user_id = $2
//	  AND credential_id <> $3
//	  AND revoked_at IS NULL
//	RETURNING credential_id, user_id, generation, label, created_at, last_seen_at, rotated_at,
//	          idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
func (q *Queries) RevokeOtherDeviceCredentialsForRecovery(ctx context.Context, arg RevokeOtherDeviceCredentialsForRecoveryParams) ([]RevokeOtherDeviceCredentialsForRecoveryRow, error) {
	rows, err := q.db.Query(ctx, revokeOtherDeviceCredentialsForRecovery, arg.RevokedAt, arg.UserID, arg.PreservedCredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokeOtherDeviceCredentialsForRecoveryRow{}
	for rows.Next() {
		var i RevokeOtherDeviceCredentialsForRecoveryRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.Generation,
			&i.Label,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RotatedAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserRecoveryCredentialCAS = `-- name: RevokeUserRecoveryCredentialCAS :one
UPDATE user_recovery_credentials
SET status = 'revoked',
    revoked_at = $1,
    revoke_reason = $2
WHERE recovery_credential_id = $3
  AND user_id = $4
  AND version = $5
  AND status = 'active'
RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
          created_at, consumed_at, revoked_at, revoke_reason
`

type RevokeUserRecoveryCredentialCASParams struct {
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason         pgtype.Text        `json:"revoke_reason"`
	RecoveryCredentialID pgtype.UUID        `json:"recovery_credential_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	ExpectedVersion      int64              `json:"expected_version"`
}

// RevokeUserRecoveryCredentialCAS
//
//	UPDATE user_recovery_credentials
//	SET status = 'revoked',
//	    revoked_at = $1,
//	    revoke_reason = $2
//	WHERE recovery_credential_id = $3
//	  AND user_id = $4
//	  AND version = $5
//	  AND status = 'active'
//	RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
//	          created_at, consumed_at, revoked_at, revoke_reason
func (q *Queries) RevokeUserRecoveryCredentialCAS(ctx context.Context, arg RevokeUserRecoveryCredentialCASParams) (UserRecoveryCredential, error) {
	row := q.db.QueryRow(ctx, revokeUserRecoveryCredentialCAS,
		arg.RevokedAt,
		arg.RevokeReason,
		arg.RecoveryCredentialID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i UserRecoveryCredential
	err := row.Scan(
		&i.RecoveryCredentialID,
		&i.UserID,
		&i.Selector,
		&i.SecretHash,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const rotateDeviceCredentialCAS = `-- name: RotateDeviceCredentialCAS :one
UPDATE device_credentials
SET previous_secret_hash = secret_hash,
    previous_secret_key_version = secret_key_version,
    previous_valid_until = $1,
    secret_hash = $2,
    secret_key_version = $3,
    csrf_hash = $4,
    generation = generation + 1,
    last_seen_at = $5,
    rotated_at = $5,
    idle_expires_at = $6
WHERE credential_id = $7
  AND user_id = $8
  AND generation = $9
  AND secret_hash = $10
  AND secret_key_version = $11
  AND previous_secret_hash IS NOT DISTINCT FROM $12::bytea
  AND previous_secret_key_version IS NOT DISTINCT FROM $13::integer
  AND previous_valid_until IS NOT DISTINCT FROM $14::timestamptz
  AND csrf_hash = $15
  AND last_seen_at = $16
  AND rotated_at = $17
  AND idle_expires_at = $18
  AND absolute_expires_at = $19
  AND revoked_at IS NULL
  AND absolute_expires_at > $5
RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
          previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
          created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
          revoked_at, revoke_reason
`

type RotateDeviceCredentialCASParams struct {
	PreviousValidUntil               pgtype.Timestamptz `json:"previous_valid_until"`
	SecretHash                       []byte             `json:"secret_hash"`
	SecretKeyVersion                 int32              `json:"secret_key_version"`
	CsrfHash                         []byte             `json:"csrf_hash"`
	RotatedAt                        pgtype.Timestamptz `json:"rotated_at"`
	IdleExpiresAt                    pgtype.Timestamptz `json:"idle_expires_at"`
	CredentialID                     pgtype.UUID        `json:"credential_id"`
	UserID                           pgtype.UUID        `json:"user_id"`
	ExpectedGeneration               int64              `json:"expected_generation"`
	ExpectedSecretHash               []byte             `json:"expected_secret_hash"`
	ExpectedSecretKeyVersion         int32              `json:"expected_secret_key_version"`
	ExpectedPreviousSecretHash       []byte             `json:"expected_previous_secret_hash"`
	ExpectedPreviousSecretKeyVersion pgtype.Int4        `json:"expected_previous_secret_key_version"`
	ExpectedPreviousValidUntil       pgtype.Timestamptz `json:"expected_previous_valid_until"`
	ExpectedCsrfHash                 []byte             `json:"expected_csrf_hash"`
	ExpectedLastSeenAt               pgtype.Timestamptz `json:"expected_last_seen_at"`
	ExpectedRotatedAt                pgtype.Timestamptz `json:"expected_rotated_at"`
	ExpectedIdleExpiresAt            pgtype.Timestamptz `json:"expected_idle_expires_at"`
	ExpectedAbsoluteExpiresAt        pgtype.Timestamptz `json:"expected_absolute_expires_at"`
}

// RotateDeviceCredentialCAS
//
//	UPDATE device_credentials
//	SET previous_secret_hash = secret_hash,
//	    previous_secret_key_version = secret_key_version,
//	    previous_valid_until = $1,
//	    secret_hash = $2,
//	    secret_key_version = $3,
//	    csrf_hash = $4,
//	    generation = generation + 1,
//	    last_seen_at = $5,
//	    rotated_at = $5,
//	    idle_expires_at = $6
//	WHERE credential_id = $7
//	  AND user_id = $8
//	  AND generation = $9
//	  AND secret_hash = $10
//	  AND secret_key_version = $11
//	  AND previous_secret_hash IS NOT DISTINCT FROM $12::bytea
//	  AND previous_secret_key_version IS NOT DISTINCT FROM $13::integer
//	  AND previous_valid_until IS NOT DISTINCT FROM $14::timestamptz
//	  AND csrf_hash = $15
//	  AND last_seen_at = $16
//	  AND rotated_at = $17
//	  AND idle_expires_at = $18
//	  AND absolute_expires_at = $19
//	  AND revoked_at IS NULL
//	  AND absolute_expires_at > $5
//	RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
//	          previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
//	          created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
//	          revoked_at, revoke_reason
func (q *Queries) RotateDeviceCredentialCAS(ctx context.Context, arg RotateDeviceCredentialCASParams) (DeviceCredential, error) {
	row := q.db.QueryRow(ctx, rotateDeviceCredentialCAS,
		arg.PreviousValidUntil,
		arg.SecretHash,
		arg.SecretKeyVersion,
		arg.CsrfHash,
		arg.RotatedAt,
		arg.IdleExpiresAt,
		arg.CredentialID,
		arg.UserID,
		arg.ExpectedGeneration,
		arg.ExpectedSecretHash,
		arg.ExpectedSecretKeyVersion,
		arg.ExpectedPreviousSecretHash,
		arg.ExpectedPreviousSecretKeyVersion,
		arg.ExpectedPreviousValidUntil,
		arg.ExpectedCsrfHash,
		arg.ExpectedLastSeenAt,
		arg.ExpectedRotatedAt,
		arg.ExpectedIdleExpiresAt,
		arg.ExpectedAbsoluteExpiresAt,
	)
	var i DeviceCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.SecretHash,
		&i.SecretKeyVersion,
		&i.PreviousSecretHash,
		&i.PreviousSecretKeyVersion,
		&i.PreviousValidUntil,
		&i.CsrfHash,
		&i.Generation,
		&i.Label,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RotatedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const setCurrentUsernameCAS = `-- name: SetCurrentUsernameCAS :one
UPDATE users
SET status = $1,
    username = $2,
    current_username_key = $3,
    username_changed_at = $4,
    updated_at = $4
WHERE user_id = $5
  AND status = $6
  AND current_username_key IS NOT DISTINCT FROM $7::text
  AND updated_at = $8
RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
`

type SetCurrentUsernameCASParams struct {
	NextStatus          string             `json:"next_status"`
	DisplayUsername     pgtype.Text        `json:"display_username"`
	UsernameKey         pgtype.Text        `json:"username_key"`
	ChangedAt           pgtype.Timestamptz `json:"changed_at"`
	UserID              pgtype.UUID        `json:"user_id"`
	ExpectedStatus      string             `json:"expected_status"`
	ExpectedUsernameKey pgtype.Text        `json:"expected_username_key"`
	ExpectedUpdatedAt   pgtype.Timestamptz `json:"expected_updated_at"`
}

// SetCurrentUsernameCAS
//
//	UPDATE users
//	SET status = $1,
//	    username = $2,
//	    current_username_key = $3,
//	    username_changed_at = $4,
//	    updated_at = $4
//	WHERE user_id = $5
//	  AND status = $6
//	  AND current_username_key IS NOT DISTINCT FROM $7::text
//	  AND updated_at = $8
//	RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
func (q *Queries) SetCurrentUsernameCAS(ctx context.Context, arg SetCurrentUsernameCASParams) (User, error) {
	row := q.db.QueryRow(ctx, setCurrentUsernameCAS,
		arg.NextStatus,
		arg.DisplayUsername,
		arg.UsernameKey,
		arg.ChangedAt,
		arg.UserID,
		arg.ExpectedStatus,
		arg.ExpectedUsernameKey,
		arg.ExpectedUpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Username,
		&i.CurrentUsernameKey,
		&i.UsernameChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchDeviceCredentialCAS = `-- name: TouchDeviceCredentialCAS :one
UPDATE device_credentials
SET last_seen_at = $1,
    idle_expires_at = LEAST($2::timestamptz, absolute_expires_at)
WHERE credential_id = $3
  AND generation = $4
  AND secret_hash = $5
  AND secret_key_version = $6
  AND previous_secret_hash IS NOT DISTINCT FROM $7::bytea
  AND previous_secret_key_version IS NOT DISTINCT FROM $8::integer
  AND previous_valid_until IS NOT DISTINCT FROM $9::timestamptz
  AND csrf_hash = $10
  AND last_seen_at = $11
  AND rotated_at = $12
  AND idle_expires_at = $13
  AND absolute_expires_at = $14
  AND revoked_at IS NULL
  AND idle_expires_at > $1
  AND absolute_expires_at > $1
  AND last_seen_at < $1
RETURNING credential_id, generation, last_seen_at, idle_expires_at, absolute_expires_at
`

type TouchDeviceCredentialCASParams struct {
	SeenAt                           pgtype.Timestamptz `json:"seen_at"`
	IdleExpiresAt                    pgtype.Timestamptz `json:"idle_expires_at"`
	CredentialID                     pgtype.UUID        `json:"credential_id"`
	ExpectedGeneration               int64              `json:"expected_generation"`
	ExpectedSecretHash               []byte             `json:"expected_secret_hash"`
	ExpectedSecretKeyVersion         int32              `json:"expected_secret_key_version"`
	ExpectedPreviousSecretHash       []byte             `json:"expected_previous_secret_hash"`
	ExpectedPreviousSecretKeyVersion pgtype.Int4        `json:"expected_previous_secret_key_version"`
	ExpectedPreviousValidUntil       pgtype.Timestamptz `json:"expected_previous_valid_until"`
	ExpectedCsrfHash                 []byte             `json:"expected_csrf_hash"`
	ExpectedLastSeenAt               pgtype.Timestamptz `json:"expected_last_seen_at"`
	ExpectedRotatedAt                pgtype.Timestamptz `json:"expected_rotated_at"`
	ExpectedIdleExpiresAt            pgtype.Timestamptz `json:"expected_idle_expires_at"`
	ExpectedAbsoluteExpiresAt        pgtype.Timestamptz `json:"expected_absolute_expires_at"`
}

type TouchDeviceCredentialCASRow struct {
	CredentialID      pgtype.UUID        `json:"credential_id"`
	Generation        int64              `json:"generation"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

// TouchDeviceCredentialCAS
//
//	UPDATE device_credentials
//	SET last_seen_at = $1,
//	    idle_expires_at = LEAST($2::timestamptz, absolute_expires_at)
//	WHERE credential_id = $3
//	  AND generation = $4
//	  AND secret_hash = $5
//	  AND secret_key_version = $6
//	  AND previous_secret_hash IS NOT DISTINCT FROM $7::bytea
//	  AND previous_secret_key_version IS NOT DISTINCT FROM $8::integer
//	  AND previous_valid_until IS NOT DISTINCT FROM $9::timestamptz
//	  AND csrf_hash = $10
//	  AND last_seen_at = $11
//	  AND rotated_at = $12
//	  AND idle_expires_at = $13
//	  AND absolute_expires_at = $14
//	  AND revoked_at IS NULL
//	  AND idle_expires_at > $1
//	  AND absolute_expires_at > $1
//	  AND last_seen_at < $1
//	RETURNING credential_id, generation, last_seen_at, idle_expires_at, absolute_expires_at
func (q *Queries) TouchDeviceCredentialCAS(ctx context.Context, arg TouchDeviceCredentialCASParams) (TouchDeviceCredentialCASRow, error) {
	row := q.db.QueryRow(ctx, touchDeviceCredentialCAS,
		arg.SeenAt,
		arg.IdleExpiresAt,
		arg.CredentialID,
		arg.ExpectedGeneration,
		arg.ExpectedSecretHash,
		arg.ExpectedSecretKeyVersion,
		arg.ExpectedPreviousSecretHash,
		arg.ExpectedPreviousSecretKeyVersion,
		arg.ExpectedPreviousValidUntil,
		arg.ExpectedCsrfHash,
		arg.ExpectedLastSeenAt,
		arg.ExpectedRotatedAt,
		arg.ExpectedIdleExpiresAt,
		arg.ExpectedAbsoluteExpiresAt,
	)
	var i TouchDeviceCredentialCASRow
	err := row.Scan(
		&i.CredentialID,
		&i.Generation,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const transitionUserStatusCAS = `-- name: TransitionUserStatusCAS :one
UPDATE users
SET status = $1,
    username = CASE WHEN $1::text = 'deleted' THEN NULL ELSE username END,
    current_username_key = CASE WHEN $1::text = 'deleted' THEN NULL ELSE current_username_key END,
    updated_at = $2
WHERE user_id = $3
  AND status = $4
  AND updated_at = $5
RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
`

type TransitionUserStatusCASParams struct {
	NextStatus        string             `json:"next_status"`
	ChangedAt         pgtype.Timestamptz `json:"changed_at"`
	UserID            pgtype.UUID        `json:"user_id"`
	ExpectedStatus    string             `json:"expected_status"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

// TransitionUserStatusCAS
//
//	UPDATE users
//	SET status = $1,
//	    username = CASE WHEN $1::text = 'deleted' THEN NULL ELSE username END,
//	    current_username_key = CASE WHEN $1::text = 'deleted' THEN NULL ELSE current_username_key END,
//	    updated_at = $2
//	WHERE user_id = $3
//	  AND status = $4
//	  AND updated_at = $5
//	RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
func (q *Queries) TransitionUserStatusCAS(ctx context.Context, arg TransitionUserStatusCASParams) (User, error) {
	row := q.db.QueryRow(ctx, transitionUserStatusCAS,
		arg.NextStatus,
		arg.ChangedAt,
		arg.UserID,
		arg.ExpectedStatus,
		arg.ExpectedUpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Username,
		&i.CurrentUsernameKey,
		&i.UsernameChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
