// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package sqlcgen

import (
	"context"
)

const runExpiryCleanup = `-- name: RunExpiryCleanup :one
SELECT run_expiry_cleanup()
`

// RunExpiryCleanup
//
//	SELECT run_expiry_cleanup()
func (q *Queries) RunExpiryCleanup(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, runExpiryCleanup)
	var run_expiry_cleanup []byte
	err := row.Scan(&run_expiry_cleanup)
	return run_expiry_cleanup, err
}
