// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackOutboxConsumerOffsetCAS = `-- name: AckOutboxConsumerOffsetCAS :one
UPDATE outbox_consumers
SET last_acked_sequence = $1,
    retry_count = 0,
    next_attempt_at = NULL,
    last_error_code = NULL,
    updated_at = $2
WHERE consumer_id = $3
  AND lease_owner = $4
  AND lease_until = $5
  AND last_acked_sequence = $6
  AND retry_count = $7
  AND next_attempt_at IS NOT DISTINCT FROM $8
  AND last_error_code IS NOT DISTINCT FROM $9
  AND updated_at = $10
  AND lease_until > pg_catalog.clock_timestamp()
  AND $1::bigint > $6::bigint
  AND EXISTS (
      SELECT 1
      FROM outbox_events AS event
      WHERE event.event_sequence = $1
        AND event.event_type = ANY(outbox_consumers.subscriptions)
        AND event.available_at <= pg_catalog.clock_timestamp()
  )
  AND NOT EXISTS (
      SELECT 1
      FROM outbox_events AS skipped
      WHERE skipped.event_sequence > $6
        AND skipped.event_sequence < $1
        AND skipped.event_type = ANY(outbox_consumers.subscriptions)
  )
RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
          retry_count, next_attempt_at, last_error_code, created_at, updated_at
`

type AckOutboxConsumerOffsetCASParams struct {
	AckedSequence         int64              `json:"acked_sequence"`
	AckedAt               pgtype.Timestamptz `json:"acked_at"`
	ConsumerID            string             `json:"consumer_id"`
	ExpectedLeaseOwner    pgtype.Text        `json:"expected_lease_owner"`
	ExpectedLeaseUntil    pgtype.Timestamptz `json:"expected_lease_until"`
	ExpectedSequence      int64              `json:"expected_sequence"`
	ExpectedRetryCount    int32              `json:"expected_retry_count"`
	ExpectedNextAttemptAt pgtype.Timestamptz `json:"expected_next_attempt_at"`
	ExpectedErrorCode     pgtype.Text        `json:"expected_error_code"`
	ExpectedUpdatedAt     pgtype.Timestamptz `json:"expected_updated_at"`
}

// AckOutboxConsumerOffsetCAS
//
//	UPDATE outbox_consumers
//	SET last_acked_sequence = $1,
//	    retry_count = 0,
//	    next_attempt_at = NULL,
//	    last_error_code = NULL,
//	    updated_at = $2
//	WHERE consumer_id = $3
//	  AND lease_owner = $4
//	  AND lease_until = $5
//	  AND last_acked_sequence = $6
//	  AND retry_count = $7
//	  AND next_attempt_at IS NOT DISTINCT FROM $8
//	  AND last_error_code IS NOT DISTINCT FROM $9
//	  AND updated_at = $10
//	  AND lease_until > pg_catalog.clock_timestamp()
//	  AND $1::bigint > $6::bigint
//	  AND EXISTS (
//	      SELECT 1
//	      FROM outbox_events AS event
//	      WHERE event.event_sequence = $1
//	        AND event.event_type = ANY(outbox_consumers.subscriptions)
//	        AND event.available_at <= pg_catalog.clock_timestamp()
//	  )
//	  AND NOT EXISTS (
//	      SELECT 1
//	      FROM outbox_events AS skipped
//	      WHERE skipped.event_sequence > $6
//	        AND skipped.event_sequence < $1
//	        AND skipped.event_type = ANY(outbox_consumers.subscriptions)
//	  )
//	RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
//	          retry_count, next_attempt_at, last_error_code, created_at, updated_at
func (q *Queries) AckOutboxConsumerOffsetCAS(ctx context.Context, arg AckOutboxConsumerOffsetCASParams) (OutboxConsumer, error) {
	row := q.db.QueryRow(ctx, ackOutboxConsumerOffsetCAS,
		arg.AckedSequence,
		arg.AckedAt,
		arg.ConsumerID,
		arg.ExpectedLeaseOwner,
		arg.ExpectedLeaseUntil,
		arg.ExpectedSequence,
		arg.ExpectedRetryCount,
		arg.ExpectedNextAttemptAt,
		arg.ExpectedErrorCode,
		arg.ExpectedUpdatedAt,
	)
	var i OutboxConsumer
	err := row.Scan(
		&i.ConsumerID,
		&i.Subscriptions,
		&i.LastAckedSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const acquireOutboxConsumerLeaseCAS = `-- name: AcquireOutboxConsumerLeaseCAS :one
UPDATE outbox_consumers
SET lease_owner = $1,
    lease_until = $2,
    updated_at = $3
WHERE consumer_id = $4
  AND lease_owner IS NOT DISTINCT FROM $5
  AND lease_until IS NOT DISTINCT FROM $6
  AND last_acked_sequence = $7
  AND retry_count = $8
  AND next_attempt_at IS NOT DISTINCT FROM $9
  AND last_error_code IS NOT DISTINCT FROM $10
  AND updated_at = $11
  AND (lease_until IS NULL OR lease_until <= pg_catalog.clock_timestamp())
  AND (next_attempt_at IS NULL OR next_attempt_at <= pg_catalog.clock_timestamp())
  AND $2 > pg_catalog.clock_timestamp()
RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
          retry_count, next_attempt_at, last_error_code, created_at, updated_at
`

type AcquireOutboxConsumerLeaseCASParams struct {
	NextLeaseOwner        pgtype.Text        `json:"next_lease_owner"`
	NextLeaseUntil        pgtype.Timestamptz `json:"next_lease_until"`
	NextUpdatedAt         pgtype.Timestamptz `json:"next_updated_at"`
	ConsumerID            string             `json:"consumer_id"`
	ExpectedLeaseOwner    pgtype.Text        `json:"expected_lease_owner"`
	ExpectedLeaseUntil    pgtype.Timestamptz `json:"expected_lease_until"`
	ExpectedSequence      int64              `json:"expected_sequence"`
	ExpectedRetryCount    int32              `json:"expected_retry_count"`
	ExpectedNextAttemptAt pgtype.Timestamptz `json:"expected_next_attempt_at"`
	ExpectedErrorCode     pgtype.Text        `json:"expected_error_code"`
	ExpectedUpdatedAt     pgtype.Timestamptz `json:"expected_updated_at"`
}

// AcquireOutboxConsumerLeaseCAS
//
//	UPDATE outbox_consumers
//	SET lease_owner = $1,
//	    lease_until = $2,
//	    updated_at = $3
//	WHERE consumer_id = $4
//	  AND lease_owner IS NOT DISTINCT FROM $5
//	  AND lease_until IS NOT DISTINCT FROM $6
//	  AND last_acked_sequence = $7
//	  AND retry_count = $8
//	  AND next_attempt_at IS NOT DISTINCT FROM $9
//	  AND last_error_code IS NOT DISTINCT FROM $10
//	  AND updated_at = $11
//	  AND (lease_until IS NULL OR lease_until <= pg_catalog.clock_timestamp())
//	  AND (next_attempt_at IS NULL OR next_attempt_at <= pg_catalog.clock_timestamp())
//	  AND $2 > pg_catalog.clock_timestamp()
//	RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
//	          retry_count, next_attempt_at, last_error_code, created_at, updated_at
func (q *Queries) AcquireOutboxConsumerLeaseCAS(ctx context.Context, arg AcquireOutboxConsumerLeaseCASParams) (OutboxConsumer, error) {
	row := q.db.QueryRow(ctx, acquireOutboxConsumerLeaseCAS,
		arg.NextLeaseOwner,
		arg.NextLeaseUntil,
		arg.NextUpdatedAt,
		arg.ConsumerID,
		arg.ExpectedLeaseOwner,
		arg.ExpectedLeaseUntil,
		arg.ExpectedSequence,
		arg.ExpectedRetryCount,
		arg.ExpectedNextAttemptAt,
		arg.ExpectedErrorCode,
		arg.ExpectedUpdatedAt,
	)
	var i OutboxConsumer
	err := row.Scan(
		&i.ConsumerID,
		&i.Subscriptions,
		&i.LastAckedSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboxConsumer = `-- name: CreateOutboxConsumer :one
INSERT INTO outbox_consumers (
    consumer_id,
    subscriptions,
    last_acked_sequence,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $4
)
ON CONFLICT (consumer_id) DO NOTHING
RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
          retry_count, next_attempt_at, last_error_code, created_at, updated_at
`

type CreateOutboxConsumerParams struct {
	ConsumerID        string             `json:"consumer_id"`
	Subscriptions     []string           `json:"subscriptions"`
	LastAckedSequence int64              `json:"last_acked_sequence"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

// CreateOutboxConsumer
//
//	INSERT INTO outbox_consumers (
//	    consumer_id,
//	    subscriptions,
//	    last_acked_sequence,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $4
//	)
//	ON CONFLICT (consumer_id) DO NOTHING
//	RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
//	          retry_count, next_attempt_at, last_error_code, created_at, updated_at
func (q *Queries) CreateOutboxConsumer(ctx context.Context, arg CreateOutboxConsumerParams) (OutboxConsumer, error) {
	row := q.db.QueryRow(ctx, createOutboxConsumer,
		arg.ConsumerID,
		arg.Subscriptions,
		arg.LastAckedSequence,
		arg.CreatedAt,
	)
	var i OutboxConsumer
	err := row.Scan(
		&i.ConsumerID,
		&i.Subscriptions,
		&i.LastAckedSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
WITH serialized AS MATERIALIZED (
    -- Transaction-level serialization makes identity sequence order match commit order for offset safety.
    SELECT pg_catalog.pg_advisory_xact_lock(1196314434, 1)
)
INSERT INTO outbox_events (
    event_id,
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    created_at,
    available_at
) SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
FROM serialized
ON CONFLICT (event_id) DO NOTHING
RETURNING event_sequence, event_id, event_type, aggregate_type, aggregate_id,
          payload, created_at, available_at
`

type CreateOutboxEventParams struct {
	EventID       pgtype.UUID        `json:"event_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
}

// CreateOutboxEvent
//
//	WITH serialized AS MATERIALIZED (
//	    -- Transaction-level serialization makes identity sequence order match commit order for offset safety.
//	    SELECT pg_catalog.pg_advisory_xact_lock(1196314434, 1)
//	)
//	INSERT INTO outbox_events (
//	    event_id,
//	    event_type,
//	    aggregate_type,
//	    aggregate_id,
//	    payload,
//	    created_at,
//	    available_at
//	) SELECT
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7
//	FROM serialized
//	ON CONFLICT (event_id) DO NOTHING
//	RETURNING event_sequence, event_id, event_type, aggregate_type, aggregate_id,
//	          payload, created_at, available_at
func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.CreatedAt,
		arg.AvailableAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.EventSequence,
		&i.EventID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.CreatedAt,
		&i.AvailableAt,
	)
	return i, err
}

const getLatestAckedOutboxEventByType = `-- name: GetLatestAckedOutboxEventByType :one
SELECT event.event_sequence, event.event_id, event.event_type, event.aggregate_type,
       event.aggregate_id, event.payload, event.created_at, event.available_at
FROM outbox_events AS event
JOIN outbox_consumers AS consumer
  ON consumer.consumer_id = $1
WHERE event.event_sequence <= consumer.last_acked_sequence
  AND event.event_type = $2
  AND event.event_type = ANY(consumer.subscriptions)
ORDER BY event.event_sequence DESC
LIMIT 1
`

type GetLatestAckedOutboxEventByTypeParams struct {
	ConsumerID string `json:"consumer_id"`
	EventType  string `json:"event_type"`
}

// GetLatestAckedOutboxEventByType
//
//	SELECT event.event_sequence, event.event_id, event.event_type, event.aggregate_type,
//	       event.aggregate_id, event.payload, event.created_at, event.available_at
//	FROM outbox_events AS event
//	JOIN outbox_consumers AS consumer
//	  ON consumer.consumer_id = $1
//	WHERE event.event_sequence <= consumer.last_acked_sequence
//	  AND event.event_type = $2
//	  AND event.event_type = ANY(consumer.subscriptions)
//	ORDER BY event.event_sequence DESC
//	LIMIT 1
func (q *Queries) GetLatestAckedOutboxEventByType(ctx context.Context, arg GetLatestAckedOutboxEventByTypeParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getLatestAckedOutboxEventByType, arg.ConsumerID, arg.EventType)
	var i OutboxEvent
	err := row.Scan(
		&i.EventSequence,
		&i.EventID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.CreatedAt,
		&i.AvailableAt,
	)
	return i, err
}

const getOutboxConsumer = `-- name: GetOutboxConsumer :one
SELECT consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
       retry_count, next_attempt_at, last_error_code, created_at, updated_at
FROM outbox_consumers
WHERE consumer_id = $1
`

type GetOutboxConsumerParams struct {
	ConsumerID string `json:"consumer_id"`
}

// GetOutboxConsumer
//
//	SELECT consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
//	       retry_count, next_attempt_at, last_error_code, created_at, updated_at
//	FROM outbox_consumers
//	WHERE consumer_id = $1
func (q *Queries) GetOutboxConsumer(ctx context.Context, arg GetOutboxConsumerParams) (OutboxConsumer, error) {
	row := q.db.QueryRow(ctx, getOutboxConsumer, arg.ConsumerID)
	var i OutboxConsumer
	err := row.Scan(
		&i.ConsumerID,
		&i.Subscriptions,
		&i.LastAckedSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboxEventByID = `-- name: GetOutboxEventByID :one
SELECT event_sequence, event_id, event_type, aggregate_type, aggregate_id,
       payload, created_at, available_at
FROM outbox_events
WHERE event_id = $1
`

type GetOutboxEventByIDParams struct {
	EventID pgtype.UUID `json:"event_id"`
}

// GetOutboxEventByID
//
//	SELECT event_sequence, event_id, event_type, aggregate_type, aggregate_id,
//	       payload, created_at, available_at
//	FROM outbox_events
//	WHERE event_id = $1
func (q *Queries) GetOutboxEventByID(ctx context.Context, arg GetOutboxEventByIDParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEventByID, arg.EventID)
	var i OutboxEvent
	err := row.Scan(
		&i.EventSequence,
		&i.EventID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.CreatedAt,
		&i.AvailableAt,
	)
	return i, err
}

const listOutboxEventsForConsumer = `-- name: ListOutboxEventsForConsumer :many
WITH consumer_state AS MATERIALIZED (
    SELECT subscriptions, last_acked_sequence
    FROM outbox_consumers
    WHERE consumer_id = $1
      AND lease_owner = $2
      AND lease_until > pg_catalog.clock_timestamp()
      AND (next_attempt_at IS NULL OR next_attempt_at <= pg_catalog.clock_timestamp())
      AND $3::timestamptz <= pg_catalog.clock_timestamp()
), candidates AS MATERIALIZED (
    SELECT event.event_sequence, event.event_id, event.event_type, event.aggregate_type,
           event.aggregate_id, event.payload, event.created_at, event.available_at
    FROM outbox_events AS event
    CROSS JOIN consumer_state AS consumer
    WHERE event.event_sequence > consumer.last_acked_sequence
      AND event.event_type = ANY(consumer.subscriptions)
    ORDER BY event.event_sequence
    LIMIT $4
)
SELECT event_sequence, event_id, event_type, aggregate_type, aggregate_id,
       payload, created_at, available_at
FROM candidates AS event
WHERE event.available_at <= pg_catalog.clock_timestamp()
  AND NOT EXISTS (
      SELECT 1
      FROM candidates AS earlier
      WHERE earlier.event_sequence < event.event_sequence
        AND earlier.available_at > pg_catalog.clock_timestamp()
  )
ORDER BY event.event_sequence
`

type ListOutboxEventsForConsumerParams struct {
	ConsumerID string             `json:"consumer_id"`
	LeaseOwner pgtype.Text        `json:"lease_owner"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	BatchSize  int32              `json:"batch_size"`
}

type ListOutboxEventsForConsumerRow struct {
	EventSequence int64              `json:"event_sequence"`
	EventID       pgtype.UUID        `json:"event_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
}

// ListOutboxEventsForConsumer
//
//	WITH consumer_state AS MATERIALIZED (
//	    SELECT subscriptions, last_acked_sequence
//	    FROM outbox_consumers
//	    WHERE consumer_id = $1
//	      AND lease_owner = $2
//	      AND lease_until > pg_catalog.clock_timestamp()
//	      AND (next_attempt_at IS NULL OR next_attempt_at <= pg_catalog.clock_timestamp())
//	      AND $3::timestamptz <= pg_catalog.clock_timestamp()
//	), candidates AS MATERIALIZED (
//	    SELECT event.event_sequence, event.event_id, event.event_type, event.aggregate_type,
//	           event.aggregate_id, event.payload, event.created_at, event.available_at
//	    FROM outbox_events AS event
//	    CROSS JOIN consumer_state AS consumer
//	    WHERE event.event_sequence > consumer.last_acked_sequence
//	      AND event.event_type = ANY(consumer.subscriptions)
//	    ORDER BY event.event_sequence
//	    LIMIT $4
//	)
//	SELECT event_sequence, event_id, event_type, aggregate_type, aggregate_id,
//	       payload, created_at, available_at
//	FROM candidates AS event
//	WHERE event.available_at <= pg_catalog.clock_timestamp()
//	  AND NOT EXISTS (
//	      SELECT 1
//	      FROM candidates AS earlier
//	      WHERE earlier.event_sequence < event.event_sequence
//	        AND earlier.available_at > pg_catalog.clock_timestamp()
//	  )
//	ORDER BY event.event_sequence
func (q *Queries) ListOutboxEventsForConsumer(ctx context.Context, arg ListOutboxEventsForConsumerParams) ([]ListOutboxEventsForConsumerRow, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsForConsumer,
		arg.ConsumerID,
		arg.LeaseOwner,
		arg.ReadAt,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutboxEventsForConsumerRow{}
	for rows.Next() {
		var i ListOutboxEventsForConsumerRow
		if err := rows.Scan(
			&i.EventSequence,
			&i.EventID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
			&i.AvailableAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readCheckpointConsumerSequence = `-- name: ReadCheckpointConsumerSequence :one
SELECT read_checkpoint_consumer_sequence()
`

// ReadCheckpointConsumerSequence
//
//	SELECT read_checkpoint_consumer_sequence()
func (q *Queries) ReadCheckpointConsumerSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, readCheckpointConsumerSequence)
	var read_checkpoint_consumer_sequence int64
	err := row.Scan(&read_checkpoint_consumer_sequence)
	return read_checkpoint_consumer_sequence, err
}

const recordOutboxConsumerRetryCAS = `-- name: RecordOutboxConsumerRetryCAS :one
UPDATE outbox_consumers
SET retry_count = $1,
    next_attempt_at = $2,
    last_error_code = $3,
    updated_at = $4
WHERE consumer_id = $5
  AND lease_owner = $6
  AND lease_until = $7
  AND last_acked_sequence = $8
  AND retry_count = $9
  AND next_attempt_at IS NOT DISTINCT FROM $10
  AND last_error_code IS NOT DISTINCT FROM $11
  AND updated_at = $12
  AND lease_until > pg_catalog.clock_timestamp()
RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
          retry_count, next_attempt_at, last_error_code, created_at, updated_at
`

type RecordOutboxConsumerRetryCASParams struct {
	NextRetryCount        int32              `json:"next_retry_count"`
	NextAttemptAt         pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorCode             pgtype.Text        `json:"error_code"`
	FailedAt              pgtype.Timestamptz `json:"failed_at"`
	ConsumerID            string             `json:"consumer_id"`
	ExpectedLeaseOwner    pgtype.Text        `json:"expected_lease_owner"`
	ExpectedLeaseUntil    pgtype.Timestamptz `json:"expected_lease_until"`
	ExpectedSequence      int64              `json:"expected_sequence"`
	ExpectedRetryCount    int32              `json:"expected_retry_count"`
	ExpectedNextAttemptAt pgtype.Timestamptz `json:"expected_next_attempt_at"`
	ExpectedErrorCode     pgtype.Text        `json:"expected_error_code"`
	ExpectedUpdatedAt     pgtype.Timestamptz `json:"expected_updated_at"`
}

// RecordOutboxConsumerRetryCAS
//
//	UPDATE outbox_consumers
//	SET retry_count = $1,
//	    next_attempt_at = $2,
//	    last_error_code = $3,
//	    updated_at = $4
//	WHERE consumer_id = $5
//	  AND lease_owner = $6
//	  AND lease_until = $7
//	  AND last_acked_sequence = $8
//	  AND retry_count = $9
//	  AND next_attempt_at IS NOT DISTINCT FROM $10
//	  AND last_error_code IS NOT DISTINCT FROM $11
//	  AND updated_at = $12
//	  AND lease_until > pg_catalog.clock_timestamp()
//	RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
//	          retry_count, next_attempt_at, last_error_code, created_at, updated_at
func (q *Queries) RecordOutboxConsumerRetryCAS(ctx context.Context, arg RecordOutboxConsumerRetryCASParams) (OutboxConsumer, error) {
	row := q.db.QueryRow(ctx, recordOutboxConsumerRetryCAS,
		arg.NextRetryCount,
		arg.NextAttemptAt,
		arg.ErrorCode,
		arg.FailedAt,
		arg.ConsumerID,
		arg.ExpectedLeaseOwner,
		arg.ExpectedLeaseUntil,
		arg.ExpectedSequence,
		arg.ExpectedRetryCount,
		arg.ExpectedNextAttemptAt,
		arg.ExpectedErrorCode,
		arg.ExpectedUpdatedAt,
	)
	var i OutboxConsumer
	err := row.Scan(
		&i.ConsumerID,
		&i.Subscriptions,
		&i.LastAckedSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseOutboxConsumerLeaseCAS = `-- name: ReleaseOutboxConsumerLeaseCAS :one
UPDATE outbox_consumers
SET lease_owner = NULL,
    lease_until = NULL,
    updated_at = $1
WHERE consumer_id = $2
  AND lease_owner = $3
  AND lease_until = $4
  AND last_acked_sequence = $5
  AND retry_count = $6
  AND next_attempt_at IS NOT DISTINCT FROM $7
  AND last_error_code IS NOT DISTINCT FROM $8
  AND updated_at = $9
  AND lease_until > pg_catalog.clock_timestamp()
RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
          retry_count, next_attempt_at, last_error_code, created_at, updated_at
`

type ReleaseOutboxConsumerLeaseCASParams struct {
	ReleasedAt            pgtype.Timestamptz `json:"released_at"`
	ConsumerID            string             `json:"consumer_id"`
	ExpectedLeaseOwner    pgtype.Text        `json:"expected_lease_owner"`
	ExpectedLeaseUntil    pgtype.Timestamptz `json:"expected_lease_until"`
	ExpectedSequence      int64              `json:"expected_sequence"`
	ExpectedRetryCount    int32              `json:"expected_retry_count"`
	ExpectedNextAttemptAt pgtype.Timestamptz `json:"expected_next_attempt_at"`
	ExpectedErrorCode     pgtype.Text        `json:"expected_error_code"`
	ExpectedUpdatedAt     pgtype.Timestamptz `json:"expected_updated_at"`
}

// ReleaseOutboxConsumerLeaseCAS
//
//	UPDATE outbox_consumers
//	SET lease_owner = NULL,
//	    lease_until = NULL,
//	    updated_at = $1
//	WHERE consumer_id = $2
//	  AND lease_owner = $3
//	  AND lease_until = $4
//	  AND last_acked_sequence = $5
//	  AND retry_count = $6
//	  AND next_attempt_at IS NOT DISTINCT FROM $7
//	  AND last_error_code IS NOT DISTINCT FROM $8
//	  AND updated_at = $9
//	  AND lease_until > pg_catalog.clock_timestamp()
//	RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
//	          retry_count, next_attempt_at, last_error_code, created_at, updated_at
func (q *Queries) ReleaseOutboxConsumerLeaseCAS(ctx context.Context, arg ReleaseOutboxConsumerLeaseCASParams) (OutboxConsumer, error) {
	row := q.db.QueryRow(ctx, releaseOutboxConsumerLeaseCAS,
		arg.ReleasedAt,
		arg.ConsumerID,
		arg.ExpectedLeaseOwner,
		arg.ExpectedLeaseUntil,
		arg.ExpectedSequence,
		arg.ExpectedRetryCount,
		arg.ExpectedNextAttemptAt,
		arg.ExpectedErrorCode,
		arg.ExpectedUpdatedAt,
	)
	var i OutboxConsumer
	err := row.Scan(
		&i.ConsumerID,
		&i.Subscriptions,
		&i.LastAckedSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewOutboxConsumerLeaseCAS = `-- name: RenewOutboxConsumerLeaseCAS :one
UPDATE outbox_consumers
SET lease_until = $1,
    updated_at = $2
WHERE consumer_id = $3
  AND lease_owner = $4
  AND lease_until = $5
  AND last_acked_sequence = $6
  AND retry_count = $7
  AND next_attempt_at IS NOT DISTINCT FROM $8
  AND last_error_code IS NOT DISTINCT FROM $9
  AND updated_at = $10
  AND lease_until > pg_catalog.clock_timestamp()
  AND $1 > pg_catalog.clock_timestamp()
RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
          retry_count, next_attempt_at, last_error_code, created_at, updated_at
`

type RenewOutboxConsumerLeaseCASParams struct {
	NextLeaseUntil        pgtype.Timestamptz `json:"next_lease_until"`
	NextUpdatedAt         pgtype.Timestamptz `json:"next_updated_at"`
	ConsumerID            string             `json:"consumer_id"`
	ExpectedLeaseOwner    pgtype.Text        `json:"expected_lease_owner"`
	ExpectedLeaseUntil    pgtype.Timestamptz `json:"expected_lease_until"`
	ExpectedSequence      int64              `json:"expected_sequence"`
	ExpectedRetryCount    int32              `json:"expected_retry_count"`
	ExpectedNextAttemptAt pgtype.Timestamptz `json:"expected_next_attempt_at"`
	ExpectedErrorCode     pgtype.Text        `json:"expected_error_code"`
	ExpectedUpdatedAt     pgtype.Timestamptz `json:"expected_updated_at"`
}

// RenewOutboxConsumerLeaseCAS
//
//	UPDATE outbox_consumers
//	SET lease_until = $1,
//	    updated_at = $2
//	WHERE consumer_id = $3
//	  AND lease_owner = $4
//	  AND lease_until = $5
//	  AND last_acked_sequence = $6
//	  AND retry_count = $7
//	  AND next_attempt_at IS NOT DISTINCT FROM $8
//	  AND last_error_code IS NOT DISTINCT FROM $9
//	  AND updated_at = $10
//	  AND lease_until > pg_catalog.clock_timestamp()
//	  AND $1 > pg_catalog.clock_timestamp()
//	RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
//	          retry_count, next_attempt_at, last_error_code, created_at, updated_at
func (q *Queries) RenewOutboxConsumerLeaseCAS(ctx context.Context, arg RenewOutboxConsumerLeaseCASParams) (OutboxConsumer, error) {
	row := q.db.QueryRow(ctx, renewOutboxConsumerLeaseCAS,
		arg.NextLeaseUntil,
		arg.NextUpdatedAt,
		arg.ConsumerID,
		arg.ExpectedLeaseOwner,
		arg.ExpectedLeaseUntil,
		arg.ExpectedSequence,
		arg.ExpectedRetryCount,
		arg.ExpectedNextAttemptAt,
		arg.ExpectedErrorCode,
		arg.ExpectedUpdatedAt,
	)
	var i OutboxConsumer
	err := row.Scan(
		&i.ConsumerID,
		&i.Subscriptions,
		&i.LastAckedSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
