// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
    user_id,
    real_name_ciphertext,
    real_name_nonce,
    real_name_key_version,
    profile_version,
    real_name_updated_at,
    real_name_updated_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    1,
    $5,
    $6
)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
          profile_version, real_name_updated_at, real_name_updated_by
`

type CreateUserProfileParams struct {
	UserID             pgtype.UUID        `json:"user_id"`
	RealNameCiphertext []byte             `json:"real_name_ciphertext"`
	RealNameNonce      []byte             `json:"real_name_nonce"`
	RealNameKeyVersion int32              `json:"real_name_key_version"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy          pgtype.UUID        `json:"updated_by"`
}

// CreateUserProfile
//
//	INSERT INTO user_profiles (
//	    user_id,
//	    real_name_ciphertext,
//	    real_name_nonce,
//	    real_name_key_version,
//	    profile_version,
//	    real_name_updated_at,
//	    real_name_updated_by
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    1,
//	    $5,
//	    $6
//	)
//	ON CONFLICT (user_id) DO NOTHING
//	RETURNING user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
//	          profile_version, real_name_updated_at, real_name_updated_by
func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.RealNameCiphertext,
		arg.RealNameNonce,
		arg.RealNameKeyVersion,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.RealNameCiphertext,
		&i.RealNameNonce,
		&i.RealNameKeyVersion,
		&i.ProfileVersion,
		&i.RealNameUpdatedAt,
		&i.RealNameUpdatedBy,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
       profile_version, real_name_updated_at, real_name_updated_by
FROM user_profiles
WHERE user_id = $1
`

type GetUserProfileParams struct {
	UserID pgtype.UUID `json:"user_id"`
}

// GetUserProfile
//
//	SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
//	       profile_version, real_name_updated_at, real_name_updated_by
//	FROM user_profiles
//	WHERE user_id = $1
func (q *Queries) GetUserProfile(ctx context.Context, arg GetUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, arg.UserID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.RealNameCiphertext,
		&i.RealNameNonce,
		&i.RealNameKeyVersion,
		&i.ProfileVersion,
		&i.RealNameUpdatedAt,
		&i.RealNameUpdatedBy,
	)
	return i, err
}

const getUserProfileForUpdate = `-- name: GetUserProfileForUpdate :one
SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
       profile_version, real_name_updated_at, real_name_updated_by
FROM user_profiles
WHERE user_id = $1
FOR UPDATE
`

type GetUserProfileForUpdateParams struct {
	UserID pgtype.UUID `json:"user_id"`
}

// GetUserProfileForUpdate
//
//	SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
//	       profile_version, real_name_updated_at, real_name_updated_by
//	FROM user_profiles
//	WHERE user_id = $1
//	FOR UPDATE
func (q *Queries) GetUserProfileForUpdate(ctx context.Context, arg GetUserProfileForUpdateParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileForUpdate, arg.UserID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.RealNameCiphertext,
		&i.RealNameNonce,
		&i.RealNameKeyVersion,
		&i.ProfileVersion,
		&i.RealNameUpdatedAt,
		&i.RealNameUpdatedBy,
	)
	return i, err
}

const updateUserProfileCAS = `-- name: UpdateUserProfileCAS :one
UPDATE user_profiles
SET real_name_ciphertext = $1,
    real_name_nonce = $2,
    real_name_key_version = $3,
    profile_version = profile_version + 1,
    real_name_updated_at = $4,
    real_name_updated_by = $5
WHERE user_id = $6
  AND profile_version = $7
RETURNING user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
          profile_version, real_name_updated_at, real_name_updated_by
`

type UpdateUserProfileCASParams struct {
	RealNameCiphertext     []byte             `json:"real_name_ciphertext"`
	RealNameNonce          []byte             `json:"real_name_nonce"`
	RealNameKeyVersion     int32              `json:"real_name_key_version"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	UserID                 pgtype.UUID        `json:"user_id"`
	ExpectedProfileVersion int64              `json:"expected_profile_version"`
}

// UpdateUserProfileCAS
//
//	UPDATE user_profiles
//	SET real_name_ciphertext = $1,
//	    real_name_nonce = $2,
//	    real_name_key_version = $3,
//	    profile_version = profile_version + 1,
//	    real_name_updated_at = $4,
//	    real_name_updated_by = $5
//	WHERE user_id = $6
//	  AND profile_version = $7
//	RETURNING user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
//	          profile_version, real_name_updated_at, real_name_updated_by
func (q *Queries) UpdateUserProfileCAS(ctx context.Context, arg UpdateUserProfileCASParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfileCAS,
		arg.RealNameCiphertext,
		arg.RealNameNonce,
		arg.RealNameKeyVersion,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.UserID,
		arg.ExpectedProfileVersion,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.RealNameCiphertext,
		&i.RealNameNonce,
		&i.RealNameKeyVersion,
		&i.ProfileVersion,
		&i.RealNameUpdatedAt,
		&i.RealNameUpdatedBy,
	)
	return i, err
}
