// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	//AbortProfileExportContextCAS
	//
	//  UPDATE profile_export_contexts
	//  SET status = 'aborted',
	//      aborted_at = $1
	//  WHERE export_id = $2
	//    AND created_by_admin_id = $3
	//    AND status = 'active'
	//  RETURNING export_id, status, aborted_at
	AbortProfileExportContextCAS(ctx context.Context, arg AbortProfileExportContextCASParams) (AbortProfileExportContextCASRow, error)
	//AcceptAdminTotpStepCAS
	//
	//  UPDATE admin_accounts
	//  SET last_accepted_totp_step = $1,
	//      updated_at = $2
	//  WHERE singleton_id = 1
	//    AND admin_id = $3
	//    AND status = 'active'
	//    AND admin_version = $4
	//    AND (last_accepted_totp_step IS NULL OR last_accepted_totp_step < $1)
	//  RETURNING admin_id, admin_version, last_accepted_totp_step, updated_at
	AcceptAdminTotpStepCAS(ctx context.Context, arg AcceptAdminTotpStepCASParams) (AcceptAdminTotpStepCASRow, error)
	//AckOutboxConsumerOffsetCAS
	//
	//  UPDATE outbox_consumers
	//  SET last_acked_sequence = $1,
	//      retry_count = 0,
	//      next_attempt_at = NULL,
	//      last_error_code = NULL,
	//      updated_at = $2
	//  WHERE consumer_id = $3
	//    AND lease_owner = $4
	//    AND lease_until > $2
	//    AND last_acked_sequence = $5
	//    AND $1::bigint > $5::bigint
	//  RETURNING consumer_id, last_acked_sequence, lease_owner, lease_until, retry_count, updated_at
	AckOutboxConsumerOffsetCAS(ctx context.Context, arg AckOutboxConsumerOffsetCASParams) (AckOutboxConsumerOffsetCASRow, error)
	//AcquireKeyRotationJobLease
	//
	//  WITH candidate AS (
	//      SELECT job_id
	//      FROM key_rotation_jobs
	//      WHERE status IN ('pending', 'running')
	//        AND (lease_owner IS NULL OR lease_until <= $1)
	//      ORDER BY created_at, job_id
	//      FOR UPDATE SKIP LOCKED
	//      LIMIT 1
	//  )
	//  UPDATE key_rotation_jobs AS job
	//  SET status = 'running',
	//      started_at = COALESCE(job.started_at, $1),
	//      lease_owner = $2,
	//      lease_until = $3,
	//      updated_at = $1
	//  FROM candidate
	//  WHERE job.job_id = candidate.job_id
	//  RETURNING job.job_id, job.purpose, job.source_key_version, job.target_key_version,
	//            job.status, job.cursor_scope, job.cursor_id, job.cursor_ordinal,
	//            job.processed_count, job.conflict_count, job.lease_owner, job.lease_until,
	//            job.last_error_code, job.created_at, job.started_at, job.updated_at, job.completed_at
	AcquireKeyRotationJobLease(ctx context.Context, arg AcquireKeyRotationJobLeaseParams) (KeyRotationJob, error)
	//AcquireOutboxConsumerLeaseCAS
	//
	//  UPDATE outbox_consumers
	//  SET lease_owner = $1,
	//      lease_until = $2,
	//      updated_at = $3
	//  WHERE consumer_id = $4
	//    AND (
	//        lease_owner IS NULL
	//        OR lease_until <= $3
	//        OR lease_owner = $1
	//    )
	//    AND (next_attempt_at IS NULL OR next_attempt_at <= $3)
	//  RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//            retry_count, next_attempt_at, last_error_code, created_at, updated_at
	AcquireOutboxConsumerLeaseCAS(ctx context.Context, arg AcquireOutboxConsumerLeaseCASParams) (OutboxConsumer, error)
	//ActivatePendingAdminTotpEnrollmentCAS
	//
	//  UPDATE admin_totp_enrollments
	//  SET status = 'active',
	//      expires_at = NULL,
	//      activated_at = $1
	//  WHERE admin_id = $2
	//    AND enrollment_id = $3
	//    AND status = 'pending'
	//    AND admin_version = $4
	//    AND expires_at > $1
	//  RETURNING enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//            operation_id, created_at, expires_at, activated_at, disabled_at
	ActivatePendingAdminTotpEnrollmentCAS(ctx context.Context, arg ActivatePendingAdminTotpEnrollmentCASParams) (AdminTotpEnrollment, error)
	//AdvanceKeyRotationCursorCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET cursor_scope = $1,
	//      cursor_id = $2,
	//      cursor_ordinal = $3,
	//      processed_count = processed_count + $4,
	//      conflict_count = conflict_count + $5,
	//      updated_at = $6
	//  WHERE job_id = $7
	//    AND status = 'running'
	//    AND lease_owner = $8
	//    AND lease_until > $6
	//    AND cursor_scope = $9
	//    AND cursor_id IS NOT DISTINCT FROM $10::uuid
	//    AND cursor_ordinal IS NOT DISTINCT FROM $11::bigint
	//  RETURNING job_id, status, cursor_scope, cursor_id, cursor_ordinal, processed_count,
	//            conflict_count, lease_owner, lease_until, updated_at
	AdvanceKeyRotationCursorCAS(ctx context.Context, arg AdvanceKeyRotationCursorCASParams) (AdvanceKeyRotationCursorCASRow, error)
	//AppendAuditEvent
	//
	//  WITH result AS (
	//      SELECT pg_catalog.to_jsonb(function_row) AS payload
	//      FROM append_audit_event(
	//          $1,
	//          $2,
	//          $3,
	//          $4,
	//          $5,
	//          $6,
	//          $7
	//      ) AS function_row
	//  )
	//  SELECT (result.payload ->> 'appended_sequence')::bigint AS appended_sequence,
	//         decode(pg_catalog.substring(result.payload ->> 'appended_hash', 3), 'hex') AS appended_hash
	//  FROM result
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AppendAuditEventRow, error)
	//BootstrapAdminPasswordCAS
	//
	//  UPDATE admin_accounts
	//  SET status = 'setup_required',
	//      password_hash = $1,
	//      password_algorithm = $2,
	//      password_parameters = $3,
	//      password_version = password_version + 1,
	//      admin_version = admin_version + 1,
	//      updated_at = $4
	//  WHERE singleton_id = 1
	//    AND status = 'bootstrap_pending'
	//    AND password_hash IS NULL
	//    AND admin_version = $5
	//  RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
	BootstrapAdminPasswordCAS(ctx context.Context, arg BootstrapAdminPasswordCASParams) (BootstrapAdminPasswordCASRow, error)
	//ClaimUsername
	//
	//  INSERT INTO username_claims (
	//      username_key,
	//      display_username,
	//      status,
	//      owner_user_id,
	//      reserved_until,
	//      created_at,
	//      updated_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      'active',
	//      $3,
	//      NULL,
	//      $4,
	//      $4
	//  )
	//  ON CONFLICT (username_key) DO UPDATE
	//  SET display_username = EXCLUDED.display_username,
	//      status = 'active',
	//      owner_user_id = EXCLUDED.owner_user_id,
	//      reserved_until = NULL,
	//      updated_at = EXCLUDED.updated_at
	//  WHERE username_claims.status = 'reserved'
	//    AND username_claims.reserved_until <= $4
	//  RETURNING username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
	ClaimUsername(ctx context.Context, arg ClaimUsernameParams) (UsernameClaim, error)
	//CompleteKeyRotationJobCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET status = 'completed',
	//      lease_owner = NULL,
	//      lease_until = NULL,
	//      completed_at = $1,
	//      updated_at = $1
	//  WHERE job_id = $2
	//    AND status = 'running'
	//    AND lease_owner = $3
	//    AND lease_until > $1
	//  RETURNING job_id, status, processed_count, conflict_count, completed_at
	CompleteKeyRotationJobCAS(ctx context.Context, arg CompleteKeyRotationJobCASParams) (CompleteKeyRotationJobCASRow, error)
	//CompleteProfileExportContextCAS
	//
	//  UPDATE profile_export_contexts
	//  SET status = 'completed',
	//      completed_at = $1
	//  WHERE export_id = $2
	//    AND created_by_admin_id = $3
	//    AND status = 'active'
	//    AND expires_at > $1
	//  RETURNING export_id, status, completed_at
	CompleteProfileExportContextCAS(ctx context.Context, arg CompleteProfileExportContextCASParams) (CompleteProfileExportContextCASRow, error)
	//ConfirmSecretOperationResultCAS
	//
	//  UPDATE secret_operation_results
	//  SET status = 'confirmed',
	//      ciphertext = NULL,
	//      nonce = NULL,
	//      wrapped_data_key = NULL,
	//      confirmed_at = $1
	//  WHERE result_id = $2
	//    AND operation_scope = $3
	//    AND actor_or_challenge_id = $4
	//    AND operation_id = $5
	//    AND request_digest = $6
	//    AND result_type = $7
	//    AND status = 'available'
	//    AND secret_expires_at > $1
	//  RETURNING result_id, status, confirmed_at, tombstone_expires_at
	ConfirmSecretOperationResultCAS(ctx context.Context, arg ConfirmSecretOperationResultCASParams) (ConfirmSecretOperationResultCASRow, error)
	//ConsumeAdminAssistedRecoveryGrantCAS
	//
	//  UPDATE admin_assisted_recovery_grants
	//  SET status = 'consumed',
	//      consumed_at = $1,
	//      result_id = $2
	//  WHERE assisted_grant_id = $3
	//    AND status = 'active'
	//    AND expires_at > $1
	//    AND attempt_count < max_attempts
	//  RETURNING assisted_grant_id, user_id, status, consumed_at, result_id
	ConsumeAdminAssistedRecoveryGrantCAS(ctx context.Context, arg ConsumeAdminAssistedRecoveryGrantCASParams) (ConsumeAdminAssistedRecoveryGrantCASRow, error)
	//ConsumeAdminChallengeCAS
	//
	//  UPDATE admin_challenges
	//  SET status = 'consumed',
	//      consumed_at = $1,
	//      replay_until = $2,
	//      operation_id = $3,
	//      request_digest = $4,
	//      result_id = $5
	//  WHERE challenge_id = $6
	//    AND status = 'active'
	//    AND expires_at > $1
	//    AND attempt_count < max_attempts
	//    AND admin_version = $7
	//    AND password_version = $8
	//  RETURNING challenge_id, status, consumed_at, replay_until, operation_id, request_digest, result_id
	ConsumeAdminChallengeCAS(ctx context.Context, arg ConsumeAdminChallengeCASParams) (ConsumeAdminChallengeCASRow, error)
	//ConsumeAdminRecoveryCodeCAS
	//
	//  UPDATE admin_recovery_codes
	//  SET status = 'consumed',
	//      consumed_at = $1
	//  WHERE recovery_code_id = $2
	//    AND admin_id = $3
	//    AND set_version = $4
	//    AND status = 'active'
	//  RETURNING recovery_code_id, admin_id, set_version, status, consumed_at
	ConsumeAdminRecoveryCodeCAS(ctx context.Context, arg ConsumeAdminRecoveryCodeCASParams) (ConsumeAdminRecoveryCodeCASRow, error)
	//ConsumeAnonymousChallengeCAS
	//
	//  UPDATE anonymous_challenges
	//  SET consumed_at = $1,
	//      replay_until = $2,
	//      operation_id = $3,
	//      request_digest = $4,
	//      result_id = $5
	//  WHERE challenge_id = $6
	//    AND consumed_at IS NULL
	//    AND expires_at > $1
	//    AND attempt_count < max_attempts
	//  RETURNING challenge_id, consumed_at, replay_until, operation_id, request_digest, result_id
	ConsumeAnonymousChallengeCAS(ctx context.Context, arg ConsumeAnonymousChallengeCASParams) (ConsumeAnonymousChallengeCASRow, error)
	//ConsumeUserRecoveryAttemptCAS
	//
	//  UPDATE user_recovery_attempts
	//  SET status = 'consumed',
	//      consumed_at = $1,
	//      result_id = $2
	//  WHERE recovery_attempt_id = $3
	//    AND status = 'active'
	//    AND expires_at > $1
	//    AND attempt_count < max_attempts
	//  RETURNING recovery_attempt_id, user_id, status, consumed_at, result_id
	ConsumeUserRecoveryAttemptCAS(ctx context.Context, arg ConsumeUserRecoveryAttemptCASParams) (ConsumeUserRecoveryAttemptCASRow, error)
	//ConsumeUserRecoveryCredentialCAS
	//
	//  UPDATE user_recovery_credentials
	//  SET status = 'consumed',
	//      consumed_at = $1
	//  WHERE recovery_credential_id = $2
	//    AND user_id = $3
	//    AND version = $4
	//    AND status = 'active'
	//  RETURNING recovery_credential_id, user_id, version, status, consumed_at
	ConsumeUserRecoveryCredentialCAS(ctx context.Context, arg ConsumeUserRecoveryCredentialCASParams) (ConsumeUserRecoveryCredentialCASRow, error)
	//CountPIIKeyReferences
	//
	//  SELECT (
	//      (SELECT count(*) FROM user_profiles AS profile WHERE profile.real_name_key_version = $1)
	//      +
	//      (SELECT count(*) FROM profile_export_items AS item WHERE item.real_name_key_version = $1)
	//  )::bigint AS reference_count
	CountPIIKeyReferences(ctx context.Context, arg CountPIIKeyReferencesParams) (int64, error)
	//CountTotpKeyReferences
	//
	//  SELECT count(*)::bigint AS reference_count
	//  FROM admin_totp_enrollments
	//  WHERE key_version = $1
	//    AND status IN ('pending', 'active')
	CountTotpKeyReferences(ctx context.Context, arg CountTotpKeyReferencesParams) (int64, error)
	//CreateAdminAssistedRecoveryGrant
	//
	//  INSERT INTO admin_assisted_recovery_grants (
	//      assisted_grant_id,
	//      user_id,
	//      selector,
	//      secret_hash,
	//      purpose,
	//      status,
	//      attempt_count,
	//      max_attempts,
	//      created_by_admin_id,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      'active',
	//      0,
	//      $6,
	//      $7,
	//      $8,
	//      $9
	//  )
	//  RETURNING assisted_grant_id, user_id, selector, secret_hash, purpose, status,
	//            attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
	//            consumed_at, revoked_at, result_id
	CreateAdminAssistedRecoveryGrant(ctx context.Context, arg CreateAdminAssistedRecoveryGrantParams) (AdminAssistedRecoveryGrant, error)
	//CreateAdminChallenge
	//
	//  INSERT INTO admin_challenges (
	//      challenge_id,
	//      admin_id,
	//      selector,
	//      secret_hash,
	//      secret_key_version,
	//      purpose,
	//      audience,
	//      admin_version,
	//      password_version,
	//      origin_hash,
	//      request_flow_id,
	//      attempt_count,
	//      max_attempts,
	//      status,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      0,
	//      $12,
	//      'active',
	//      $13,
	//      $14
	//  )
	//  RETURNING challenge_id, admin_id, selector, secret_hash, secret_key_version, purpose,
	//            audience, admin_version, password_version, origin_hash, request_flow_id,
	//            attempt_count, max_attempts, status, created_at, expires_at, consumed_at,
	//            revoked_at, replay_until, operation_id, request_digest, result_id
	CreateAdminChallenge(ctx context.Context, arg CreateAdminChallengeParams) (AdminChallenge, error)
	//CreateAdminRecoveryCode
	//
	//  INSERT INTO admin_recovery_codes (
	//      recovery_code_id,
	//      admin_id,
	//      selector,
	//      secret_hash,
	//      set_version,
	//      status,
	//      created_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      'active',
	//      $6
	//  )
	//  RETURNING recovery_code_id, admin_id, selector, secret_hash, set_version, status,
	//            created_at, consumed_at, revoked_at
	CreateAdminRecoveryCode(ctx context.Context, arg CreateAdminRecoveryCodeParams) (AdminRecoveryCode, error)
	//CreateAdminSession
	//
	//  INSERT INTO admin_sessions (
	//      session_id,
	//      admin_id,
	//      selector,
	//      secret_hash,
	//      secret_key_version,
	//      csrf_hash,
	//      kind,
	//      admin_version,
	//      password_version,
	//      attempt_count,
	//      max_attempts,
	//      created_at,
	//      last_seen_at,
	//      idle_expires_at,
	//      absolute_expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      0,
	//      $10,
	//      $11,
	//      $11,
	//      $12,
	//      $13
	//  )
	//  RETURNING session_id, admin_id, selector, secret_hash, secret_key_version, csrf_hash,
	//            kind, admin_version, password_version, attempt_count, max_attempts, created_at,
	//            last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error)
	//CreateAnonymousChallenge
	//
	//  INSERT INTO anonymous_challenges (
	//      challenge_id,
	//      selector,
	//      secret_hash,
	//      secret_key_version,
	//      purpose,
	//      audience,
	//      origin_hash,
	//      request_flow_id,
	//      attempt_count,
	//      max_attempts,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      0,
	//      $9,
	//      $10,
	//      $11
	//  )
	//  RETURNING challenge_id, selector, secret_hash, secret_key_version, purpose, audience,
	//            origin_hash, request_flow_id, attempt_count, max_attempts, created_at, expires_at,
	//            consumed_at, replay_until, operation_id, request_digest, result_id
	CreateAnonymousChallenge(ctx context.Context, arg CreateAnonymousChallengeParams) (AnonymousChallenge, error)
	//CreateDeviceCredential
	//
	//  INSERT INTO device_credentials (
	//      credential_id,
	//      user_id,
	//      secret_hash,
	//      secret_key_version,
	//      csrf_hash,
	//      generation,
	//      label,
	//      created_at,
	//      last_seen_at,
	//      rotated_at,
	//      idle_expires_at,
	//      absolute_expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      1,
	//      $6,
	//      $7,
	//      $7,
	//      $7,
	//      $8,
	//      $9
	//  )
	//  RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
	//            previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
	//            created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
	//            revoked_at, revoke_reason
	CreateDeviceCredential(ctx context.Context, arg CreateDeviceCredentialParams) (DeviceCredential, error)
	//CreateKeyRotationJob
	//
	//  INSERT INTO key_rotation_jobs (
	//      job_id,
	//      purpose,
	//      source_key_version,
	//      target_key_version,
	//      status,
	//      cursor_scope,
	//      processed_count,
	//      conflict_count,
	//      created_at,
	//      updated_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      'pending',
	//      $5,
	//      0,
	//      0,
	//      $6,
	//      $6
	//  )
	//  ON CONFLICT (purpose) WHERE status IN ('pending', 'running') DO NOTHING
	//  RETURNING job_id, purpose, source_key_version, target_key_version, status, cursor_scope,
	//            cursor_id, cursor_ordinal, processed_count, conflict_count, lease_owner,
	//            lease_until, last_error_code, created_at, started_at, updated_at, completed_at
	CreateKeyRotationJob(ctx context.Context, arg CreateKeyRotationJobParams) (KeyRotationJob, error)
	//CreateOutboxEvent
	//
	//  INSERT INTO outbox_events (
	//      event_id,
	//      event_type,
	//      aggregate_type,
	//      aggregate_id,
	//      payload,
	//      created_at,
	//      available_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7
	//  )
	//  ON CONFLICT (event_id) DO NOTHING
	//  RETURNING event_sequence, event_id, event_type, aggregate_type, aggregate_id,
	//            payload, created_at, available_at
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	//CreatePendingAdminTotpEnrollment
	//
	//  INSERT INTO admin_totp_enrollments (
	//      enrollment_id,
	//      admin_id,
	//      ciphertext,
	//      nonce,
	//      key_version,
	//      status,
	//      admin_version,
	//      operation_id,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      'pending',
	//      $6,
	//      $7,
	//      $8,
	//      $9
	//  )
	//  ON CONFLICT (admin_id) WHERE status = 'pending' DO NOTHING
	//  RETURNING enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//            operation_id, created_at, expires_at, activated_at, disabled_at
	CreatePendingAdminTotpEnrollment(ctx context.Context, arg CreatePendingAdminTotpEnrollmentParams) (AdminTotpEnrollment, error)
	//CreateProfileExportContext
	//
	//  INSERT INTO profile_export_contexts (
	//      export_id,
	//      created_by_admin_id,
	//      filter_digest,
	//      requested_fields,
	//      schema_version,
	//      item_count,
	//      status,
	//      reason,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      'active',
	//      $7,
	//      $8,
	//      $9
	//  )
	//  RETURNING export_id, created_by_admin_id, filter_digest, requested_fields, schema_version,
	//            item_count, status, reason, created_at, expires_at, completed_at, aborted_at, expired_at
	CreateProfileExportContext(ctx context.Context, arg CreateProfileExportContextParams) (ProfileExportContext, error)
	//CreateProfileExportItem
	//
	//  INSERT INTO profile_export_items (
	//      export_id,
	//      ordinal,
	//      user_id,
	//      username,
	//      profile_version,
	//      real_name_ciphertext,
	//      real_name_nonce,
	//      real_name_key_version
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8
	//  )
	//  RETURNING export_id, ordinal, user_id, username, profile_version,
	//            real_name_ciphertext, real_name_nonce, real_name_key_version
	CreateProfileExportItem(ctx context.Context, arg CreateProfileExportItemParams) (ProfileExportItem, error)
	//CreateSecretOperationResult
	//
	//  INSERT INTO secret_operation_results (
	//      result_id,
	//      operation_scope,
	//      actor_or_challenge_id,
	//      operation_id,
	//      request_digest,
	//      result_type,
	//      result_version,
	//      ciphertext,
	//      nonce,
	//      wrapped_data_key,
	//      key_version,
	//      status,
	//      secret_expires_at,
	//      completed_at,
	//      tombstone_expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      'available',
	//      $12,
	//      $13,
	//      $14
	//  )
	//  ON CONFLICT (operation_scope, actor_or_challenge_id, operation_id) DO NOTHING
	//  RETURNING result_id, operation_scope, actor_or_challenge_id, operation_id, request_digest,
	//            result_type, result_version, ciphertext, nonce, wrapped_data_key, key_version,
	//            status, secret_expires_at, confirmed_at, completed_at, tombstone_expires_at
	CreateSecretOperationResult(ctx context.Context, arg CreateSecretOperationResultParams) (SecretOperationResult, error)
	//CreateUser
	//
	//  INSERT INTO users (
	//      user_id,
	//      status,
	//      created_at,
	//      updated_at
	//  ) VALUES (
	//      $1,
	//      'onboarding',
	//      $2,
	//      $2
	//  )
	//  RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//CreateUserProfile
	//
	//  INSERT INTO user_profiles (
	//      user_id,
	//      real_name_ciphertext,
	//      real_name_nonce,
	//      real_name_key_version,
	//      profile_version,
	//      real_name_updated_at,
	//      real_name_updated_by
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      1,
	//      $5,
	//      $6
	//  )
	//  ON CONFLICT (user_id) DO NOTHING
	//  RETURNING user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//            profile_version, real_name_updated_at, real_name_updated_by
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	//CreateUserRecoveryAttempt
	//
	//  INSERT INTO user_recovery_attempts (
	//      recovery_attempt_id,
	//      grant_selector,
	//      grant_secret_hash,
	//      grant_key_version,
	//      user_id,
	//      recovery_credential_id,
	//      recovery_credential_version,
	//      assisted_grant_id,
	//      challenge_id,
	//      origin_hash,
	//      purpose,
	//      request_digest,
	//      attempt_count,
	//      max_attempts,
	//      status,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      $12,
	//      0,
	//      $13,
	//      'active',
	//      $14,
	//      $15
	//  )
	//  RETURNING recovery_attempt_id, grant_selector, grant_secret_hash, grant_key_version,
	//            user_id, recovery_credential_id, recovery_credential_version, assisted_grant_id,
	//            challenge_id, origin_hash, purpose, request_digest, attempt_count, max_attempts,
	//            status, created_at, expires_at, consumed_at, revoked_at, result_id
	CreateUserRecoveryAttempt(ctx context.Context, arg CreateUserRecoveryAttemptParams) (UserRecoveryAttempt, error)
	//CreateUserRecoveryCredential
	//
	//  INSERT INTO user_recovery_credentials (
	//      recovery_credential_id,
	//      user_id,
	//      selector,
	//      secret_hash,
	//      version,
	//      status,
	//      created_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      'active',
	//      $6
	//  )
	//  RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
	//            created_at, consumed_at, revoked_at, revoke_reason
	CreateUserRecoveryCredential(ctx context.Context, arg CreateUserRecoveryCredentialParams) (UserRecoveryCredential, error)
	//DisableActiveAdminTotpEnrollmentCAS
	//
	//  UPDATE admin_totp_enrollments
	//  SET status = 'disabled',
	//      ciphertext = NULL,
	//      nonce = NULL,
	//      disabled_at = $1
	//  WHERE admin_id = $2
	//    AND enrollment_id = $3
	//    AND status = 'active'
	//    AND admin_version = $4
	//  RETURNING enrollment_id, admin_id, status, disabled_at
	DisableActiveAdminTotpEnrollmentCAS(ctx context.Context, arg DisableActiveAdminTotpEnrollmentCASParams) (DisableActiveAdminTotpEnrollmentCASRow, error)
	//ExpireProfileExportContextCAS
	//
	//  UPDATE profile_export_contexts
	//  SET status = 'expired',
	//      expired_at = $1
	//  WHERE export_id = $2
	//    AND status = 'active'
	//    AND expires_at <= $1
	//  RETURNING export_id, status, expired_at
	ExpireProfileExportContextCAS(ctx context.Context, arg ExpireProfileExportContextCASParams) (ExpireProfileExportContextCASRow, error)
	//ExpireSecretOperationResultCAS
	//
	//  UPDATE secret_operation_results
	//  SET status = 'expired',
	//      ciphertext = NULL,
	//      nonce = NULL,
	//      wrapped_data_key = NULL
	//  WHERE result_id = $1
	//    AND status = 'available'
	//    AND secret_expires_at <= $2
	//  RETURNING result_id, status, tombstone_expires_at
	ExpireSecretOperationResultCAS(ctx context.Context, arg ExpireSecretOperationResultCASParams) (ExpireSecretOperationResultCASRow, error)
	//FailKeyRotationJobCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET status = 'failed',
	//      lease_owner = NULL,
	//      lease_until = NULL,
	//      last_error_code = $1,
	//      updated_at = $2
	//  WHERE job_id = $3
	//    AND status = 'running'
	//    AND lease_owner = $4
	//  RETURNING job_id, status, processed_count, conflict_count, last_error_code, updated_at
	FailKeyRotationJobCAS(ctx context.Context, arg FailKeyRotationJobCASParams) (FailKeyRotationJobCASRow, error)
	//GetAdminAssistedRecoveryGrantForUpdate
	//
	//  SELECT assisted_grant_id, user_id, selector, secret_hash, purpose, status,
	//         attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
	//         consumed_at, revoked_at, result_id
	//  FROM admin_assisted_recovery_grants
	//  WHERE selector = $1
	//  FOR UPDATE
	GetAdminAssistedRecoveryGrantForUpdate(ctx context.Context, arg GetAdminAssistedRecoveryGrantForUpdateParams) (AdminAssistedRecoveryGrant, error)
	//GetAdminChallengeForUpdate
	//
	//  SELECT challenge_id, admin_id, selector, secret_hash, secret_key_version, purpose,
	//         audience, admin_version, password_version, origin_hash, request_flow_id,
	//         attempt_count, max_attempts, status, created_at, expires_at, consumed_at,
	//         revoked_at, replay_until, operation_id, request_digest, result_id
	//  FROM admin_challenges
	//  WHERE selector = $1
	//  FOR UPDATE
	GetAdminChallengeForUpdate(ctx context.Context, arg GetAdminChallengeForUpdateParams) (AdminChallenge, error)
	//GetAdminSessionForUpdate
	//
	//  SELECT session_id, admin_id, selector, secret_hash, secret_key_version, csrf_hash,
	//         kind, admin_version, password_version, attempt_count, max_attempts, created_at,
	//         last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
	//  FROM admin_sessions
	//  WHERE selector = $1
	//  FOR UPDATE
	GetAdminSessionForUpdate(ctx context.Context, arg GetAdminSessionForUpdateParams) (AdminSession, error)
	//GetAnonymousChallengeForUpdate
	//
	//  SELECT challenge_id, selector, secret_hash, secret_key_version, purpose, audience,
	//         origin_hash, request_flow_id, attempt_count, max_attempts, created_at, expires_at,
	//         consumed_at, replay_until, operation_id, request_digest, result_id
	//  FROM anonymous_challenges
	//  WHERE selector = $1
	//  FOR UPDATE
	GetAnonymousChallengeForUpdate(ctx context.Context, arg GetAnonymousChallengeForUpdateParams) (AnonymousChallenge, error)
	//GetDeviceCredentialForUpdate
	//
	//  SELECT credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
	//         previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
	//         created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
	//         revoked_at, revoke_reason
	//  FROM device_credentials
	//  WHERE credential_id = $1
	//  FOR UPDATE
	GetDeviceCredentialForUpdate(ctx context.Context, arg GetDeviceCredentialForUpdateParams) (DeviceCredential, error)
	//GetKeyRotationJob
	//
	//  SELECT job_id, purpose, source_key_version, target_key_version, status, cursor_scope,
	//         cursor_id, cursor_ordinal, processed_count, conflict_count, lease_owner,
	//         lease_until, last_error_code, created_at, started_at, updated_at, completed_at
	//  FROM key_rotation_jobs
	//  WHERE job_id = $1
	GetKeyRotationJob(ctx context.Context, arg GetKeyRotationJobParams) (KeyRotationJob, error)
	//GetOutboxConsumer
	//
	//  SELECT consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//         retry_count, next_attempt_at, last_error_code, created_at, updated_at
	//  FROM outbox_consumers
	//  WHERE consumer_id = $1
	GetOutboxConsumer(ctx context.Context, arg GetOutboxConsumerParams) (OutboxConsumer, error)
	//GetPendingAdminTotpEnrollmentForUpdate
	//
	//  SELECT enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//         operation_id, created_at, expires_at, activated_at, disabled_at
	//  FROM admin_totp_enrollments
	//  WHERE admin_id = $1
	//    AND status = 'pending'
	//  FOR UPDATE
	GetPendingAdminTotpEnrollmentForUpdate(ctx context.Context, arg GetPendingAdminTotpEnrollmentForUpdateParams) (AdminTotpEnrollment, error)
	//GetProfileExportContextForUpdate
	//
	//  SELECT export_id, created_by_admin_id, filter_digest, requested_fields, schema_version,
	//         item_count, status, reason, created_at, expires_at, completed_at, aborted_at, expired_at
	//  FROM profile_export_contexts
	//  WHERE export_id = $1
	//  FOR UPDATE
	GetProfileExportContextForUpdate(ctx context.Context, arg GetProfileExportContextForUpdateParams) (ProfileExportContext, error)
	//GetSecretOperationResultByOperation
	//
	//  SELECT result_id, operation_scope, actor_or_challenge_id, operation_id, request_digest,
	//         result_type, result_version, ciphertext, nonce, wrapped_data_key, key_version,
	//         status, secret_expires_at, confirmed_at, completed_at, tombstone_expires_at
	//  FROM secret_operation_results
	//  WHERE operation_scope = $1
	//    AND actor_or_challenge_id = $2
	//    AND operation_id = $3
	GetSecretOperationResultByOperation(ctx context.Context, arg GetSecretOperationResultByOperationParams) (SecretOperationResult, error)
	//GetSingletonAdminForUpdate
	//
	//  SELECT singleton_id, admin_id, username, status, password_hash, password_algorithm,
	//         password_parameters, password_version, admin_version, last_accepted_totp_step,
	//         created_at, updated_at
	//  FROM admin_accounts
	//  WHERE singleton_id = 1
	//  FOR UPDATE
	GetSingletonAdminForUpdate(ctx context.Context) (AdminAccount, error)
	//GetUserByID
	//
	//  SELECT user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	//  FROM users
	//  WHERE user_id = $1
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	//GetUserForUpdate
	//
	//  SELECT user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	//  FROM users
	//  WHERE user_id = $1
	//  FOR UPDATE
	GetUserForUpdate(ctx context.Context, arg GetUserForUpdateParams) (User, error)
	//GetUserProfile
	//
	//  SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//         profile_version, real_name_updated_at, real_name_updated_by
	//  FROM user_profiles
	//  WHERE user_id = $1
	GetUserProfile(ctx context.Context, arg GetUserProfileParams) (UserProfile, error)
	//GetUserRecoveryAttemptForUpdate
	//
	//  SELECT recovery_attempt_id, grant_selector, grant_secret_hash, grant_key_version,
	//         user_id, recovery_credential_id, recovery_credential_version, assisted_grant_id,
	//         challenge_id, origin_hash, purpose, request_digest, attempt_count, max_attempts,
	//         status, created_at, expires_at, consumed_at, revoked_at, result_id
	//  FROM user_recovery_attempts
	//  WHERE grant_selector = $1
	//  FOR UPDATE
	GetUserRecoveryAttemptForUpdate(ctx context.Context, arg GetUserRecoveryAttemptForUpdateParams) (UserRecoveryAttempt, error)
	//GetUserRecoveryCredentialForUpdate
	//
	//  SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
	//         created_at, consumed_at, revoked_at, revoke_reason
	//  FROM user_recovery_credentials
	//  WHERE selector = $1
	//  FOR UPDATE
	GetUserRecoveryCredentialForUpdate(ctx context.Context, arg GetUserRecoveryCredentialForUpdateParams) (UserRecoveryCredential, error)
	//ListAdminTotpEnrollmentsForKeyRotation
	//
	//  SELECT enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//         operation_id, created_at, expires_at, activated_at, disabled_at
	//  FROM admin_totp_enrollments
	//  WHERE key_version = $1
	//    AND status IN ('pending', 'active')
	//    AND ($2::uuid IS NULL OR enrollment_id > $2::uuid)
	//  ORDER BY enrollment_id
	//  LIMIT $3
	ListAdminTotpEnrollmentsForKeyRotation(ctx context.Context, arg ListAdminTotpEnrollmentsForKeyRotationParams) ([]AdminTotpEnrollment, error)
	//ListAuditEvents
	//
	//  SELECT chain_id, sequence, event_id, previous_hash, canonical_event, event_hash,
	//         signature, signing_key_version, created_at
	//  FROM audit_events_redacted
	//  WHERE chain_id = $1
	//    AND sequence > $2
	//  ORDER BY sequence
	//  LIMIT $3
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEventsRedacted, error)
	//ListOutboxEventsForConsumer
	//
	//  SELECT event.event_sequence, event.event_id, event.event_type, event.aggregate_type,
	//         event.aggregate_id, event.payload, event.created_at, event.available_at
	//  FROM outbox_events AS event
	//  JOIN outbox_consumers AS consumer
	//    ON consumer.consumer_id = $1
	//  WHERE consumer.lease_owner = $2
	//    AND consumer.lease_until > $3
	//    AND event.event_sequence > consumer.last_acked_sequence
	//    AND event.available_at <= $3
	//    AND event.event_type = ANY(consumer.subscriptions)
	//  ORDER BY event.event_sequence
	//  LIMIT $4
	ListOutboxEventsForConsumer(ctx context.Context, arg ListOutboxEventsForConsumerParams) ([]OutboxEvent, error)
	//ListProfileExportItems
	//
	//  SELECT export_id, ordinal, user_id, username, profile_version,
	//         real_name_ciphertext, real_name_nonce, real_name_key_version
	//  FROM profile_export_items
	//  WHERE export_id = $1
	//    AND ordinal > $2
	//  ORDER BY ordinal
	//  LIMIT $3
	ListProfileExportItems(ctx context.Context, arg ListProfileExportItemsParams) ([]ProfileExportItem, error)
	//ListProfileExportItemsForKeyRotation
	//
	//  SELECT export_id, ordinal, user_id, profile_version, real_name_ciphertext,
	//         real_name_nonce, real_name_key_version
	//  FROM profile_export_items
	//  WHERE real_name_key_version = $1
	//    AND (
	//        $2::uuid IS NULL
	//        OR (export_id, ordinal) > (
	//            $2::uuid,
	//            $3::bigint
	//        )
	//    )
	//  ORDER BY export_id, ordinal
	//  LIMIT $4
	ListProfileExportItemsForKeyRotation(ctx context.Context, arg ListProfileExportItemsForKeyRotationParams) ([]ListProfileExportItemsForKeyRotationRow, error)
	//ListUserDeviceCredentials
	//
	//  SELECT credential_id, user_id, generation, label, created_at, last_seen_at, rotated_at,
	//         idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
	//  FROM device_credentials
	//  WHERE user_id = $1
	//    AND (created_at, credential_id) > ($2, $3)
	//  ORDER BY created_at, credential_id
	//  LIMIT $4
	ListUserDeviceCredentials(ctx context.Context, arg ListUserDeviceCredentialsParams) ([]ListUserDeviceCredentialsRow, error)
	//ListUserProfilesForKeyRotation
	//
	//  SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//         profile_version, real_name_updated_at, real_name_updated_by
	//  FROM user_profiles
	//  WHERE real_name_key_version = $1
	//    AND ($2::uuid IS NULL OR user_id > $2::uuid)
	//  ORDER BY user_id
	//  LIMIT $3
	ListUserProfilesForKeyRotation(ctx context.Context, arg ListUserProfilesForKeyRotationParams) ([]UserProfile, error)
	//ReadAuditHead
	//
	//  WITH result AS (
	//      SELECT pg_catalog.to_jsonb(function_row) AS payload
	//      FROM read_audit_head($1) AS function_row
	//  )
	//  SELECT (result.payload ->> 'sequence')::bigint AS sequence,
	//         decode(pg_catalog.substring(result.payload ->> 'head_hash', 3), 'hex') AS head_hash
	//  FROM result
	ReadAuditHead(ctx context.Context, arg ReadAuditHeadParams) (ReadAuditHeadRow, error)
	//RecordAdminAssistedRecoveryFailureCAS
	//
	//  UPDATE admin_assisted_recovery_grants
	//  SET attempt_count = attempt_count + 1
	//  WHERE assisted_grant_id = $1
	//    AND status = 'active'
	//    AND expires_at > $2
	//    AND attempt_count < max_attempts
	//  RETURNING assisted_grant_id, attempt_count, max_attempts, status, expires_at
	RecordAdminAssistedRecoveryFailureCAS(ctx context.Context, arg RecordAdminAssistedRecoveryFailureCASParams) (RecordAdminAssistedRecoveryFailureCASRow, error)
	//RecordAdminChallengeFailureCAS
	//
	//  UPDATE admin_challenges
	//  SET attempt_count = attempt_count + 1
	//  WHERE challenge_id = $1
	//    AND status = 'active'
	//    AND expires_at > $2
	//    AND attempt_count < max_attempts
	//  RETURNING challenge_id, attempt_count, max_attempts, status, expires_at
	RecordAdminChallengeFailureCAS(ctx context.Context, arg RecordAdminChallengeFailureCASParams) (RecordAdminChallengeFailureCASRow, error)
	//RecordAnonymousChallengeFailureCAS
	//
	//  UPDATE anonymous_challenges
	//  SET attempt_count = attempt_count + 1
	//  WHERE challenge_id = $1
	//    AND consumed_at IS NULL
	//    AND expires_at > $2
	//    AND attempt_count < max_attempts
	//  RETURNING challenge_id, attempt_count, max_attempts, expires_at
	RecordAnonymousChallengeFailureCAS(ctx context.Context, arg RecordAnonymousChallengeFailureCASParams) (RecordAnonymousChallengeFailureCASRow, error)
	//RecordOutboxConsumerRetryCAS
	//
	//  UPDATE outbox_consumers
	//  SET retry_count = retry_count + 1,
	//      next_attempt_at = $1,
	//      last_error_code = $2,
	//      updated_at = $3
	//  WHERE consumer_id = $4
	//    AND lease_owner = $5
	//    AND lease_until > $3
	//  RETURNING consumer_id, last_acked_sequence, lease_owner, lease_until, retry_count,
	//            next_attempt_at, last_error_code, updated_at
	RecordOutboxConsumerRetryCAS(ctx context.Context, arg RecordOutboxConsumerRetryCASParams) (RecordOutboxConsumerRetryCASRow, error)
	//RecordUserRecoveryAttemptFailureCAS
	//
	//  UPDATE user_recovery_attempts
	//  SET attempt_count = attempt_count + 1
	//  WHERE recovery_attempt_id = $1
	//    AND status = 'active'
	//    AND expires_at > $2
	//    AND attempt_count < max_attempts
	//  RETURNING recovery_attempt_id, attempt_count, max_attempts, status, expires_at
	RecordUserRecoveryAttemptFailureCAS(ctx context.Context, arg RecordUserRecoveryAttemptFailureCASParams) (RecordUserRecoveryAttemptFailureCASRow, error)
	//ReleaseOutboxConsumerLeaseCAS
	//
	//  UPDATE outbox_consumers
	//  SET lease_owner = NULL,
	//      lease_until = NULL,
	//      updated_at = $1
	//  WHERE consumer_id = $2
	//    AND lease_owner = $3
	//  RETURNING consumer_id, last_acked_sequence, lease_owner, lease_until, updated_at
	ReleaseOutboxConsumerLeaseCAS(ctx context.Context, arg ReleaseOutboxConsumerLeaseCASParams) (ReleaseOutboxConsumerLeaseCASRow, error)
	//RenewKeyRotationJobLeaseCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET lease_until = $1,
	//      updated_at = $2
	//  WHERE job_id = $3
	//    AND status = 'running'
	//    AND lease_owner = $4
	//    AND lease_until > $2
	//  RETURNING job_id, status, cursor_scope, cursor_id, cursor_ordinal, lease_owner,
	//            lease_until, updated_at
	RenewKeyRotationJobLeaseCAS(ctx context.Context, arg RenewKeyRotationJobLeaseCASParams) (RenewKeyRotationJobLeaseCASRow, error)
	//RenewOutboxConsumerLeaseCAS
	//
	//  UPDATE outbox_consumers
	//  SET lease_until = $1,
	//      updated_at = $2
	//  WHERE consumer_id = $3
	//    AND lease_owner = $4
	//    AND lease_until > $2
	//  RETURNING consumer_id, last_acked_sequence, lease_owner, lease_until, updated_at
	RenewOutboxConsumerLeaseCAS(ctx context.Context, arg RenewOutboxConsumerLeaseCASParams) (RenewOutboxConsumerLeaseCASRow, error)
	//ReserveUsernameClaimCAS
	//
	//  UPDATE username_claims
	//  SET status = 'reserved',
	//      reserved_until = $1,
	//      updated_at = $2
	//  WHERE username_key = $3
	//    AND owner_user_id = $4
	//    AND status = 'active'
	//  RETURNING username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
	ReserveUsernameClaimCAS(ctx context.Context, arg ReserveUsernameClaimCASParams) (UsernameClaim, error)
	//ResetAdminAccount
	//
	//  WITH result AS (
	//      SELECT pg_catalog.to_jsonb(function_row) AS payload
	//      FROM reset_admin_account(
	//          $1,
	//          $2,
	//          $3,
	//          $4,
	//          $5,
	//          $6,
	//          $7,
	//          $8,
	//          $9,
	//          $10,
	//          $11
	//      ) AS function_row
	//  )
	//  SELECT (result.payload ->> 'appended_sequence')::bigint AS appended_sequence,
	//         decode(pg_catalog.substring(result.payload ->> 'appended_hash', 3), 'hex') AS appended_hash
	//  FROM result
	ResetAdminAccount(ctx context.Context, arg ResetAdminAccountParams) (ResetAdminAccountRow, error)
	//RevokeAdminChallenges
	//
	//  UPDATE admin_challenges
	//  SET status = 'revoked',
	//      revoked_at = $1
	//  WHERE admin_id = $2
	//    AND status = 'active'
	RevokeAdminChallenges(ctx context.Context, arg RevokeAdminChallengesParams) (int64, error)
	//RevokeAdminRecoveryCodeSet
	//
	//  UPDATE admin_recovery_codes
	//  SET status = 'revoked',
	//      revoked_at = $1
	//  WHERE admin_id = $2
	//    AND set_version = $3
	//    AND status = 'active'
	RevokeAdminRecoveryCodeSet(ctx context.Context, arg RevokeAdminRecoveryCodeSetParams) (int64, error)
	//RevokeAdminSessionCAS
	//
	//  UPDATE admin_sessions
	//  SET revoked_at = $1,
	//      revoke_reason = $2
	//  WHERE session_id = $3
	//    AND revoked_at IS NULL
	//  RETURNING session_id, revoked_at, revoke_reason
	RevokeAdminSessionCAS(ctx context.Context, arg RevokeAdminSessionCASParams) (RevokeAdminSessionCASRow, error)
	//RevokeAllAdminSessions
	//
	//  UPDATE admin_sessions
	//  SET revoked_at = $1,
	//      revoke_reason = $2
	//  WHERE admin_id = $3
	//    AND revoked_at IS NULL
	RevokeAllAdminSessions(ctx context.Context, arg RevokeAllAdminSessionsParams) (int64, error)
	//RevokeDeviceCredentialCAS
	//
	//  UPDATE device_credentials
	//  SET revoked_at = $1,
	//      revoke_reason = $2,
	//      generation = generation + 1
	//  WHERE credential_id = $3
	//    AND user_id = $4
	//    AND generation = $5
	//    AND revoked_at IS NULL
	//  RETURNING credential_id, generation, revoked_at, revoke_reason
	RevokeDeviceCredentialCAS(ctx context.Context, arg RevokeDeviceCredentialCASParams) (RevokeDeviceCredentialCASRow, error)
	//RevokeUserRecoveryAttemptCAS
	//
	//  UPDATE user_recovery_attempts
	//  SET status = 'revoked',
	//      revoked_at = $1
	//  WHERE recovery_attempt_id = $2
	//    AND status = 'active'
	//  RETURNING recovery_attempt_id, user_id, status, revoked_at
	RevokeUserRecoveryAttemptCAS(ctx context.Context, arg RevokeUserRecoveryAttemptCASParams) (RevokeUserRecoveryAttemptCASRow, error)
	//RevokeUserRecoveryCredentialCAS
	//
	//  UPDATE user_recovery_credentials
	//  SET status = 'revoked',
	//      revoked_at = $1,
	//      revoke_reason = $2
	//  WHERE recovery_credential_id = $3
	//    AND user_id = $4
	//    AND version = $5
	//    AND status = 'active'
	//  RETURNING recovery_credential_id, user_id, version, status, revoked_at, revoke_reason
	RevokeUserRecoveryCredentialCAS(ctx context.Context, arg RevokeUserRecoveryCredentialCASParams) (RevokeUserRecoveryCredentialCASRow, error)
	//RotateAdminTotpEnrollmentCiphertextCAS
	//
	//  UPDATE admin_totp_enrollments
	//  SET ciphertext = $1,
	//      nonce = $2,
	//      key_version = $3
	//  WHERE enrollment_id = $4
	//    AND admin_version = $5
	//    AND key_version = $6
	//    AND status IN ('pending', 'active')
	//  RETURNING enrollment_id, admin_id, key_version, status, admin_version
	RotateAdminTotpEnrollmentCiphertextCAS(ctx context.Context, arg RotateAdminTotpEnrollmentCiphertextCASParams) (RotateAdminTotpEnrollmentCiphertextCASRow, error)
	//RotateDeviceCredentialCAS
	//
	//  UPDATE device_credentials
	//  SET previous_secret_hash = secret_hash,
	//      previous_secret_key_version = secret_key_version,
	//      previous_valid_until = $1,
	//      secret_hash = $2,
	//      secret_key_version = $3,
	//      csrf_hash = $4,
	//      generation = generation + 1,
	//      last_seen_at = $5,
	//      rotated_at = $5,
	//      idle_expires_at = $6
	//  WHERE credential_id = $7
	//    AND user_id = $8
	//    AND generation = $9
	//    AND revoked_at IS NULL
	//    AND absolute_expires_at > $5
	//  RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
	//            previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
	//            created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
	//            revoked_at, revoke_reason
	RotateDeviceCredentialCAS(ctx context.Context, arg RotateDeviceCredentialCASParams) (DeviceCredential, error)
	//RotateProfileExportItemCiphertextCAS
	//
	//  UPDATE profile_export_items
	//  SET real_name_ciphertext = $1,
	//      real_name_nonce = $2,
	//      real_name_key_version = $3
	//  WHERE export_id = $4
	//    AND ordinal = $5
	//    AND real_name_key_version = $6
	//  RETURNING export_id, ordinal, user_id, real_name_key_version
	RotateProfileExportItemCiphertextCAS(ctx context.Context, arg RotateProfileExportItemCiphertextCASParams) (RotateProfileExportItemCiphertextCASRow, error)
	//RotateUserProfileCiphertextCAS
	//
	//  UPDATE user_profiles
	//  SET real_name_ciphertext = $1,
	//      real_name_nonce = $2,
	//      real_name_key_version = $3
	//  WHERE user_id = $4
	//    AND profile_version = $5
	//    AND real_name_key_version = $6
	//  RETURNING user_id, real_name_key_version, profile_version
	RotateUserProfileCiphertextCAS(ctx context.Context, arg RotateUserProfileCiphertextCASParams) (RotateUserProfileCiphertextCASRow, error)
	//SetCurrentUsernameCAS
	//
	//  UPDATE users
	//  SET status = $1,
	//      username = $2,
	//      current_username_key = $3,
	//      username_changed_at = $4,
	//      updated_at = $4
	//  WHERE user_id = $5
	//    AND status = $6
	//    AND current_username_key IS NOT DISTINCT FROM $7::text
	//  RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	SetCurrentUsernameCAS(ctx context.Context, arg SetCurrentUsernameCASParams) (User, error)
	//TouchAdminSessionCAS
	//
	//  UPDATE admin_sessions
	//  SET last_seen_at = $1,
	//      idle_expires_at = LEAST($2::timestamptz, absolute_expires_at)
	//  WHERE session_id = $3
	//    AND admin_version = $4
	//    AND password_version = $5
	//    AND revoked_at IS NULL
	//    AND idle_expires_at > $1
	//    AND absolute_expires_at > $1
	//  RETURNING session_id, kind, last_seen_at, idle_expires_at, absolute_expires_at
	TouchAdminSessionCAS(ctx context.Context, arg TouchAdminSessionCASParams) (TouchAdminSessionCASRow, error)
	//TouchDeviceCredentialCAS
	//
	//  UPDATE device_credentials
	//  SET last_seen_at = $1,
	//      idle_expires_at = LEAST($2::timestamptz, absolute_expires_at)
	//  WHERE credential_id = $3
	//    AND generation = $4
	//    AND revoked_at IS NULL
	//    AND idle_expires_at > $1
	//    AND absolute_expires_at > $1
	//  RETURNING credential_id, generation, last_seen_at, idle_expires_at, absolute_expires_at
	TouchDeviceCredentialCAS(ctx context.Context, arg TouchDeviceCredentialCASParams) (TouchDeviceCredentialCASRow, error)
	//TransitionAdminStatusCAS
	//
	//  UPDATE admin_accounts
	//  SET status = $1,
	//      admin_version = admin_version + 1,
	//      updated_at = $2
	//  WHERE singleton_id = 1
	//    AND admin_id = $3
	//    AND status = $4
	//    AND admin_version = $5
	//  RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
	TransitionAdminStatusCAS(ctx context.Context, arg TransitionAdminStatusCASParams) (TransitionAdminStatusCASRow, error)
	//TransitionUserStatusCAS
	//
	//  UPDATE users
	//  SET status = $1,
	//      username = CASE WHEN $1::text = 'deleted' THEN NULL ELSE username END,
	//      current_username_key = CASE WHEN $1::text = 'deleted' THEN NULL ELSE current_username_key END,
	//      updated_at = $2
	//  WHERE user_id = $3
	//    AND status = $4
	//  RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	TransitionUserStatusCAS(ctx context.Context, arg TransitionUserStatusCASParams) (User, error)
	//UpdateAdminPasswordCAS
	//
	//  UPDATE admin_accounts
	//  SET password_hash = $1,
	//      password_algorithm = $2,
	//      password_parameters = $3,
	//      password_version = password_version + 1,
	//      admin_version = admin_version + 1,
	//      updated_at = $4
	//  WHERE singleton_id = 1
	//    AND admin_id = $5
	//    AND status = $6
	//    AND password_version = $7
	//    AND admin_version = $8
	//  RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
	UpdateAdminPasswordCAS(ctx context.Context, arg UpdateAdminPasswordCASParams) (UpdateAdminPasswordCASRow, error)
	//UpdateUserProfileCAS
	//
	//  UPDATE user_profiles
	//  SET real_name_ciphertext = $1,
	//      real_name_nonce = $2,
	//      real_name_key_version = $3,
	//      profile_version = profile_version + 1,
	//      real_name_updated_at = $4,
	//      real_name_updated_by = $5
	//  WHERE user_id = $6
	//    AND profile_version = $7
	//  RETURNING user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//            profile_version, real_name_updated_at, real_name_updated_by
	UpdateUserProfileCAS(ctx context.Context, arg UpdateUserProfileCASParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
