// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	//AbortProfileExportContextCAS
	//
	//  UPDATE profile_export_contexts
	//  SET status = 'aborted',
	//      aborted_at = $1
	//  WHERE export_id = $2
	//    AND created_by_admin_id = $3
	//    AND status = 'active'
	//  RETURNING export_id, status, aborted_at
	AbortProfileExportContextCAS(ctx context.Context, arg AbortProfileExportContextCASParams) (AbortProfileExportContextCASRow, error)
	//AcceptAdminTotpStepCAS
	//
	//  UPDATE admin_accounts
	//  SET last_accepted_totp_step = $1,
	//      updated_at = $2
	//  WHERE singleton_id = 1
	//    AND admin_id = $3
	//    AND status IN ('setup_required', 'recovery_pending', 'active')
	//    AND admin_version = $4
	//    AND (last_accepted_totp_step IS NULL OR last_accepted_totp_step < $1)
	//  RETURNING admin_id, admin_version, last_accepted_totp_step, updated_at
	AcceptAdminTotpStepCAS(ctx context.Context, arg AcceptAdminTotpStepCASParams) (AcceptAdminTotpStepCASRow, error)
	//AckOutboxConsumerOffsetCAS
	//
	//  UPDATE outbox_consumers
	//  SET last_acked_sequence = $1,
	//      retry_count = 0,
	//      next_attempt_at = NULL,
	//      last_error_code = NULL,
	//      updated_at = $2
	//  WHERE consumer_id = $3
	//    AND lease_owner = $4
	//    AND lease_until = $5
	//    AND last_acked_sequence = $6
	//    AND retry_count = $7
	//    AND next_attempt_at IS NOT DISTINCT FROM $8
	//    AND last_error_code IS NOT DISTINCT FROM $9
	//    AND updated_at = $10
	//    AND lease_until > pg_catalog.clock_timestamp()
	//    AND $1::bigint > $6::bigint
	//    AND EXISTS (
	//        SELECT 1
	//        FROM outbox_events AS event
	//        WHERE event.event_sequence = $1
	//          AND event.event_type = ANY(outbox_consumers.subscriptions)
	//          AND event.available_at <= pg_catalog.clock_timestamp()
	//    )
	//    AND NOT EXISTS (
	//        SELECT 1
	//        FROM outbox_events AS skipped
	//        WHERE skipped.event_sequence > $6
	//          AND skipped.event_sequence < $1
	//          AND skipped.event_type = ANY(outbox_consumers.subscriptions)
	//    )
	//  RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//            retry_count, next_attempt_at, last_error_code, created_at, updated_at
	AckOutboxConsumerOffsetCAS(ctx context.Context, arg AckOutboxConsumerOffsetCASParams) (OutboxConsumer, error)
	//AcquireGameSessionOwnershipCAS
	//
	//  UPDATE game_sessions
	//  SET ownership_epoch = ownership_epoch + 1,
	//      updated_at = $1
	//  WHERE session_id = $2
	//    AND state_version = $3
	//    AND ownership_epoch = $4
	//    AND status IN ('active', 'suspended')
	//  RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
	//      state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
	//      state_payload, next_deadline_at, status, started_at, updated_at, ended_at
	AcquireGameSessionOwnershipCAS(ctx context.Context, arg AcquireGameSessionOwnershipCASParams) (GameSession, error)
	//AcquireKeyRotationJobLease
	//
	//  WITH candidate AS (
	//      SELECT job_id, status
	//      FROM key_rotation_jobs
	//      WHERE status IN ('pending', 'running')
	//        AND (lease_owner IS NULL OR lease_until <= $1)
	//      ORDER BY created_at, job_id
	//      FOR UPDATE SKIP LOCKED
	//      LIMIT 1
	//  )
	//  UPDATE key_rotation_jobs AS job
	//  SET status = 'running',
	//      started_at = COALESCE(job.started_at, $1),
	//      lease_owner = $2,
	//      lease_until = $3,
	//      updated_at = $1
	//  FROM candidate
	//  WHERE job.job_id = candidate.job_id
	//  RETURNING job.job_id, job.purpose, job.source_key_version, job.target_key_version,
	//            job.status, job.cursor_scope, job.cursor_id, job.cursor_ordinal,
	//            job.processed_count, job.conflict_count, job.lease_owner, job.lease_until,
	//            job.last_error_code, job.created_at, job.started_at, job.updated_at, job.completed_at,
	//            candidate.status = 'pending' AS started_now
	AcquireKeyRotationJobLease(ctx context.Context, arg AcquireKeyRotationJobLeaseParams) (AcquireKeyRotationJobLeaseRow, error)
	//AcquireOutboxConsumerLeaseCAS
	//
	//  UPDATE outbox_consumers
	//  SET lease_owner = $1,
	//      lease_until = $2,
	//      updated_at = $3
	//  WHERE consumer_id = $4
	//    AND lease_owner IS NOT DISTINCT FROM $5
	//    AND lease_until IS NOT DISTINCT FROM $6
	//    AND last_acked_sequence = $7
	//    AND retry_count = $8
	//    AND next_attempt_at IS NOT DISTINCT FROM $9
	//    AND last_error_code IS NOT DISTINCT FROM $10
	//    AND updated_at = $11
	//    AND (lease_until IS NULL OR lease_until <= pg_catalog.clock_timestamp())
	//    AND (next_attempt_at IS NULL OR next_attempt_at <= pg_catalog.clock_timestamp())
	//    AND $2 > pg_catalog.clock_timestamp()
	//  RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//            retry_count, next_attempt_at, last_error_code, created_at, updated_at
	AcquireOutboxConsumerLeaseCAS(ctx context.Context, arg AcquireOutboxConsumerLeaseCASParams) (OutboxConsumer, error)
	//ActivatePendingAdminTotpEnrollmentCAS
	//
	//  UPDATE admin_totp_enrollments
	//  SET status = 'active',
	//      expires_at = NULL,
	//      activated_at = $1
	//  WHERE admin_id = $2
	//    AND enrollment_id = $3
	//    AND status = 'pending'
	//    AND admin_version = $4
	//    AND expires_at > $1
	//  RETURNING enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//            operation_id, created_at, expires_at, activated_at, disabled_at
	ActivatePendingAdminTotpEnrollmentCAS(ctx context.Context, arg ActivatePendingAdminTotpEnrollmentCASParams) (AdminTotpEnrollment, error)
	//AdvanceKeyRotationCursorCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET cursor_scope = $1,
	//      cursor_id = $2,
	//      cursor_ordinal = $3,
	//      processed_count = processed_count + $4,
	//      conflict_count = conflict_count + $5,
	//      updated_at = $6
	//  WHERE job_id = $7
	//    AND status = 'running'
	//    AND lease_owner = $8
	//    AND lease_until > $6
	//    AND cursor_scope = $9
	//    AND cursor_id IS NOT DISTINCT FROM $10::uuid
	//    AND cursor_ordinal IS NOT DISTINCT FROM $11::bigint
	//  RETURNING job_id, status, cursor_scope, cursor_id, cursor_ordinal, processed_count,
	//            conflict_count, lease_owner, lease_until, updated_at
	AdvanceKeyRotationCursorCAS(ctx context.Context, arg AdvanceKeyRotationCursorCASParams) (AdvanceKeyRotationCursorCASRow, error)
	//AppendAuditEvent
	//
	//  WITH result AS (
	//      SELECT pg_catalog.to_jsonb(function_row) AS payload
	//      FROM append_audit_event(
	//          $1,
	//          $2,
	//          $3,
	//          $4,
	//          $5,
	//          $6,
	//          $7
	//      ) AS function_row
	//  )
	//  SELECT (result.payload ->> 'appended_sequence')::bigint AS appended_sequence,
	//         decode(pg_catalog.substring(result.payload ->> 'appended_hash', 3), 'hex') AS appended_hash
	//  FROM result
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AppendAuditEventRow, error)
	//BootstrapAdminPasswordCAS
	//
	//  UPDATE admin_accounts
	//  SET status = 'setup_required',
	//      password_hash = $1,
	//      password_algorithm = $2,
	//      password_parameters = $3,
	//      password_version = password_version + 1,
	//      admin_version = admin_version + 1,
	//      updated_at = $4
	//  WHERE singleton_id = 1
	//    AND status = 'bootstrap_pending'
	//    AND password_hash IS NULL
	//    AND admin_version = $5
	//  RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
	BootstrapAdminPasswordCAS(ctx context.Context, arg BootstrapAdminPasswordCASParams) (BootstrapAdminPasswordCASRow, error)
	//ChangeCurrentUsernameCAS
	//
	//  UPDATE users
	//  SET username = $1,
	//      current_username_key = $2,
	//      username_changed_at = $3,
	//      updated_at = $3
	//  WHERE user_id = $4
	//    AND status = 'active'
	//    AND username = $5
	//    AND current_username_key = $6
	//    AND username_changed_at = $7
	//    AND updated_at = $8
	//    AND username_changed_at <= $9
	//  RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	ChangeCurrentUsernameCAS(ctx context.Context, arg ChangeCurrentUsernameCASParams) (User, error)
	//ClaimUsername
	//
	//  INSERT INTO username_claims (
	//      username_key,
	//      display_username,
	//      status,
	//      owner_user_id,
	//      reserved_until,
	//      created_at,
	//      updated_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      'active',
	//      $3,
	//      NULL,
	//      $4,
	//      $4
	//  )
	//  ON CONFLICT (username_key) DO UPDATE
	//  SET display_username = EXCLUDED.display_username,
	//      status = 'active',
	//      owner_user_id = EXCLUDED.owner_user_id,
	//      reserved_until = NULL,
	//      updated_at = EXCLUDED.updated_at
	//  WHERE username_claims.status = 'reserved'
	//    AND username_claims.reserved_until <= $4
	//  RETURNING username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
	ClaimUsername(ctx context.Context, arg ClaimUsernameParams) (UsernameClaim, error)
	//CompleteGameSystemOperationCAS
	//
	//  UPDATE game_system_operations
	//  SET status = 'completed',
	//      result_code = $1,
	//      result_digest = $2,
	//      committed_state_version = $3,
	//      batch_id = $4,
	//      completed_at = $5
	//  WHERE session_id = $6
	//    AND operation_id = $7
	//    AND status = 'pending'
	//  RETURNING session_id, operation_id, source_kind, source_event_id, requested_by_user_id,
	//      logical_digest, status, result_code, result_digest, committed_state_version,
	//      batch_id, created_at, completed_at
	CompleteGameSystemOperationCAS(ctx context.Context, arg CompleteGameSystemOperationCASParams) (GameSystemOperation, error)
	//CompleteKeyRotationJobCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET status = 'completed',
	//      lease_owner = NULL,
	//      lease_until = NULL,
	//      completed_at = $1,
	//      updated_at = $1
	//  WHERE job_id = $2
	//    AND status = 'running'
	//    AND lease_owner = $3
	//    AND lease_until > $1
	//  RETURNING job_id, status, processed_count, conflict_count, completed_at
	CompleteKeyRotationJobCAS(ctx context.Context, arg CompleteKeyRotationJobCASParams) (CompleteKeyRotationJobCASRow, error)
	//CompleteOnboardingUserCAS
	//
	//  UPDATE users
	//  SET status = 'active',
	//      username = $1,
	//      current_username_key = $2,
	//      username_changed_at = $3,
	//      updated_at = $3
	//  WHERE user_id = $4
	//    AND status = 'onboarding'
	//    AND username IS NULL
	//    AND current_username_key IS NULL
	//    AND username_changed_at IS NULL
	//    AND updated_at = $5
	//    AND created_at = $6
	//    AND created_at <= $3
	//    AND $3 >= $5
	//    AND created_at > $3 - INTERVAL '86400 seconds'
	//  RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	CompleteOnboardingUserCAS(ctx context.Context, arg CompleteOnboardingUserCASParams) (User, error)
	//CompleteProfileExportContextCAS
	//
	//  UPDATE profile_export_contexts
	//  SET status = 'completed',
	//      completed_at = $1
	//  WHERE export_id = $2
	//    AND created_by_admin_id = $3
	//    AND status = 'active'
	//    AND expires_at > $1
	//  RETURNING export_id, status, completed_at
	CompleteProfileExportContextCAS(ctx context.Context, arg CompleteProfileExportContextCASParams) (CompleteProfileExportContextCASRow, error)
	//ConfirmSecretOperationResultCAS
	//
	//  UPDATE secret_operation_results
	//  SET status = 'confirmed',
	//      ciphertext = NULL,
	//      nonce = NULL,
	//      wrapped_data_key = NULL,
	//      confirmed_at = $1
	//  WHERE result_id = $2
	//    AND operation_scope = $3
	//    AND actor_or_challenge_id = $4
	//    AND operation_id = $5
	//    AND request_digest = $6
	//    AND result_type = $7
	//    AND result_version = $8
	//    AND status = 'available'
	//    AND secret_expires_at > $1
	//  RETURNING result_id, status, confirmed_at, tombstone_expires_at
	ConfirmSecretOperationResultCAS(ctx context.Context, arg ConfirmSecretOperationResultCASParams) (ConfirmSecretOperationResultCASRow, error)
	//ConsumeAdminAssistedRecoveryGrantCAS
	//
	//  UPDATE admin_assisted_recovery_grants
	//  SET status = 'consumed',
	//      consumed_at = $1,
	//      result_id = $2
	//  WHERE assisted_grant_id = $3
	//    AND user_id = $4
	//    AND status = 'active'
	//    AND attempt_count = $5
	//    AND expires_at > $1
	//    AND attempt_count < max_attempts
	//  RETURNING assisted_grant_id, user_id, selector, secret_hash, purpose, status,
	//            attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
	//            consumed_at, revoked_at, result_id
	ConsumeAdminAssistedRecoveryGrantCAS(ctx context.Context, arg ConsumeAdminAssistedRecoveryGrantCASParams) (AdminAssistedRecoveryGrant, error)
	//ConsumeAdminChallengeCAS
	//
	//  WITH current_admin AS MATERIALIZED (
	//      -- Direct CAS callers must acquire the same account-first lock as GetAdminChallengeForUpdate.
	//      SELECT admin_id, admin_version, password_version
	//      FROM admin_accounts
	//      WHERE singleton_id = 1
	//      FOR UPDATE
	//  )
	//  UPDATE admin_challenges AS challenge
	//  SET status = 'consumed',
	//      consumed_at = $1,
	//      replay_until = $2,
	//      operation_id = $3,
	//      request_digest = $4,
	//      result_id = $5
	//  FROM current_admin
	//  WHERE challenge.challenge_id = $6
	//    AND challenge.admin_id = current_admin.admin_id
	//    AND challenge.status = 'active'
	//    AND challenge.expires_at > $1
	//    AND challenge.attempt_count < challenge.max_attempts
	//    AND challenge.admin_version = $7
	//    AND challenge.password_version = $8
	//    AND challenge.admin_version = current_admin.admin_version
	//    AND challenge.password_version = current_admin.password_version
	//  RETURNING challenge.challenge_id, challenge.status, challenge.consumed_at,
	//            challenge.replay_until, challenge.operation_id, challenge.request_digest,
	//            challenge.result_id
	ConsumeAdminChallengeCAS(ctx context.Context, arg ConsumeAdminChallengeCASParams) (ConsumeAdminChallengeCASRow, error)
	//ConsumeAdminRecoveryCodeCAS
	//
	//  UPDATE admin_recovery_codes
	//  SET status = 'consumed',
	//      consumed_at = $1
	//  WHERE recovery_code_id = $2
	//    AND admin_id = $3
	//    AND set_version = $4
	//    AND status = 'active'
	//  RETURNING recovery_code_id, admin_id, set_version, status, consumed_at
	ConsumeAdminRecoveryCodeCAS(ctx context.Context, arg ConsumeAdminRecoveryCodeCASParams) (ConsumeAdminRecoveryCodeCASRow, error)
	//ConsumeAnonymousChallengeCAS
	//
	//  UPDATE anonymous_challenges
	//  SET consumed_at = $1,
	//      replay_until = $2,
	//      operation_id = $3,
	//      request_digest = $4,
	//      result_id = $5
	//  WHERE challenge_id = $6
	//    AND consumed_at IS NULL
	//    AND expires_at > $1
	//    AND attempt_count < max_attempts
	//  RETURNING challenge_id, consumed_at, replay_until, operation_id, request_digest, result_id
	ConsumeAnonymousChallengeCAS(ctx context.Context, arg ConsumeAnonymousChallengeCASParams) (ConsumeAnonymousChallengeCASRow, error)
	//ConsumeAnonymousChallengeWithoutReplayCAS
	//
	//  UPDATE anonymous_challenges
	//  SET consumed_at = $1
	//  WHERE challenge_id = $2
	//    AND consumed_at IS NULL
	//    AND expires_at > $1
	//    AND attempt_count < max_attempts
	//  RETURNING challenge_id, consumed_at
	ConsumeAnonymousChallengeWithoutReplayCAS(ctx context.Context, arg ConsumeAnonymousChallengeWithoutReplayCASParams) (ConsumeAnonymousChallengeWithoutReplayCASRow, error)
	//ConsumeUserRecoveryAttemptCAS
	//
	//  UPDATE user_recovery_attempts
	//  SET status = 'consumed',
	//      consumed_at = $1,
	//      request_digest = $2,
	//      result_id = $3
	//  WHERE recovery_attempt_id = $4
	//    AND status = 'active'
	//    AND attempt_count = $5
	//    AND expires_at > $1
	//    AND attempt_count < max_attempts
	//  RETURNING recovery_attempt_id, grant_selector, grant_secret_hash, grant_key_version,
	//            user_id, recovery_credential_id, recovery_credential_version, assisted_grant_id,
	//            challenge_id, origin_hash, purpose, request_digest, attempt_count, max_attempts,
	//            status, created_at, expires_at, consumed_at, revoked_at, result_id
	ConsumeUserRecoveryAttemptCAS(ctx context.Context, arg ConsumeUserRecoveryAttemptCASParams) (UserRecoveryAttempt, error)
	//ConsumeUserRecoveryCredentialCAS
	//
	//  UPDATE user_recovery_credentials
	//  SET status = 'consumed',
	//      consumed_at = $1
	//  WHERE recovery_credential_id = $2
	//    AND user_id = $3
	//    AND version = $4
	//    AND status = 'active'
	//  RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
	//            created_at, consumed_at, revoked_at, revoke_reason
	ConsumeUserRecoveryCredentialCAS(ctx context.Context, arg ConsumeUserRecoveryCredentialCASParams) (UserRecoveryCredential, error)
	//CountPIIKeyReferences
	//
	//  SELECT (
	//      (SELECT count(*) FROM user_profiles AS profile WHERE profile.real_name_key_version = $1)
	//      +
	//      (SELECT count(*) FROM profile_export_items AS item WHERE item.real_name_key_version = $1)
	//  )::bigint AS reference_count
	CountPIIKeyReferences(ctx context.Context, arg CountPIIKeyReferencesParams) (int64, error)
	//CountTotpKeyReferences
	//
	//  SELECT count(*)::bigint AS reference_count
	//  FROM admin_totp_enrollments
	//  WHERE key_version = $1
	//    AND status IN ('pending', 'active')
	CountTotpKeyReferences(ctx context.Context, arg CountTotpKeyReferencesParams) (int64, error)
	//CreateAdminAssistedRecoveryGrant
	//
	//  INSERT INTO admin_assisted_recovery_grants (
	//      assisted_grant_id,
	//      user_id,
	//      selector,
	//      secret_hash,
	//      purpose,
	//      status,
	//      attempt_count,
	//      max_attempts,
	//      created_by_admin_id,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      'active',
	//      0,
	//      $6,
	//      $7,
	//      $8,
	//      $9
	//  )
	//  RETURNING assisted_grant_id, user_id, selector, secret_hash, purpose, status,
	//            attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
	//            consumed_at, revoked_at, result_id
	CreateAdminAssistedRecoveryGrant(ctx context.Context, arg CreateAdminAssistedRecoveryGrantParams) (AdminAssistedRecoveryGrant, error)
	//CreateAdminChallenge
	//
	//  INSERT INTO admin_challenges (
	//      challenge_id,
	//      admin_id,
	//      selector,
	//      secret_hash,
	//      secret_key_version,
	//      purpose,
	//      audience,
	//      admin_version,
	//      password_version,
	//      origin_hash,
	//      request_flow_id,
	//      attempt_count,
	//      max_attempts,
	//      status,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      0,
	//      $12,
	//      'active',
	//      $13,
	//      $14
	//  )
	//  RETURNING challenge_id, admin_id, selector, secret_hash, secret_key_version, purpose,
	//            audience, admin_version, password_version, origin_hash, request_flow_id,
	//            attempt_count, max_attempts, status, created_at, expires_at, consumed_at,
	//            revoked_at, replay_until, operation_id, request_digest, result_id
	CreateAdminChallenge(ctx context.Context, arg CreateAdminChallengeParams) (AdminChallenge, error)
	//CreateAdminRecoveryCode
	//
	//  INSERT INTO admin_recovery_codes (
	//      recovery_code_id,
	//      admin_id,
	//      selector,
	//      secret_hash,
	//      set_version,
	//      status,
	//      created_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      'active',
	//      $6
	//  )
	//  RETURNING recovery_code_id, admin_id, selector, secret_hash, set_version, status,
	//            created_at, consumed_at, revoked_at
	CreateAdminRecoveryCode(ctx context.Context, arg CreateAdminRecoveryCodeParams) (AdminRecoveryCode, error)
	//CreateAdminSession
	//
	//  INSERT INTO admin_sessions (
	//      session_id,
	//      admin_id,
	//      selector,
	//      secret_hash,
	//      secret_key_version,
	//      csrf_hash,
	//      kind,
	//      admin_version,
	//      password_version,
	//      attempt_count,
	//      max_attempts,
	//      created_at,
	//      last_seen_at,
	//      idle_expires_at,
	//      absolute_expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      0,
	//      $10,
	//      $11,
	//      $11,
	//      $12,
	//      $13
	//  )
	//  RETURNING session_id, admin_id, selector, secret_hash, secret_key_version, csrf_hash,
	//            kind, admin_version, password_version, attempt_count, max_attempts, created_at,
	//            last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error)
	//CreateAnonymousChallenge
	//
	//  INSERT INTO anonymous_challenges (
	//      challenge_id,
	//      selector,
	//      secret_hash,
	//      secret_key_version,
	//      purpose,
	//      audience,
	//      origin_hash,
	//      request_flow_id,
	//      attempt_count,
	//      max_attempts,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      0,
	//      $9,
	//      $10,
	//      $11
	//  )
	//  RETURNING challenge_id, selector, secret_hash, secret_key_version, purpose, audience,
	//            origin_hash, request_flow_id, attempt_count, max_attempts, created_at, expires_at,
	//            consumed_at, replay_until, operation_id, request_digest, result_id
	CreateAnonymousChallenge(ctx context.Context, arg CreateAnonymousChallengeParams) (AnonymousChallenge, error)
	//CreateDeviceCredential
	//
	//  INSERT INTO device_credentials (
	//      credential_id,
	//      user_id,
	//      secret_hash,
	//      secret_key_version,
	//      csrf_hash,
	//      generation,
	//      label,
	//      created_at,
	//      last_seen_at,
	//      rotated_at,
	//      idle_expires_at,
	//      absolute_expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      1,
	//      $6,
	//      $7,
	//      $7,
	//      $7,
	//      $8,
	//      $9
	//  )
	//  RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
	//            previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
	//            created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
	//            revoked_at, revoke_reason
	CreateDeviceCredential(ctx context.Context, arg CreateDeviceCredentialParams) (DeviceCredential, error)
	//CreateGameActionReceipt
	//
	//  INSERT INTO game_action_receipts (
	//      session_id,
	//      actor_user_id,
	//      action_id,
	//      request_digest,
	//      result_code,
	//      result_digest,
	//      committed_state_version,
	//      committed_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8
	//  )
	//  ON CONFLICT (session_id, actor_user_id, action_id) DO NOTHING
	//  RETURNING session_id, actor_user_id, action_id, request_digest, result_code,
	//      result_digest, committed_state_version, committed_at
	CreateGameActionReceipt(ctx context.Context, arg CreateGameActionReceiptParams) (GameActionReceipt, error)
	//CreateGameSession
	//
	//  INSERT INTO game_sessions (
	//      session_id,
	//      room_id,
	//      game_id,
	//      engine_version,
	//      protocol_version,
	//      client_version,
	//      state_version,
	//      ownership_epoch,
	//      snapshot_version,
	//      state_message_type,
	//      state_schema_version,
	//      state_payload,
	//      next_deadline_at,
	//      status,
	//      started_at,
	//      updated_at,
	//      ended_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      $12,
	//      $13,
	//      $14,
	//      $15,
	//      $16,
	//      $17
	//  )
	//  RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
	//      state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
	//      state_payload, next_deadline_at, status, started_at, updated_at, ended_at
	CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (GameSession, error)
	//CreateGameSessionEvent
	//
	//  INSERT INTO game_session_events (batch_id, event_ordinal, message_type, schema_version, payload)
	//  VALUES (
	//      $1, $2, $3,
	//      $4, $5
	//  )
	CreateGameSessionEvent(ctx context.Context, arg CreateGameSessionEventParams) error
	//CreateGameSessionEventBatch
	//
	//  INSERT INTO game_session_event_batches (
	//      batch_id,
	//      session_id,
	//      state_version,
	//      ownership_epoch,
	//      cause,
	//      actor_user_id,
	//      action_id,
	//      timer_id,
	//      system_operation_id,
	//      system_source_kind,
	//      system_source_event_id,
	//      system_requested_by_user_id,
	//      system_request_digest,
	//      executed_at,
	//      random_seed,
	//      allocated_ids,
	//      input_message_type,
	//      input_schema_version,
	//      input_payload,
	//      event_count,
	//      committed_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      $12,
	//      $13,
	//      $14,
	//      $15,
	//      $16,
	//      $17,
	//      $18,
	//      $19,
	//      $20,
	//      $21
	//  )
	//  RETURNING batch_id, session_id, state_version, ownership_epoch, cause, actor_user_id,
	//      action_id, timer_id, system_operation_id, system_source_kind, system_source_event_id,
	//      system_requested_by_user_id, system_request_digest,
	//      executed_at, random_seed, allocated_ids, input_message_type,
	//      input_schema_version, input_payload, event_count, committed_at
	CreateGameSessionEventBatch(ctx context.Context, arg CreateGameSessionEventBatchParams) (CreateGameSessionEventBatchRow, error)
	//CreateGameSessionParticipant
	//
	//  INSERT INTO game_session_participants (session_id, user_id, seat_index)
	//  VALUES ($1, $2, $3)
	CreateGameSessionParticipant(ctx context.Context, arg CreateGameSessionParticipantParams) error
	//CreateGameSessionStartReceipt
	//
	//  INSERT INTO game_session_start_receipts (
	//      actor_user_id, room_id, operation_id, request_digest, session_id, committed_at
	//  ) VALUES (
	//      $1, $2, $3,
	//      $4, $5, $6
	//  )
	//  ON CONFLICT (actor_user_id, room_id, operation_id) DO NOTHING
	//  RETURNING actor_user_id, room_id, operation_id, request_digest, session_id, committed_at
	CreateGameSessionStartReceipt(ctx context.Context, arg CreateGameSessionStartReceiptParams) (GameSessionStartReceipt, error)
	//CreateGameSessionTimer
	//
	//  INSERT INTO game_session_timers (
	//      session_id, timer_id, expected_state_version, due_at, message_type, schema_version, payload
	//  ) VALUES (
	//      $1, $2, $3, $4,
	//      $5, $6, $7
	//  )
	CreateGameSessionTimer(ctx context.Context, arg CreateGameSessionTimerParams) error
	//CreateGameTimerReceipt
	//
	//  INSERT INTO game_timer_receipts (
	//      session_id, timer_id, expected_state_version, result_code, result_digest,
	//      committed_state_version, batch_id, committed_at
	//  ) VALUES (
	//      $1, $2, $3,
	//      $4, $5, $6,
	//      $7, $8
	//  )
	//  ON CONFLICT (session_id, timer_id, expected_state_version) DO NOTHING
	//  RETURNING session_id, timer_id, expected_state_version, result_code, result_digest,
	//      committed_state_version, batch_id, committed_at
	CreateGameTimerReceipt(ctx context.Context, arg CreateGameTimerReceiptParams) (GameTimerReceipt, error)
	//CreateKeyRotationJob
	//
	//  INSERT INTO key_rotation_jobs (
	//      job_id,
	//      purpose,
	//      source_key_version,
	//      target_key_version,
	//      status,
	//      cursor_scope,
	//      processed_count,
	//      conflict_count,
	//      created_at,
	//      updated_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      'pending',
	//      $5,
	//      0,
	//      0,
	//      $6,
	//      $6
	//  )
	//  ON CONFLICT (purpose) WHERE status IN ('pending', 'running') DO NOTHING
	//  RETURNING job_id, purpose, source_key_version, target_key_version, status, cursor_scope,
	//            cursor_id, cursor_ordinal, processed_count, conflict_count, lease_owner,
	//            lease_until, last_error_code, created_at, started_at, updated_at, completed_at
	CreateKeyRotationJob(ctx context.Context, arg CreateKeyRotationJobParams) (KeyRotationJob, error)
	//CreateOutboxConsumer
	//
	//  INSERT INTO outbox_consumers (
	//      consumer_id,
	//      subscriptions,
	//      last_acked_sequence,
	//      created_at,
	//      updated_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $4
	//  )
	//  ON CONFLICT (consumer_id) DO NOTHING
	//  RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//            retry_count, next_attempt_at, last_error_code, created_at, updated_at
	CreateOutboxConsumer(ctx context.Context, arg CreateOutboxConsumerParams) (OutboxConsumer, error)
	//CreateOutboxEvent
	//
	//  WITH serialized AS MATERIALIZED (
	//      -- Transaction-level serialization makes identity sequence order match commit order for offset safety.
	//      SELECT pg_catalog.pg_advisory_xact_lock(1196314434, 1)
	//  )
	//  INSERT INTO outbox_events (
	//      event_id,
	//      event_type,
	//      aggregate_type,
	//      aggregate_id,
	//      payload,
	//      created_at,
	//      available_at
	//  ) SELECT
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7
	//  FROM serialized
	//  ON CONFLICT (event_id) DO NOTHING
	//  RETURNING event_sequence, event_id, event_type, aggregate_type, aggregate_id,
	//            payload, created_at, available_at
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	//CreatePartyRoom
	//
	//  INSERT INTO party_rooms (
	//      room_id,
	//      room_code,
	//      visibility,
	//      status,
	//      host_user_id,
	//      participant_capacity,
	//      participant_admission,
	//      spectator_admission,
	//      active_session_id,
	//      active_game_id,
	//      room_version,
	//      membership_version,
	//      created_at,
	//      updated_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      $12,
	//      $13,
	//      $14
	//  )
	//  RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
	//      participant_admission, spectator_admission, active_session_id, active_game_id,
	//      room_version, membership_version, created_at, updated_at
	CreatePartyRoom(ctx context.Context, arg CreatePartyRoomParams) (PartyRoom, error)
	//CreatePendingAdminTotpEnrollment
	//
	//  INSERT INTO admin_totp_enrollments (
	//      enrollment_id,
	//      admin_id,
	//      ciphertext,
	//      nonce,
	//      key_version,
	//      status,
	//      admin_version,
	//      operation_id,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      'pending',
	//      $6,
	//      $7,
	//      $8,
	//      $9
	//  )
	//  ON CONFLICT (admin_id) WHERE status = 'pending' DO NOTHING
	//  RETURNING enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//            operation_id, created_at, expires_at, activated_at, disabled_at
	CreatePendingAdminTotpEnrollment(ctx context.Context, arg CreatePendingAdminTotpEnrollmentParams) (AdminTotpEnrollment, error)
	//CreateProfileExportContext
	//
	//  INSERT INTO profile_export_contexts (
	//      export_id,
	//      created_by_admin_id,
	//      filter_digest,
	//      requested_fields,
	//      schema_version,
	//      item_count,
	//      status,
	//      reason,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      'active',
	//      $7,
	//      $8,
	//      $9
	//  )
	//  RETURNING export_id, created_by_admin_id, filter_digest, requested_fields, schema_version,
	//            item_count, status, reason, created_at, expires_at, completed_at, aborted_at, expired_at
	CreateProfileExportContext(ctx context.Context, arg CreateProfileExportContextParams) (ProfileExportContext, error)
	//CreateProfileExportItem
	//
	//  INSERT INTO profile_export_items (
	//      export_id,
	//      ordinal,
	//      user_id,
	//      username,
	//      profile_version,
	//      real_name_ciphertext,
	//      real_name_nonce,
	//      real_name_key_version
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8
	//  )
	//  RETURNING export_id, ordinal, user_id, username, profile_version,
	//            real_name_ciphertext, real_name_nonce, real_name_key_version
	CreateProfileExportItem(ctx context.Context, arg CreateProfileExportItemParams) (ProfileExportItem, error)
	//CreateRoomMember
	//
	//  INSERT INTO room_members (
	//      room_id,
	//      user_id,
	//      role,
	//      requested_role,
	//      seat_index,
	//      joined_at,
	//      last_seen_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7
	//  )
	CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error
	//CreateSecretOperationResult
	//
	//  INSERT INTO secret_operation_results (
	//      result_id,
	//      operation_scope,
	//      actor_or_challenge_id,
	//      operation_id,
	//      request_digest,
	//      result_type,
	//      result_version,
	//      ciphertext,
	//      nonce,
	//      wrapped_data_key,
	//      key_version,
	//      status,
	//      secret_expires_at,
	//      completed_at,
	//      tombstone_expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      'available',
	//      $12,
	//      $13,
	//      $14
	//  )
	//  ON CONFLICT (operation_scope, actor_or_challenge_id, operation_id) DO NOTHING
	//  RETURNING result_id, operation_scope, actor_or_challenge_id, operation_id, request_digest,
	//            result_type, result_version, ciphertext, nonce, wrapped_data_key, key_version,
	//            status, secret_expires_at, confirmed_at, completed_at, tombstone_expires_at
	CreateSecretOperationResult(ctx context.Context, arg CreateSecretOperationResultParams) (SecretOperationResult, error)
	//CreateUser
	//
	//  INSERT INTO users (
	//      user_id,
	//      status,
	//      created_at,
	//      updated_at
	//  ) VALUES (
	//      $1,
	//      'onboarding',
	//      $2,
	//      $2
	//  )
	//  RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//CreateUserProfile
	//
	//  INSERT INTO user_profiles (
	//      user_id,
	//      real_name_ciphertext,
	//      real_name_nonce,
	//      real_name_key_version,
	//      profile_version,
	//      real_name_updated_at,
	//      real_name_updated_by
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      1,
	//      $5,
	//      $6
	//  )
	//  ON CONFLICT (user_id) DO NOTHING
	//  RETURNING user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//            profile_version, real_name_updated_at, real_name_updated_by
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	//CreateUserRecoveryAttempt
	//
	//  INSERT INTO user_recovery_attempts (
	//      recovery_attempt_id,
	//      grant_selector,
	//      grant_secret_hash,
	//      grant_key_version,
	//      user_id,
	//      recovery_credential_id,
	//      recovery_credential_version,
	//      assisted_grant_id,
	//      challenge_id,
	//      origin_hash,
	//      purpose,
	//      attempt_count,
	//      max_attempts,
	//      status,
	//      created_at,
	//      expires_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      0,
	//      $12,
	//      'active',
	//      $13,
	//      $14
	//  )
	//  RETURNING recovery_attempt_id, grant_selector, grant_secret_hash, grant_key_version,
	//            user_id, recovery_credential_id, recovery_credential_version, assisted_grant_id,
	//            challenge_id, origin_hash, purpose, request_digest, attempt_count, max_attempts,
	//            status, created_at, expires_at, consumed_at, revoked_at, result_id
	CreateUserRecoveryAttempt(ctx context.Context, arg CreateUserRecoveryAttemptParams) (UserRecoveryAttempt, error)
	//CreateUserRecoveryCredential
	//
	//  INSERT INTO user_recovery_credentials (
	//      recovery_credential_id,
	//      user_id,
	//      selector,
	//      secret_hash,
	//      version,
	//      status,
	//      created_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      'active',
	//      $6
	//  )
	//  RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
	//            created_at, consumed_at, revoked_at, revoke_reason
	CreateUserRecoveryCredential(ctx context.Context, arg CreateUserRecoveryCredentialParams) (UserRecoveryCredential, error)
	//DeleteGameSessionTimers
	//
	//  DELETE FROM game_session_timers WHERE session_id = $1
	DeleteGameSessionTimers(ctx context.Context, arg DeleteGameSessionTimersParams) error
	//DeleteRoomMembers
	//
	//  DELETE FROM room_members WHERE room_id = $1
	DeleteRoomMembers(ctx context.Context, arg DeleteRoomMembersParams) error
	//DisableActiveAdminTotpEnrollmentCAS
	//
	//  UPDATE admin_totp_enrollments
	//  SET status = 'disabled',
	//      ciphertext = NULL,
	//      nonce = NULL,
	//      disabled_at = $1
	//  WHERE admin_id = $2
	//    AND enrollment_id = $3
	//    AND status = 'active'
	//    AND admin_version = $4
	//  RETURNING enrollment_id, admin_id, status, disabled_at
	DisableActiveAdminTotpEnrollmentCAS(ctx context.Context, arg DisableActiveAdminTotpEnrollmentCASParams) (DisableActiveAdminTotpEnrollmentCASRow, error)
	//ExpireProfileExportContextCAS
	//
	//  UPDATE profile_export_contexts
	//  SET status = 'expired',
	//      expired_at = $1
	//  WHERE export_id = $2
	//    AND status = 'active'
	//    AND expires_at <= $1
	//  RETURNING export_id, status, expired_at
	ExpireProfileExportContextCAS(ctx context.Context, arg ExpireProfileExportContextCASParams) (ExpireProfileExportContextCASRow, error)
	//ExpireSecretOperationResultCAS
	//
	//  UPDATE secret_operation_results
	//  SET status = 'expired',
	//      ciphertext = NULL,
	//      nonce = NULL,
	//      wrapped_data_key = NULL
	//  WHERE result_id = $1
	//    AND status = 'available'
	//    AND secret_expires_at <= $2
	//  RETURNING result_id, status, tombstone_expires_at
	ExpireSecretOperationResultCAS(ctx context.Context, arg ExpireSecretOperationResultCASParams) (ExpireSecretOperationResultCASRow, error)
	//FailKeyRotationJobCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET status = 'failed',
	//      lease_owner = NULL,
	//      lease_until = NULL,
	//      last_error_code = $1,
	//      updated_at = $2
	//  WHERE job_id = $3
	//    AND status = 'running'
	//    AND lease_owner = $4
	//  RETURNING job_id, status, processed_count, conflict_count, last_error_code, updated_at
	FailKeyRotationJobCAS(ctx context.Context, arg FailKeyRotationJobCASParams) (FailKeyRotationJobCASRow, error)
	//FinishPartyRoomCAS
	//
	//  UPDATE party_rooms
	//  SET status = 'lobby',
	//      participant_admission = 'closed',
	//      active_session_id = NULL,
	//      active_game_id = NULL,
	//      room_version = $1,
	//      updated_at = $2
	//  WHERE room_id = $3
	//    AND status = 'playing'
	//    AND active_session_id = $4
	//    AND active_game_id = $5
	//    AND room_version = $6
	//    AND membership_version = $7
	//  RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
	//      participant_admission, spectator_admission, active_session_id, active_game_id,
	//      room_version, membership_version, created_at, updated_at
	FinishPartyRoomCAS(ctx context.Context, arg FinishPartyRoomCASParams) (PartyRoom, error)
	//GetActiveAdminTotpEnrollmentForUpdate
	//
	//  SELECT enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//         operation_id, created_at, expires_at, activated_at, disabled_at
	//  FROM admin_totp_enrollments
	//  WHERE admin_id = $1
	//    AND status = 'active'
	//  FOR UPDATE
	GetActiveAdminTotpEnrollmentForUpdate(ctx context.Context, arg GetActiveAdminTotpEnrollmentForUpdateParams) (AdminTotpEnrollment, error)
	//GetActiveUserRecoveryCredentialForUpdate
	//
	//  SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
	//         created_at, consumed_at, revoked_at, revoke_reason
	//  FROM user_recovery_credentials
	//  WHERE user_id = $1
	//    AND status = 'active'
	//  FOR UPDATE
	GetActiveUserRecoveryCredentialForUpdate(ctx context.Context, arg GetActiveUserRecoveryCredentialForUpdateParams) (UserRecoveryCredential, error)
	//GetAdminAssistedRecoveryGrantBySelector
	//
	//  SELECT assisted_grant_id, user_id, selector, secret_hash, purpose, status,
	//         attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
	//         consumed_at, revoked_at, result_id
	//  FROM admin_assisted_recovery_grants
	//  WHERE selector = $1
	GetAdminAssistedRecoveryGrantBySelector(ctx context.Context, arg GetAdminAssistedRecoveryGrantBySelectorParams) (AdminAssistedRecoveryGrant, error)
	//GetAdminAssistedRecoveryGrantForUpdate
	//
	//  WITH locked_user AS MATERIALIZED (
	//      SELECT target.user_id
	//      FROM users AS target
	//      WHERE target.user_id = $2
	//      FOR UPDATE OF target
	//  )
	//  SELECT grants.assisted_grant_id, grants.user_id, grants.selector, grants.secret_hash,
	//         grants.purpose, grants.status, grants.attempt_count, grants.max_attempts,
	//         grants.created_by_admin_id, grants.created_at, grants.expires_at,
	//         grants.consumed_at, grants.revoked_at, grants.result_id
	//  FROM admin_assisted_recovery_grants AS grants
	//  JOIN locked_user AS users ON users.user_id = grants.user_id
	//  WHERE grants.assisted_grant_id = $1
	//  FOR UPDATE OF grants
	GetAdminAssistedRecoveryGrantForUpdate(ctx context.Context, arg GetAdminAssistedRecoveryGrantForUpdateParams) (AdminAssistedRecoveryGrant, error)
	//GetAdminChallengeForUpdate
	//
	//  WITH current_admin AS MATERIALIZED (
	//      -- Lock the account generation before the challenge to match every security-state transition.
	//      SELECT admin_id, admin_version, password_version
	//      FROM admin_accounts
	//      WHERE singleton_id = 1
	//      FOR UPDATE
	//  )
	//  SELECT challenge.challenge_id, challenge.admin_id, challenge.selector, challenge.secret_hash,
	//         challenge.secret_key_version, challenge.purpose, challenge.audience,
	//         challenge.admin_version, challenge.password_version, challenge.origin_hash,
	//         challenge.request_flow_id, challenge.attempt_count, challenge.max_attempts,
	//         challenge.status, challenge.created_at, challenge.expires_at, challenge.consumed_at,
	//         challenge.revoked_at, challenge.replay_until, challenge.operation_id,
	//         challenge.request_digest, challenge.result_id
	//  FROM current_admin
	//  JOIN admin_challenges AS challenge ON challenge.admin_id = current_admin.admin_id
	//  WHERE challenge.selector = $1
	//    AND challenge.admin_version = current_admin.admin_version
	//    AND challenge.password_version = current_admin.password_version
	//  FOR UPDATE OF challenge
	GetAdminChallengeForUpdate(ctx context.Context, arg GetAdminChallengeForUpdateParams) (AdminChallenge, error)
	//GetAdminRecoveryCodeForUpdate
	//
	//  SELECT recovery_code_id, admin_id, selector, secret_hash, set_version, status,
	//         created_at, consumed_at, revoked_at
	//  FROM admin_recovery_codes
	//  WHERE selector = $1
	//  FOR UPDATE
	GetAdminRecoveryCodeForUpdate(ctx context.Context, arg GetAdminRecoveryCodeForUpdateParams) (AdminRecoveryCode, error)
	//GetAdminSessionForUpdate
	//
	//  SELECT session_id, admin_id, selector, secret_hash, secret_key_version, csrf_hash,
	//         kind, admin_version, password_version, attempt_count, max_attempts, created_at,
	//         last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
	//  FROM admin_sessions
	//  WHERE selector = $1
	//  FOR UPDATE
	GetAdminSessionForUpdate(ctx context.Context, arg GetAdminSessionForUpdateParams) (AdminSession, error)
	//GetAnonymousChallengeForUpdate
	//
	//  SELECT challenge_id, selector, secret_hash, secret_key_version, purpose, audience,
	//         origin_hash, request_flow_id, attempt_count, max_attempts, created_at, expires_at,
	//         consumed_at, replay_until, operation_id, request_digest, result_id
	//  FROM anonymous_challenges
	//  WHERE selector = $1
	//  FOR UPDATE
	GetAnonymousChallengeForUpdate(ctx context.Context, arg GetAnonymousChallengeForUpdateParams) (AnonymousChallenge, error)
	//GetDeviceCredentialForUpdate
	//
	//  SELECT credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
	//         previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
	//         created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
	//         revoked_at, revoke_reason
	//  FROM device_credentials
	//  WHERE credential_id = $1
	//  FOR UPDATE
	GetDeviceCredentialForUpdate(ctx context.Context, arg GetDeviceCredentialForUpdateParams) (DeviceCredential, error)
	//GetDeviceIdentityForUpdate
	//
	//  WITH selected_device AS MATERIALIZED (
	//      SELECT selected.user_id
	//      FROM device_credentials AS selected
	//      WHERE selected.credential_id = $1
	//  ),
	//  locked_user AS MATERIALIZED (
	//      SELECT u.user_id, u.status, u.username, u.current_username_key,
	//             u.username_changed_at, u.created_at, u.updated_at
	//      FROM users AS u
	//      JOIN selected_device AS selected ON selected.user_id = u.user_id
	//      FOR UPDATE OF u
	//  ),
	//  locked_device AS MATERIALIZED (
	//      SELECT d.credential_id, d.user_id, d.secret_hash, d.secret_key_version,
	//             d.previous_secret_hash, d.previous_secret_key_version, d.previous_valid_until,
	//             d.csrf_hash, d.generation, d.label, d.created_at, d.last_seen_at, d.rotated_at,
	//             d.idle_expires_at, d.absolute_expires_at, d.revoked_at, d.revoke_reason
	//      FROM device_credentials AS d
	//      JOIN locked_user AS locked ON locked.user_id = d.user_id
	//      WHERE d.credential_id = $1
	//      FOR UPDATE OF d
	//  )
	//  SELECT u.user_id AS user_id,
	//         u.status AS user_status,
	//         u.username AS user_username,
	//         u.current_username_key AS user_current_username_key,
	//         u.username_changed_at AS user_username_changed_at,
	//         u.created_at AS user_created_at,
	//         u.updated_at AS user_updated_at,
	//         d.credential_id,
	//         d.secret_hash,
	//         d.secret_key_version,
	//         d.previous_secret_hash,
	//         d.previous_secret_key_version,
	//         d.previous_valid_until,
	//         d.csrf_hash,
	//         d.generation,
	//         d.label,
	//         d.created_at AS device_created_at,
	//         d.last_seen_at,
	//         d.rotated_at,
	//         d.idle_expires_at,
	//         d.absolute_expires_at,
	//         d.revoked_at,
	//         d.revoke_reason
	//  FROM locked_user AS u
	//  JOIN locked_device AS d ON d.user_id = u.user_id
	GetDeviceIdentityForUpdate(ctx context.Context, arg GetDeviceIdentityForUpdateParams) (GetDeviceIdentityForUpdateRow, error)
	//GetGameActionReceipt
	//
	//  SELECT session_id, actor_user_id, action_id, request_digest, result_code,
	//      result_digest, committed_state_version, committed_at
	//  FROM game_action_receipts
	//  WHERE session_id = $1
	//    AND actor_user_id = $2
	//    AND action_id = $3
	GetGameActionReceipt(ctx context.Context, arg GetGameActionReceiptParams) (GameActionReceipt, error)
	//GetGameSessionForShare
	//
	//  SELECT session_id, room_id, game_id, engine_version, protocol_version, client_version,
	//      state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
	//      state_payload, next_deadline_at, status, started_at, updated_at, ended_at
	//  FROM game_sessions
	//  WHERE session_id = $1
	//  FOR SHARE
	GetGameSessionForShare(ctx context.Context, arg GetGameSessionForShareParams) (GameSession, error)
	//GetGameSessionForUpdate
	//
	//  SELECT session_id, room_id, game_id, engine_version, protocol_version, client_version,
	//      state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
	//      state_payload, next_deadline_at, status, started_at, updated_at, ended_at
	//  FROM game_sessions
	//  WHERE session_id = $1
	//  FOR UPDATE
	GetGameSessionForUpdate(ctx context.Context, arg GetGameSessionForUpdateParams) (GameSession, error)
	//GetGameSessionRoomID
	//
	//  SELECT room_id
	//  FROM game_sessions
	//  WHERE session_id = $1
	GetGameSessionRoomID(ctx context.Context, arg GetGameSessionRoomIDParams) (pgtype.UUID, error)
	//GetGameSessionStartReceipt
	//
	//  SELECT actor_user_id, room_id, operation_id, request_digest, session_id, committed_at
	//  FROM game_session_start_receipts
	//  WHERE actor_user_id = $1
	//    AND room_id = $2
	//    AND operation_id = $3
	GetGameSessionStartReceipt(ctx context.Context, arg GetGameSessionStartReceiptParams) (GameSessionStartReceipt, error)
	//GetGameSessionStartReceiptForUpdate
	//
	//  SELECT actor_user_id, room_id, operation_id, request_digest, session_id, committed_at
	//  FROM game_session_start_receipts
	//  WHERE actor_user_id = $1
	//    AND room_id = $2
	//    AND operation_id = $3
	//  FOR UPDATE
	GetGameSessionStartReceiptForUpdate(ctx context.Context, arg GetGameSessionStartReceiptForUpdateParams) (GameSessionStartReceipt, error)
	//GetGameSessionTimerForUpdate
	//
	//  SELECT session_id, timer_id, expected_state_version, due_at, message_type, schema_version, payload
	//  FROM game_session_timers
	//  WHERE session_id = $1
	//    AND timer_id = $2
	//  FOR UPDATE
	GetGameSessionTimerForUpdate(ctx context.Context, arg GetGameSessionTimerForUpdateParams) (GameSessionTimer, error)
	//GetGameSystemOperationBySourceForUpdate
	//
	//  SELECT session_id, operation_id, source_kind, source_event_id, requested_by_user_id,
	//      logical_digest, status, result_code, result_digest, committed_state_version,
	//      batch_id, created_at, completed_at
	//  FROM game_system_operations
	//  WHERE session_id = $1
	//    AND source_event_id = $2
	//  FOR UPDATE
	GetGameSystemOperationBySourceForUpdate(ctx context.Context, arg GetGameSystemOperationBySourceForUpdateParams) (GameSystemOperation, error)
	//GetGameSystemOperationForUpdate
	//
	//  SELECT session_id, operation_id, source_kind, source_event_id, requested_by_user_id,
	//      logical_digest, status, result_code, result_digest, committed_state_version,
	//      batch_id, created_at, completed_at
	//  FROM game_system_operations
	//  WHERE session_id = $1
	//    AND operation_id = $2
	//  FOR UPDATE
	GetGameSystemOperationForUpdate(ctx context.Context, arg GetGameSystemOperationForUpdateParams) (GameSystemOperation, error)
	//GetGameTimerReceipt
	//
	//  SELECT session_id, timer_id, expected_state_version, result_code, result_digest,
	//      committed_state_version, batch_id, committed_at
	//  FROM game_timer_receipts
	//  WHERE session_id = $1
	//    AND timer_id = $2
	//    AND expected_state_version = $3
	GetGameTimerReceipt(ctx context.Context, arg GetGameTimerReceiptParams) (GameTimerReceipt, error)
	//GetKeyRotationJob
	//
	//  SELECT job_id, purpose, source_key_version, target_key_version, status, cursor_scope,
	//         cursor_id, cursor_ordinal, processed_count, conflict_count, lease_owner,
	//         lease_until, last_error_code, created_at, started_at, updated_at, completed_at
	//  FROM key_rotation_jobs
	//  WHERE job_id = $1
	GetKeyRotationJob(ctx context.Context, arg GetKeyRotationJobParams) (KeyRotationJob, error)
	//GetLatestAckedOutboxEventByType
	//
	//  SELECT event.event_sequence, event.event_id, event.event_type, event.aggregate_type,
	//         event.aggregate_id, event.payload, event.created_at, event.available_at
	//  FROM outbox_events AS event
	//  JOIN outbox_consumers AS consumer
	//    ON consumer.consumer_id = $1
	//  WHERE event.event_sequence <= consumer.last_acked_sequence
	//    AND event.event_type = $2
	//    AND event.event_type = ANY(consumer.subscriptions)
	//  ORDER BY event.event_sequence DESC
	//  LIMIT 1
	GetLatestAckedOutboxEventByType(ctx context.Context, arg GetLatestAckedOutboxEventByTypeParams) (OutboxEvent, error)
	//GetOutboxConsumer
	//
	//  SELECT consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//         retry_count, next_attempt_at, last_error_code, created_at, updated_at
	//  FROM outbox_consumers
	//  WHERE consumer_id = $1
	GetOutboxConsumer(ctx context.Context, arg GetOutboxConsumerParams) (OutboxConsumer, error)
	//GetOutboxEventByID
	//
	//  SELECT event_sequence, event_id, event_type, aggregate_type, aggregate_id,
	//         payload, created_at, available_at
	//  FROM outbox_events
	//  WHERE event_id = $1
	GetOutboxEventByID(ctx context.Context, arg GetOutboxEventByIDParams) (OutboxEvent, error)
	//GetPartyRoomByCodeForShare
	//
	//  SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
	//      participant_admission, spectator_admission, active_session_id, active_game_id,
	//      room_version, membership_version, created_at, updated_at
	//  FROM party_rooms
	//  WHERE room_code = $1
	//  FOR SHARE
	GetPartyRoomByCodeForShare(ctx context.Context, arg GetPartyRoomByCodeForShareParams) (PartyRoom, error)
	//GetPartyRoomForShare
	//
	//  SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
	//      participant_admission, spectator_admission, active_session_id, active_game_id,
	//      room_version, membership_version, created_at, updated_at
	//  FROM party_rooms
	//  WHERE room_id = $1
	//  FOR SHARE
	GetPartyRoomForShare(ctx context.Context, arg GetPartyRoomForShareParams) (PartyRoom, error)
	//GetPartyRoomForUpdate
	//
	//  SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
	//      participant_admission, spectator_admission, active_session_id, active_game_id,
	//      room_version, membership_version, created_at, updated_at
	//  FROM party_rooms
	//  WHERE room_id = $1
	//  FOR UPDATE
	GetPartyRoomForUpdate(ctx context.Context, arg GetPartyRoomForUpdateParams) (PartyRoom, error)
	//GetPendingAdminTotpEnrollmentForUpdate
	//
	//  SELECT enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//         operation_id, created_at, expires_at, activated_at, disabled_at
	//  FROM admin_totp_enrollments
	//  WHERE admin_id = $1
	//    AND status = 'pending'
	//  FOR UPDATE
	GetPendingAdminTotpEnrollmentForUpdate(ctx context.Context, arg GetPendingAdminTotpEnrollmentForUpdateParams) (AdminTotpEnrollment, error)
	//GetProfileExportContextForUpdate
	//
	//  SELECT export_id, created_by_admin_id, filter_digest, requested_fields, schema_version,
	//         item_count, status, reason, created_at, expires_at, completed_at, aborted_at, expired_at
	//  FROM profile_export_contexts
	//  WHERE export_id = $1
	//  FOR UPDATE
	GetProfileExportContextForUpdate(ctx context.Context, arg GetProfileExportContextForUpdateParams) (ProfileExportContext, error)
	//GetRoomMemberRole
	//
	//  SELECT role
	//  FROM room_members
	//  WHERE room_id = $1
	//    AND user_id = $2
	GetRoomMemberRole(ctx context.Context, arg GetRoomMemberRoleParams) (string, error)
	//GetSecretOperationResultByIDForUpdate
	//
	//  SELECT result_id, operation_scope, actor_or_challenge_id, operation_id, request_digest,
	//         result_type, result_version, ciphertext, nonce, wrapped_data_key, key_version,
	//         status, secret_expires_at, confirmed_at, completed_at, tombstone_expires_at
	//  FROM secret_operation_results
	//  WHERE result_id = $1
	//  FOR UPDATE
	GetSecretOperationResultByIDForUpdate(ctx context.Context, arg GetSecretOperationResultByIDForUpdateParams) (SecretOperationResult, error)
	//GetSecretOperationResultByOperation
	//
	//  SELECT result_id, operation_scope, actor_or_challenge_id, operation_id, request_digest,
	//         result_type, result_version, ciphertext, nonce, wrapped_data_key, key_version,
	//         status, secret_expires_at, confirmed_at, completed_at, tombstone_expires_at
	//  FROM secret_operation_results
	//  WHERE operation_scope = $1
	//    AND actor_or_challenge_id = $2
	//    AND operation_id = $3
	GetSecretOperationResultByOperation(ctx context.Context, arg GetSecretOperationResultByOperationParams) (SecretOperationResult, error)
	//GetSecretOperationResultByOperationForUpdate
	//
	//  SELECT result_id, operation_scope, actor_or_challenge_id, operation_id, request_digest,
	//         result_type, result_version, ciphertext, nonce, wrapped_data_key, key_version,
	//         status, secret_expires_at, confirmed_at, completed_at, tombstone_expires_at
	//  FROM secret_operation_results
	//  WHERE operation_scope = $1
	//    AND actor_or_challenge_id = $2
	//    AND operation_id = $3
	//  FOR UPDATE
	GetSecretOperationResultByOperationForUpdate(ctx context.Context, arg GetSecretOperationResultByOperationForUpdateParams) (SecretOperationResult, error)
	//GetSingletonAdminForUpdate
	//
	//  SELECT singleton_id, admin_id, username, status, password_hash, password_algorithm,
	//         password_parameters, password_version, admin_version, last_accepted_totp_step,
	//         created_at, updated_at
	//  FROM admin_accounts
	//  WHERE singleton_id = 1
	//  FOR UPDATE
	GetSingletonAdminForUpdate(ctx context.Context) (AdminAccount, error)
	//GetUserByID
	//
	//  SELECT user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	//  FROM users
	//  WHERE user_id = $1
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	//GetUserByUsernameKey
	//
	//  SELECT u.user_id, u.status, u.username, u.current_username_key, u.username_changed_at, u.created_at, u.updated_at
	//  FROM username_claims AS claim
	//  JOIN users AS u ON u.user_id = claim.owner_user_id
	//  WHERE claim.username_key = $1
	//    AND claim.status = 'active'
	//    AND u.current_username_key = claim.username_key
	GetUserByUsernameKey(ctx context.Context, arg GetUserByUsernameKeyParams) (User, error)
	//GetUserForUpdate
	//
	//  SELECT user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	//  FROM users
	//  WHERE user_id = $1
	//  FOR UPDATE
	GetUserForUpdate(ctx context.Context, arg GetUserForUpdateParams) (User, error)
	//GetUserProfile
	//
	//  SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//         profile_version, real_name_updated_at, real_name_updated_by
	//  FROM user_profiles
	//  WHERE user_id = $1
	GetUserProfile(ctx context.Context, arg GetUserProfileParams) (UserProfile, error)
	//GetUserProfileForUpdate
	//
	//  SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//         profile_version, real_name_updated_at, real_name_updated_by
	//  FROM user_profiles
	//  WHERE user_id = $1
	//  FOR UPDATE
	GetUserProfileForUpdate(ctx context.Context, arg GetUserProfileForUpdateParams) (UserProfile, error)
	//GetUserRecoveryAttemptBySelector
	//
	//  SELECT recovery_attempt_id, grant_selector, grant_secret_hash, grant_key_version,
	//         user_id, recovery_credential_id, recovery_credential_version, assisted_grant_id,
	//         challenge_id, origin_hash, purpose, request_digest, attempt_count, max_attempts,
	//         status, created_at, expires_at, consumed_at, revoked_at, result_id
	//  FROM user_recovery_attempts
	//  WHERE grant_selector = $1
	GetUserRecoveryAttemptBySelector(ctx context.Context, arg GetUserRecoveryAttemptBySelectorParams) (UserRecoveryAttempt, error)
	//GetUserRecoveryAttemptForUpdate
	//
	//  WITH selected_attempt AS MATERIALIZED (
	//      SELECT selected.recovery_attempt_id, selected.user_id
	//      FROM user_recovery_attempts AS selected
	//      WHERE selected.grant_selector = $1
	//  ),
	//  locked_user AS MATERIALIZED (
	//      SELECT users.user_id
	//      FROM users
	//      JOIN selected_attempt AS selected ON selected.user_id = users.user_id
	//      FOR UPDATE OF users
	//  ),
	//  locked_attempt AS MATERIALIZED (
	//      SELECT attempts.recovery_attempt_id, attempts.grant_selector, attempts.grant_secret_hash, attempts.grant_key_version, attempts.user_id, attempts.recovery_credential_id, attempts.recovery_credential_version, attempts.assisted_grant_id, attempts.challenge_id, attempts.origin_hash, attempts.purpose, attempts.request_digest, attempts.attempt_count, attempts.max_attempts, attempts.status, attempts.created_at, attempts.expires_at, attempts.consumed_at, attempts.revoked_at, attempts.result_id
	//      FROM user_recovery_attempts AS attempts
	//      JOIN selected_attempt AS selected ON selected.recovery_attempt_id = attempts.recovery_attempt_id
	//      JOIN locked_user AS users ON users.user_id = attempts.user_id
	//      FOR UPDATE OF attempts
	//  )
	//  SELECT recovery_attempt_id, grant_selector, grant_secret_hash, grant_key_version,
	//         user_id, recovery_credential_id, recovery_credential_version, assisted_grant_id,
	//         challenge_id, origin_hash, purpose, request_digest, attempt_count, max_attempts,
	//         status, created_at, expires_at, consumed_at, revoked_at, result_id
	//  FROM locked_attempt
	GetUserRecoveryAttemptForUpdate(ctx context.Context, arg GetUserRecoveryAttemptForUpdateParams) (GetUserRecoveryAttemptForUpdateRow, error)
	//GetUserRecoveryCredentialBySelector
	//
	//  SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
	//         created_at, consumed_at, revoked_at, revoke_reason
	//  FROM user_recovery_credentials
	//  WHERE selector = $1
	GetUserRecoveryCredentialBySelector(ctx context.Context, arg GetUserRecoveryCredentialBySelectorParams) (UserRecoveryCredential, error)
	//GetUserRecoveryCredentialForUpdate
	//
	//  SELECT recovery_credential_id, user_id, selector, secret_hash, version, status,
	//         created_at, consumed_at, revoked_at, revoke_reason
	//  FROM user_recovery_credentials
	//  WHERE recovery_credential_id = $1
	//    AND user_id = $2
	//    AND version = $3
	//  FOR UPDATE
	GetUserRecoveryCredentialForUpdate(ctx context.Context, arg GetUserRecoveryCredentialForUpdateParams) (UserRecoveryCredential, error)
	//GetUsernameClaimForUpdate
	//
	//  SELECT username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
	//  FROM username_claims
	//  WHERE username_key = $1
	//  FOR UPDATE
	GetUsernameClaimForUpdate(ctx context.Context, arg GetUsernameClaimForUpdateParams) (UsernameClaim, error)
	//InsertGameSystemOperationPending
	//
	//  INSERT INTO game_system_operations (
	//      session_id, operation_id, source_kind, source_event_id, requested_by_user_id,
	//      logical_digest, status, created_at
	//  ) VALUES (
	//      $1, $2, $3, $4,
	//      $5, $6, 'pending', $7
	//  )
	//  ON CONFLICT DO NOTHING
	//  RETURNING session_id, operation_id, source_kind, source_event_id, requested_by_user_id,
	//      logical_digest, status, result_code, result_digest, committed_state_version,
	//      batch_id, created_at, completed_at
	InsertGameSystemOperationPending(ctx context.Context, arg InsertGameSystemOperationPendingParams) (GameSystemOperation, error)
	//ListAdminTotpEnrollmentsForKeyRotation
	//
	//  SELECT enrollment_id, admin_id, ciphertext, nonce, key_version, status, admin_version,
	//         operation_id, created_at, expires_at, activated_at, disabled_at
	//  FROM admin_totp_enrollments
	//  WHERE key_version = $1
	//    AND status IN ('pending', 'active')
	//    AND ($2::uuid IS NULL OR enrollment_id > $2::uuid)
	//  ORDER BY enrollment_id
	//  LIMIT $3
	ListAdminTotpEnrollmentsForKeyRotation(ctx context.Context, arg ListAdminTotpEnrollmentsForKeyRotationParams) ([]AdminTotpEnrollment, error)
	//ListAuditEvents
	//
	//  SELECT chain_id, sequence, event_id, previous_hash, canonical_event, event_hash,
	//         signature, signing_key_version, created_at
	//  FROM audit_events_redacted
	//  WHERE chain_id = $1
	//    AND sequence > $2
	//  ORDER BY sequence
	//  LIMIT $3
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEventsRedacted, error)
	//ListDueGameSessionTimerCandidates
	//
	//  SELECT timer.session_id, timer.timer_id, timer.expected_state_version, timer.due_at,
	//      timer.message_type, timer.schema_version, timer.payload
	//  FROM game_session_timers AS timer
	//  JOIN game_sessions AS session USING (session_id)
	//  WHERE session.status = 'active'
	//    AND timer.due_at <= $1
	//  ORDER BY timer.due_at, timer.session_id, timer.timer_id
	//  LIMIT $2
	ListDueGameSessionTimerCandidates(ctx context.Context, arg ListDueGameSessionTimerCandidatesParams) ([]GameSessionTimer, error)
	//ListGameSessionEventBatchesAfter
	//
	//  SELECT batch_id, session_id, state_version, ownership_epoch, cause, actor_user_id,
	//      action_id, timer_id, system_operation_id, system_source_kind, system_source_event_id,
	//      system_requested_by_user_id, system_request_digest,
	//      executed_at, random_seed, allocated_ids, input_message_type,
	//      input_schema_version, input_payload, event_count, committed_at
	//  FROM game_session_event_batches
	//  WHERE session_id = $1
	//    AND state_version > $2
	//  ORDER BY state_version
	//  LIMIT $3
	ListGameSessionEventBatchesAfter(ctx context.Context, arg ListGameSessionEventBatchesAfterParams) ([]ListGameSessionEventBatchesAfterRow, error)
	//ListGameSessionEvents
	//
	//  SELECT batch_id, event_ordinal, message_type, schema_version, payload
	//  FROM game_session_events
	//  WHERE batch_id = $1
	//  ORDER BY event_ordinal
	ListGameSessionEvents(ctx context.Context, arg ListGameSessionEventsParams) ([]GameSessionEvent, error)
	//ListGameSessionParticipants
	//
	//  SELECT session_id, user_id, seat_index
	//  FROM game_session_participants
	//  WHERE session_id = $1
	//  ORDER BY seat_index, user_id
	ListGameSessionParticipants(ctx context.Context, arg ListGameSessionParticipantsParams) ([]GameSessionParticipant, error)
	//ListGameSessionTimers
	//
	//  SELECT session_id, timer_id, expected_state_version, due_at, message_type, schema_version, payload
	//  FROM game_session_timers
	//  WHERE session_id = $1
	//  ORDER BY timer_id
	ListGameSessionTimers(ctx context.Context, arg ListGameSessionTimersParams) ([]GameSessionTimer, error)
	//ListOutboxEventsForConsumer
	//
	//  WITH consumer_state AS MATERIALIZED (
	//      SELECT subscriptions, last_acked_sequence
	//      FROM outbox_consumers
	//      WHERE consumer_id = $1
	//        AND lease_owner = $2
	//        AND lease_until > pg_catalog.clock_timestamp()
	//        AND (next_attempt_at IS NULL OR next_attempt_at <= pg_catalog.clock_timestamp())
	//        AND $3::timestamptz <= pg_catalog.clock_timestamp()
	//  ), candidates AS MATERIALIZED (
	//      SELECT event.event_sequence, event.event_id, event.event_type, event.aggregate_type,
	//             event.aggregate_id, event.payload, event.created_at, event.available_at
	//      FROM outbox_events AS event
	//      CROSS JOIN consumer_state AS consumer
	//      WHERE event.event_sequence > consumer.last_acked_sequence
	//        AND event.event_type = ANY(consumer.subscriptions)
	//      ORDER BY event.event_sequence
	//      LIMIT $4
	//  )
	//  SELECT event_sequence, event_id, event_type, aggregate_type, aggregate_id,
	//         payload, created_at, available_at
	//  FROM candidates AS event
	//  WHERE event.available_at <= pg_catalog.clock_timestamp()
	//    AND NOT EXISTS (
	//        SELECT 1
	//        FROM candidates AS earlier
	//        WHERE earlier.event_sequence < event.event_sequence
	//          AND earlier.available_at > pg_catalog.clock_timestamp()
	//    )
	//  ORDER BY event.event_sequence
	ListOutboxEventsForConsumer(ctx context.Context, arg ListOutboxEventsForConsumerParams) ([]ListOutboxEventsForConsumerRow, error)
	//ListPIIKeyVersionsWithReferences
	//
	//  SELECT DISTINCT real_name_key_version
	//  FROM (
	//      SELECT real_name_key_version FROM user_profiles
	//      UNION ALL
	//      SELECT real_name_key_version FROM profile_export_items
	//  ) AS key_refs
	//  WHERE real_name_key_version IS NOT NULL
	//  ORDER BY real_name_key_version
	ListPIIKeyVersionsWithReferences(ctx context.Context) ([]int32, error)
	//ListProfileExportItems
	//
	//  SELECT export_id, ordinal, user_id, username, profile_version,
	//         real_name_ciphertext, real_name_nonce, real_name_key_version
	//  FROM profile_export_items
	//  WHERE export_id = $1
	//    AND ordinal > $2
	//  ORDER BY ordinal
	//  LIMIT $3
	ListProfileExportItems(ctx context.Context, arg ListProfileExportItemsParams) ([]ProfileExportItem, error)
	//ListProfileExportItemsForKeyRotation
	//
	//  SELECT export_id, ordinal, user_id, profile_version, real_name_ciphertext,
	//         real_name_nonce, real_name_key_version
	//  FROM profile_export_items
	//  WHERE real_name_key_version = $1
	//    AND (
	//        $2::uuid IS NULL
	//        OR (export_id, ordinal) > (
	//            $2::uuid,
	//            $3::bigint
	//        )
	//    )
	//  ORDER BY export_id, ordinal
	//  LIMIT $4
	ListProfileExportItemsForKeyRotation(ctx context.Context, arg ListProfileExportItemsForKeyRotationParams) ([]ListProfileExportItemsForKeyRotationRow, error)
	//ListProfileExportSources
	//
	//  SELECT users.user_id,
	//         users.username,
	//         user_profiles.profile_version,
	//         user_profiles.real_name_ciphertext,
	//         user_profiles.real_name_nonce,
	//         user_profiles.real_name_key_version
	//  FROM users
	//  LEFT JOIN user_profiles ON user_profiles.user_id = users.user_id
	//  WHERE (cardinality($1::uuid[]) = 0 OR users.user_id = ANY($1::uuid[]))
	//    AND (cardinality($2::text[]) = 0 OR users.status = ANY($2::text[]))
	//  ORDER BY users.user_id
	ListProfileExportSources(ctx context.Context, arg ListProfileExportSourcesParams) ([]ListProfileExportSourcesRow, error)
	//ListPublicRoomCards
	//
	//  SELECT room.room_id,
	//      host.username AS host_username,
	//      room.status,
	//      room.participant_capacity,
	//      counts.participant_count,
	//      counts.spectator_count,
	//      counts.waiting_count,
	//      room.participant_admission,
	//      room.spectator_admission,
	//      room.active_game_id,
	//      viewer.role AS viewer_role,
	//      viewer.requested_role AS viewer_requested_role,
	//      room.updated_at
	//  FROM party_rooms AS room
	//  JOIN users AS host
	//    ON host.user_id = room.host_user_id
	//   AND host.status = 'active'
	//  JOIN LATERAL (
	//      SELECT count(*) FILTER (WHERE member.role = 'participant') AS participant_count,
	//          count(*) FILTER (WHERE member.role = 'spectator') AS spectator_count,
	//          count(*) FILTER (WHERE member.role = 'waiting') AS waiting_count
	//      FROM room_members AS member
	//      WHERE member.room_id = room.room_id
	//  ) AS counts ON true
	//  LEFT JOIN room_members AS viewer
	//    ON viewer.room_id = room.room_id
	//   AND viewer.user_id = $1
	//  WHERE room.visibility = 'public'
	//    AND room.status <> 'closed'
	//    AND (
	//        (NOT $2::boolean AND NOT $3::boolean)
	//        OR ($2::boolean AND room.status = 'lobby')
	//        OR ($3::boolean AND room.status = 'playing')
	//    )
	//    AND ($4::text = '' OR room.active_game_id = $4::text)
	//    AND (
	//        NOT $5::boolean
	//        OR (
	//            room.status = 'lobby'
	//            AND room.participant_admission IN ('open', 'approval')
	//            AND counts.participant_count < room.participant_capacity
	//        )
	//    )
	//    AND (
	//        NOT $6::boolean
	//        OR (room.updated_at, room.room_id) < ($7::timestamptz, $8::uuid)
	//    )
	//  ORDER BY room.updated_at DESC, room.room_id DESC
	//  LIMIT $9
	ListPublicRoomCards(ctx context.Context, arg ListPublicRoomCardsParams) ([]ListPublicRoomCardsRow, error)
	//ListRoomMembers
	//
	//  SELECT room_id, user_id, role, requested_role, seat_index, joined_at, last_seen_at
	//  FROM room_members
	//  WHERE room_id = $1
	//  ORDER BY joined_at, user_id
	ListRoomMembers(ctx context.Context, arg ListRoomMembersParams) ([]RoomMember, error)
	//ListTotpKeyVersionsWithReferences
	//
	//  SELECT DISTINCT key_version
	//  FROM admin_totp_enrollments
	//  WHERE key_version IS NOT NULL
	//    AND status IN ('pending', 'active')
	//  ORDER BY key_version
	ListTotpKeyVersionsWithReferences(ctx context.Context) ([]int32, error)
	//ListUserDeviceCredentials
	//
	//  SELECT credential_id, user_id, generation, label, created_at, last_seen_at, rotated_at,
	//         idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
	//  FROM device_credentials
	//  WHERE user_id = $1
	//    AND ($2::boolean OR revoked_at IS NULL)
	//    AND (created_at, credential_id) > (
	//        $3::timestamptz,
	//        $4::uuid
	//    )
	//  ORDER BY created_at, credential_id
	//  LIMIT $5
	ListUserDeviceCredentials(ctx context.Context, arg ListUserDeviceCredentialsParams) ([]ListUserDeviceCredentialsRow, error)
	//ListUserProfilesForKeyRotation
	//
	//  SELECT user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//         profile_version, real_name_updated_at, real_name_updated_by
	//  FROM user_profiles
	//  WHERE real_name_key_version = $1
	//    AND ($2::uuid IS NULL OR user_id > $2::uuid)
	//  ORDER BY user_id
	//  LIMIT $3
	ListUserProfilesForKeyRotation(ctx context.Context, arg ListUserProfilesForKeyRotationParams) ([]UserProfile, error)
	//ReadAuditAnchor
	//
	//  WITH result AS (
	//      SELECT pg_catalog.to_jsonb(function_row) AS payload
	//      FROM read_audit_anchor($1::text, $2::bigint) AS function_row
	//  )
	//  SELECT decode(pg_catalog.substring(result.payload ->> 'event_hash', 3), 'hex') AS event_hash,
	//         (result.payload ->> 'created_at')::timestamptz AS created_at
	//  FROM result
	ReadAuditAnchor(ctx context.Context, arg ReadAuditAnchorParams) (ReadAuditAnchorRow, error)
	//ReadAuditHead
	//
	//  WITH result AS (
	//      SELECT pg_catalog.to_jsonb(function_row) AS payload
	//      FROM read_audit_head($1) AS function_row
	//  )
	//  SELECT (result.payload ->> 'sequence')::bigint AS sequence,
	//         decode(pg_catalog.substring(result.payload ->> 'head_hash', 3), 'hex') AS head_hash,
	//         (result.payload ->> 'updated_at')::timestamptz AS updated_at
	//  FROM result
	ReadAuditHead(ctx context.Context, arg ReadAuditHeadParams) (ReadAuditHeadRow, error)
	//ReadCheckpointConsumerSequence
	//
	//  SELECT read_checkpoint_consumer_sequence()
	ReadCheckpointConsumerSequence(ctx context.Context) (int64, error)
	//RecordAdminAssistedRecoveryFailureCAS
	//
	//  UPDATE admin_assisted_recovery_grants
	//  SET attempt_count = $1,
	//      status = $2
	//  WHERE assisted_grant_id = $3
	//    AND status = 'active'
	//    AND attempt_count = $4
	//  RETURNING assisted_grant_id, user_id, selector, secret_hash, purpose, status,
	//            attempt_count, max_attempts, created_by_admin_id, created_at, expires_at,
	//            consumed_at, revoked_at, result_id
	RecordAdminAssistedRecoveryFailureCAS(ctx context.Context, arg RecordAdminAssistedRecoveryFailureCASParams) (AdminAssistedRecoveryGrant, error)
	//RecordAdminChallengeFailureCAS
	//
	//  UPDATE admin_challenges
	//  SET attempt_count = attempt_count + 1
	//  WHERE challenge_id = $1
	//    AND status = 'active'
	//    AND expires_at > $2
	//    AND attempt_count < max_attempts
	//  RETURNING challenge_id, attempt_count, max_attempts, status, expires_at
	RecordAdminChallengeFailureCAS(ctx context.Context, arg RecordAdminChallengeFailureCASParams) (RecordAdminChallengeFailureCASRow, error)
	//RecordAnonymousChallengeFailureCAS
	//
	//  UPDATE anonymous_challenges
	//  SET attempt_count = attempt_count + 1
	//  WHERE challenge_id = $1
	//    AND consumed_at IS NULL
	//    AND expires_at > $2
	//    AND attempt_count < max_attempts
	//  RETURNING challenge_id, attempt_count, max_attempts, expires_at
	RecordAnonymousChallengeFailureCAS(ctx context.Context, arg RecordAnonymousChallengeFailureCASParams) (RecordAnonymousChallengeFailureCASRow, error)
	//RecordOutboxConsumerRetryCAS
	//
	//  UPDATE outbox_consumers
	//  SET retry_count = $1,
	//      next_attempt_at = $2,
	//      last_error_code = $3,
	//      updated_at = $4
	//  WHERE consumer_id = $5
	//    AND lease_owner = $6
	//    AND lease_until = $7
	//    AND last_acked_sequence = $8
	//    AND retry_count = $9
	//    AND next_attempt_at IS NOT DISTINCT FROM $10
	//    AND last_error_code IS NOT DISTINCT FROM $11
	//    AND updated_at = $12
	//    AND lease_until > pg_catalog.clock_timestamp()
	//  RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//            retry_count, next_attempt_at, last_error_code, created_at, updated_at
	RecordOutboxConsumerRetryCAS(ctx context.Context, arg RecordOutboxConsumerRetryCASParams) (OutboxConsumer, error)
	//RecordUserRecoveryAttemptFailureCAS
	//
	//  UPDATE user_recovery_attempts
	//  SET attempt_count = $1,
	//      status = $2
	//  WHERE recovery_attempt_id = $3
	//    AND status = 'active'
	//    AND attempt_count = $4
	//  RETURNING recovery_attempt_id, grant_selector, grant_secret_hash, grant_key_version,
	//            user_id, recovery_credential_id, recovery_credential_version, assisted_grant_id,
	//            challenge_id, origin_hash, purpose, request_digest, attempt_count, max_attempts,
	//            status, created_at, expires_at, consumed_at, revoked_at, result_id
	RecordUserRecoveryAttemptFailureCAS(ctx context.Context, arg RecordUserRecoveryAttemptFailureCASParams) (UserRecoveryAttempt, error)
	//ReleaseKeyRotationJobLeaseCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET lease_owner = NULL,
	//      lease_until = NULL,
	//      updated_at = $1
	//  WHERE job_id = $2
	//    AND status = 'running'
	//    AND lease_owner = $3
	//    AND lease_until > $1
	//  RETURNING job_id, status, cursor_scope, cursor_id, cursor_ordinal, updated_at
	ReleaseKeyRotationJobLeaseCAS(ctx context.Context, arg ReleaseKeyRotationJobLeaseCASParams) (ReleaseKeyRotationJobLeaseCASRow, error)
	//ReleaseOutboxConsumerLeaseCAS
	//
	//  UPDATE outbox_consumers
	//  SET lease_owner = NULL,
	//      lease_until = NULL,
	//      updated_at = $1
	//  WHERE consumer_id = $2
	//    AND lease_owner = $3
	//    AND lease_until = $4
	//    AND last_acked_sequence = $5
	//    AND retry_count = $6
	//    AND next_attempt_at IS NOT DISTINCT FROM $7
	//    AND last_error_code IS NOT DISTINCT FROM $8
	//    AND updated_at = $9
	//    AND lease_until > pg_catalog.clock_timestamp()
	//  RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//            retry_count, next_attempt_at, last_error_code, created_at, updated_at
	ReleaseOutboxConsumerLeaseCAS(ctx context.Context, arg ReleaseOutboxConsumerLeaseCASParams) (OutboxConsumer, error)
	//RenewKeyRotationJobLeaseCAS
	//
	//  UPDATE key_rotation_jobs
	//  SET lease_until = $1,
	//      updated_at = $2
	//  WHERE job_id = $3
	//    AND status = 'running'
	//    AND lease_owner = $4
	//    AND lease_until > $2
	//  RETURNING job_id, status, cursor_scope, cursor_id, cursor_ordinal, lease_owner,
	//            lease_until, updated_at
	RenewKeyRotationJobLeaseCAS(ctx context.Context, arg RenewKeyRotationJobLeaseCASParams) (RenewKeyRotationJobLeaseCASRow, error)
	//RenewOutboxConsumerLeaseCAS
	//
	//  UPDATE outbox_consumers
	//  SET lease_until = $1,
	//      updated_at = $2
	//  WHERE consumer_id = $3
	//    AND lease_owner = $4
	//    AND lease_until = $5
	//    AND last_acked_sequence = $6
	//    AND retry_count = $7
	//    AND next_attempt_at IS NOT DISTINCT FROM $8
	//    AND last_error_code IS NOT DISTINCT FROM $9
	//    AND updated_at = $10
	//    AND lease_until > pg_catalog.clock_timestamp()
	//    AND $1 > pg_catalog.clock_timestamp()
	//  RETURNING consumer_id, subscriptions, last_acked_sequence, lease_owner, lease_until,
	//            retry_count, next_attempt_at, last_error_code, created_at, updated_at
	RenewOutboxConsumerLeaseCAS(ctx context.Context, arg RenewOutboxConsumerLeaseCASParams) (OutboxConsumer, error)
	//ReserveUsernameClaimCAS
	//
	//  UPDATE username_claims
	//  SET status = 'reserved',
	//      reserved_until = $1,
	//      updated_at = $2
	//  WHERE username_key = $3
	//    AND owner_user_id = $4
	//    AND status = 'active'
	//  RETURNING username_key, display_username, status, owner_user_id, reserved_until, created_at, updated_at
	ReserveUsernameClaimCAS(ctx context.Context, arg ReserveUsernameClaimCASParams) (UsernameClaim, error)
	//ResetAdminAccount
	//
	//  WITH result AS (
	//      SELECT pg_catalog.to_jsonb(function_row) AS payload
	//      FROM reset_admin_account(
	//          $1,
	//          $2,
	//          $3,
	//          $4,
	//          $5,
	//          $6,
	//          $7,
	//          $8,
	//          $9,
	//          $10,
	//          $11
	//      ) AS function_row
	//  )
	//  SELECT (result.payload ->> 'appended_sequence')::bigint AS appended_sequence,
	//         decode(pg_catalog.substring(result.payload ->> 'appended_hash', 3), 'hex') AS appended_hash
	//  FROM result
	ResetAdminAccount(ctx context.Context, arg ResetAdminAccountParams) (ResetAdminAccountRow, error)
	//RevokeActiveAdminAssistedRecoveryGrantsForUser
	//
	//  UPDATE admin_assisted_recovery_grants
	//  SET status = 'revoked',
	//      revoked_at = $1
	//  WHERE user_id = $2
	//    AND assisted_grant_id <> $3
	//    AND status = 'active'
	//  RETURNING assisted_grant_id
	RevokeActiveAdminAssistedRecoveryGrantsForUser(ctx context.Context, arg RevokeActiveAdminAssistedRecoveryGrantsForUserParams) ([]pgtype.UUID, error)
	//RevokeAdminChallenges
	//
	//  UPDATE admin_challenges
	//  SET status = 'revoked',
	//      revoked_at = $1
	//  WHERE admin_id = $2
	//    AND status = 'active'
	RevokeAdminChallenges(ctx context.Context, arg RevokeAdminChallengesParams) (int64, error)
	//RevokeAdminRecoveryCodeSet
	//
	//  UPDATE admin_recovery_codes
	//  SET status = 'revoked',
	//      revoked_at = $1
	//  WHERE admin_id = $2
	//    AND set_version = $3
	//    AND status = 'active'
	RevokeAdminRecoveryCodeSet(ctx context.Context, arg RevokeAdminRecoveryCodeSetParams) (int64, error)
	//RevokeAdminSessionCAS
	//
	//  UPDATE admin_sessions
	//  SET revoked_at = $1,
	//      revoke_reason = $2
	//  WHERE session_id = $3
	//    AND revoked_at IS NULL
	//  RETURNING session_id, revoked_at, revoke_reason
	RevokeAdminSessionCAS(ctx context.Context, arg RevokeAdminSessionCASParams) (RevokeAdminSessionCASRow, error)
	//RevokeAllAdminRecoveryCodeSets
	//
	//  UPDATE admin_recovery_codes
	//  SET status = 'revoked',
	//      revoked_at = $1
	//  WHERE admin_id = $2
	//    AND status = 'active'
	RevokeAllAdminRecoveryCodeSets(ctx context.Context, arg RevokeAllAdminRecoveryCodeSetsParams) (int64, error)
	//RevokeAllAdminSessions
	//
	//  UPDATE admin_sessions
	//  SET revoked_at = $1,
	//      revoke_reason = $2
	//  WHERE admin_id = $3
	//    AND revoked_at IS NULL
	RevokeAllAdminSessions(ctx context.Context, arg RevokeAllAdminSessionsParams) (int64, error)
	//RevokeDeviceCredentialCAS
	//
	//  UPDATE device_credentials
	//  SET revoked_at = $1,
	//      revoke_reason = $2,
	//      generation = generation + 1
	//  WHERE credential_id = $3
	//    AND user_id = $4
	//    AND generation = $5
	//    AND revoked_at IS NULL
	//  RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
	//            previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
	//            created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
	//            revoked_at, revoke_reason
	RevokeDeviceCredentialCAS(ctx context.Context, arg RevokeDeviceCredentialCASParams) (DeviceCredential, error)
	//RevokeOtherDeviceCredentialsForRecovery
	//
	//  UPDATE device_credentials
	//  SET revoked_at = $1,
	//      revoke_reason = 'recovery',
	//      generation = generation + 1
	//  WHERE user_id = $2
	//    AND credential_id <> $3
	//    AND revoked_at IS NULL
	//  RETURNING credential_id, user_id, generation, label, created_at, last_seen_at, rotated_at,
	//            idle_expires_at, absolute_expires_at, revoked_at, revoke_reason
	RevokeOtherDeviceCredentialsForRecovery(ctx context.Context, arg RevokeOtherDeviceCredentialsForRecoveryParams) ([]RevokeOtherDeviceCredentialsForRecoveryRow, error)
	//RevokeUserRecoveryAttemptCAS
	//
	//  UPDATE user_recovery_attempts
	//  SET status = 'revoked',
	//      revoked_at = $1
	//  WHERE recovery_attempt_id = $2
	//    AND status = 'active'
	//    AND attempt_count = $3
	//  RETURNING recovery_attempt_id, grant_selector, grant_secret_hash, grant_key_version,
	//            user_id, recovery_credential_id, recovery_credential_version, assisted_grant_id,
	//            challenge_id, origin_hash, purpose, request_digest, attempt_count, max_attempts,
	//            status, created_at, expires_at, consumed_at, revoked_at, result_id
	RevokeUserRecoveryAttemptCAS(ctx context.Context, arg RevokeUserRecoveryAttemptCASParams) (UserRecoveryAttempt, error)
	//RevokeUserRecoveryCredentialCAS
	//
	//  UPDATE user_recovery_credentials
	//  SET status = 'revoked',
	//      revoked_at = $1,
	//      revoke_reason = $2
	//  WHERE recovery_credential_id = $3
	//    AND user_id = $4
	//    AND version = $5
	//    AND status = 'active'
	//  RETURNING recovery_credential_id, user_id, selector, secret_hash, version, status,
	//            created_at, consumed_at, revoked_at, revoke_reason
	RevokeUserRecoveryCredentialCAS(ctx context.Context, arg RevokeUserRecoveryCredentialCASParams) (UserRecoveryCredential, error)
	//RotateAdminTotpEnrollmentCiphertextCAS
	//
	//  UPDATE admin_totp_enrollments
	//  SET ciphertext = $1,
	//      nonce = $2,
	//      key_version = $3
	//  WHERE enrollment_id = $4
	//    AND admin_version = $5
	//    AND key_version = $6
	//    AND status IN ('pending', 'active')
	//  RETURNING enrollment_id, admin_id, key_version, status, admin_version
	RotateAdminTotpEnrollmentCiphertextCAS(ctx context.Context, arg RotateAdminTotpEnrollmentCiphertextCASParams) (RotateAdminTotpEnrollmentCiphertextCASRow, error)
	//RotateDeviceCredentialCAS
	//
	//  UPDATE device_credentials
	//  SET previous_secret_hash = secret_hash,
	//      previous_secret_key_version = secret_key_version,
	//      previous_valid_until = $1,
	//      secret_hash = $2,
	//      secret_key_version = $3,
	//      csrf_hash = $4,
	//      generation = generation + 1,
	//      last_seen_at = $5,
	//      rotated_at = $5,
	//      idle_expires_at = $6
	//  WHERE credential_id = $7
	//    AND user_id = $8
	//    AND generation = $9
	//    AND secret_hash = $10
	//    AND secret_key_version = $11
	//    AND previous_secret_hash IS NOT DISTINCT FROM $12::bytea
	//    AND previous_secret_key_version IS NOT DISTINCT FROM $13::integer
	//    AND previous_valid_until IS NOT DISTINCT FROM $14::timestamptz
	//    AND csrf_hash = $15
	//    AND last_seen_at = $16
	//    AND rotated_at = $17
	//    AND idle_expires_at = $18
	//    AND absolute_expires_at = $19
	//    AND revoked_at IS NULL
	//    AND absolute_expires_at > $5
	//  RETURNING credential_id, user_id, secret_hash, secret_key_version, previous_secret_hash,
	//            previous_secret_key_version, previous_valid_until, csrf_hash, generation, label,
	//            created_at, last_seen_at, rotated_at, idle_expires_at, absolute_expires_at,
	//            revoked_at, revoke_reason
	RotateDeviceCredentialCAS(ctx context.Context, arg RotateDeviceCredentialCASParams) (DeviceCredential, error)
	//RotateProfileExportItemCiphertextCAS
	//
	//  UPDATE profile_export_items
	//  SET real_name_ciphertext = $1,
	//      real_name_nonce = $2,
	//      real_name_key_version = $3
	//  WHERE export_id = $4
	//    AND ordinal = $5
	//    AND real_name_key_version = $6
	//  RETURNING export_id, ordinal, user_id, real_name_key_version
	RotateProfileExportItemCiphertextCAS(ctx context.Context, arg RotateProfileExportItemCiphertextCASParams) (RotateProfileExportItemCiphertextCASRow, error)
	//RotateUserProfileCiphertextCAS
	//
	//  UPDATE user_profiles
	//  SET real_name_ciphertext = $1,
	//      real_name_nonce = $2,
	//      real_name_key_version = $3
	//  WHERE user_id = $4
	//    AND profile_version = $5
	//    AND real_name_key_version = $6
	//  RETURNING user_id, real_name_key_version, profile_version
	RotateUserProfileCiphertextCAS(ctx context.Context, arg RotateUserProfileCiphertextCASParams) (RotateUserProfileCiphertextCASRow, error)
	//RunExpiryCleanup
	//
	//  SELECT run_expiry_cleanup()
	RunExpiryCleanup(ctx context.Context) ([]byte, error)
	//SetCurrentUsernameCAS
	//
	//  UPDATE users
	//  SET status = $1,
	//      username = $2,
	//      current_username_key = $3,
	//      username_changed_at = $4,
	//      updated_at = $4
	//  WHERE user_id = $5
	//    AND status = $6
	//    AND current_username_key IS NOT DISTINCT FROM $7::text
	//    AND updated_at = $8
	//  RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	SetCurrentUsernameCAS(ctx context.Context, arg SetCurrentUsernameCASParams) (User, error)
	//TouchAdminSessionCAS
	//
	//  UPDATE admin_sessions
	//  SET last_seen_at = $1,
	//      idle_expires_at = LEAST($2::timestamptz, absolute_expires_at)
	//  WHERE session_id = $3
	//    AND admin_version = $4
	//    AND password_version = $5
	//    AND revoked_at IS NULL
	//    AND idle_expires_at > $1
	//    AND absolute_expires_at > $1
	//  RETURNING session_id, kind, last_seen_at, idle_expires_at, absolute_expires_at
	TouchAdminSessionCAS(ctx context.Context, arg TouchAdminSessionCASParams) (TouchAdminSessionCASRow, error)
	//TouchDeviceCredentialCAS
	//
	//  UPDATE device_credentials
	//  SET last_seen_at = $1,
	//      idle_expires_at = LEAST($2::timestamptz, absolute_expires_at)
	//  WHERE credential_id = $3
	//    AND generation = $4
	//    AND secret_hash = $5
	//    AND secret_key_version = $6
	//    AND previous_secret_hash IS NOT DISTINCT FROM $7::bytea
	//    AND previous_secret_key_version IS NOT DISTINCT FROM $8::integer
	//    AND previous_valid_until IS NOT DISTINCT FROM $9::timestamptz
	//    AND csrf_hash = $10
	//    AND last_seen_at = $11
	//    AND rotated_at = $12
	//    AND idle_expires_at = $13
	//    AND absolute_expires_at = $14
	//    AND revoked_at IS NULL
	//    AND idle_expires_at > $1
	//    AND absolute_expires_at > $1
	//    AND last_seen_at < $1
	//  RETURNING credential_id, generation, last_seen_at, idle_expires_at, absolute_expires_at
	TouchDeviceCredentialCAS(ctx context.Context, arg TouchDeviceCredentialCASParams) (TouchDeviceCredentialCASRow, error)
	//TransitionAdminStatusCAS
	//
	//  UPDATE admin_accounts
	//  SET status = $1,
	//      admin_version = admin_version + 1,
	//      updated_at = $2
	//  WHERE singleton_id = 1
	//    AND admin_id = $3
	//    AND status = $4
	//    AND admin_version = $5
	//  RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
	TransitionAdminStatusCAS(ctx context.Context, arg TransitionAdminStatusCASParams) (TransitionAdminStatusCASRow, error)
	//TransitionUserStatusCAS
	//
	//  UPDATE users
	//  SET status = $1,
	//      username = CASE WHEN $1::text = 'deleted' THEN NULL ELSE username END,
	//      current_username_key = CASE WHEN $1::text = 'deleted' THEN NULL ELSE current_username_key END,
	//      updated_at = $2
	//  WHERE user_id = $3
	//    AND status = $4
	//    AND updated_at = $5
	//  RETURNING user_id, status, username, current_username_key, username_changed_at, created_at, updated_at
	TransitionUserStatusCAS(ctx context.Context, arg TransitionUserStatusCASParams) (User, error)
	//UpdateAdminPasswordCAS
	//
	//  UPDATE admin_accounts
	//  SET password_hash = $1,
	//      password_algorithm = $2,
	//      password_parameters = $3,
	//      password_version = password_version + 1,
	//      admin_version = admin_version + 1,
	//      updated_at = $4
	//  WHERE singleton_id = 1
	//    AND admin_id = $5
	//    AND status = $6
	//    AND password_version = $7
	//    AND admin_version = $8
	//  RETURNING singleton_id, admin_id, status, password_version, admin_version, updated_at
	UpdateAdminPasswordCAS(ctx context.Context, arg UpdateAdminPasswordCASParams) (UpdateAdminPasswordCASRow, error)
	//UpdateGameSessionLifecycleCAS
	//
	//  UPDATE game_sessions
	//  SET next_deadline_at = $1,
	//      status = $2,
	//      updated_at = $3,
	//      ended_at = $4
	//  WHERE session_id = $5
	//    AND state_version = $6
	//    AND ownership_epoch = $7
	//    AND status IN ('active', 'suspended')
	//  RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
	//      state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
	//      state_payload, next_deadline_at, status, started_at, updated_at, ended_at
	UpdateGameSessionLifecycleCAS(ctx context.Context, arg UpdateGameSessionLifecycleCASParams) (GameSession, error)
	//UpdateGameSessionStateCAS
	//
	//  UPDATE game_sessions
	//  SET state_version = $1,
	//      snapshot_version = $2,
	//      state_message_type = $3,
	//      state_schema_version = $4,
	//      state_payload = $5,
	//      next_deadline_at = $6,
	//      status = $7,
	//      updated_at = $8,
	//      ended_at = $9
	//  WHERE session_id = $10
	//    AND state_version = $11
	//    AND ownership_epoch = $12
	//    AND status = 'active'
	//  RETURNING session_id, room_id, game_id, engine_version, protocol_version, client_version,
	//      state_version, ownership_epoch, snapshot_version, state_message_type, state_schema_version,
	//      state_payload, next_deadline_at, status, started_at, updated_at, ended_at
	UpdateGameSessionStateCAS(ctx context.Context, arg UpdateGameSessionStateCASParams) (GameSession, error)
	//UpdatePartyRoomCAS
	//
	//  UPDATE party_rooms
	//  SET visibility = $1,
	//      status = $2,
	//      host_user_id = $3,
	//      participant_capacity = $4,
	//      participant_admission = $5,
	//      spectator_admission = $6,
	//      active_session_id = $7,
	//      active_game_id = $8,
	//      room_version = $9,
	//      membership_version = $10,
	//      updated_at = $11
	//  WHERE room_id = $12
	//    AND room_code = $13
	//    AND room_version = $14
	//    AND membership_version = $15
	//  RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
	//      participant_admission, spectator_admission, active_session_id, active_game_id,
	//      room_version, membership_version, created_at, updated_at
	UpdatePartyRoomCAS(ctx context.Context, arg UpdatePartyRoomCASParams) (PartyRoom, error)
	//UpdateUserProfileCAS
	//
	//  UPDATE user_profiles
	//  SET real_name_ciphertext = $1,
	//      real_name_nonce = $2,
	//      real_name_key_version = $3,
	//      profile_version = profile_version + 1,
	//      real_name_updated_at = $4,
	//      real_name_updated_by = $5
	//  WHERE user_id = $6
	//    AND profile_version = $7
	//  RETURNING user_id, real_name_ciphertext, real_name_nonce, real_name_key_version,
	//            profile_version, real_name_updated_at, real_name_updated_by
	UpdateUserProfileCAS(ctx context.Context, arg UpdateUserProfileCASParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
