// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPartyRoom = `-- name: CreatePartyRoom :one
INSERT INTO party_rooms (
    room_id,
    room_code,
    visibility,
    status,
    host_user_id,
    participant_capacity,
    participant_admission,
    spectator_admission,
    active_session_id,
    active_game_id,
    last_finished_session_id,
    last_finished_game_id,
    room_version,
    membership_version,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at,
    last_finished_session_id, last_finished_game_id
`

type CreatePartyRoomParams struct {
	RoomID                pgtype.UUID        `json:"room_id"`
	RoomCode              string             `json:"room_code"`
	Visibility            string             `json:"visibility"`
	Status                string             `json:"status"`
	HostUserID            pgtype.UUID        `json:"host_user_id"`
	ParticipantCapacity   int32              `json:"participant_capacity"`
	ParticipantAdmission  string             `json:"participant_admission"`
	SpectatorAdmission    string             `json:"spectator_admission"`
	ActiveSessionID       pgtype.UUID        `json:"active_session_id"`
	ActiveGameID          pgtype.Text        `json:"active_game_id"`
	LastFinishedSessionID pgtype.UUID        `json:"last_finished_session_id"`
	LastFinishedGameID    pgtype.Text        `json:"last_finished_game_id"`
	RoomVersion           int64              `json:"room_version"`
	MembershipVersion     int64              `json:"membership_version"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// CreatePartyRoom
//
//	INSERT INTO party_rooms (
//	    room_id,
//	    room_code,
//	    visibility,
//	    status,
//	    host_user_id,
//	    participant_capacity,
//	    participant_admission,
//	    spectator_admission,
//	    active_session_id,
//	    active_game_id,
//	    last_finished_session_id,
//	    last_finished_game_id,
//	    room_version,
//	    membership_version,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    $12,
//	    $13,
//	    $14,
//	    $15,
//	    $16
//	)
//	RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at,
//	    last_finished_session_id, last_finished_game_id
func (q *Queries) CreatePartyRoom(ctx context.Context, arg CreatePartyRoomParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, createPartyRoom,
		arg.RoomID,
		arg.RoomCode,
		arg.Visibility,
		arg.Status,
		arg.HostUserID,
		arg.ParticipantCapacity,
		arg.ParticipantAdmission,
		arg.SpectatorAdmission,
		arg.ActiveSessionID,
		arg.ActiveGameID,
		arg.LastFinishedSessionID,
		arg.LastFinishedGameID,
		arg.RoomVersion,
		arg.MembershipVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFinishedSessionID,
		&i.LastFinishedGameID,
	)
	return i, err
}

const createRoomMember = `-- name: CreateRoomMember :exec
INSERT INTO room_members (
    room_id,
    user_id,
    role,
    requested_role,
    seat_index,
    joined_at,
    last_seen_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateRoomMemberParams struct {
	RoomID        pgtype.UUID        `json:"room_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Role          string             `json:"role"`
	RequestedRole pgtype.Text        `json:"requested_role"`
	SeatIndex     pgtype.Int4        `json:"seat_index"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
}

// CreateRoomMember
//
//	INSERT INTO room_members (
//	    room_id,
//	    user_id,
//	    role,
//	    requested_role,
//	    seat_index,
//	    joined_at,
//	    last_seen_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7
//	)
func (q *Queries) CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error {
	_, err := q.db.Exec(ctx, createRoomMember,
		arg.RoomID,
		arg.UserID,
		arg.Role,
		arg.RequestedRole,
		arg.SeatIndex,
		arg.JoinedAt,
		arg.LastSeenAt,
	)
	return err
}

const deleteRoomMembers = `-- name: DeleteRoomMembers :exec
DELETE FROM room_members WHERE room_id = $1
`

type DeleteRoomMembersParams struct {
	RoomID pgtype.UUID `json:"room_id"`
}

// DeleteRoomMembers
//
//	DELETE FROM room_members WHERE room_id = $1
func (q *Queries) DeleteRoomMembers(ctx context.Context, arg DeleteRoomMembersParams) error {
	_, err := q.db.Exec(ctx, deleteRoomMembers, arg.RoomID)
	return err
}

const finishPartyRoomCAS = `-- name: FinishPartyRoomCAS :one
UPDATE party_rooms
SET status = 'post_game',
    participant_admission = 'closed',
    last_finished_session_id = active_session_id,
    last_finished_game_id = active_game_id,
    active_session_id = NULL,
    active_game_id = NULL,
    room_version = $1,
    updated_at = $2
WHERE room_id = $3
  AND status = 'playing'
  AND active_session_id = $4
  AND active_game_id = $5
  AND room_version = $6
  AND membership_version = $7
RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at,
    last_finished_session_id, last_finished_game_id
`

type FinishPartyRoomCASParams struct {
	RoomVersion               int64              `json:"room_version"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	RoomID                    pgtype.UUID        `json:"room_id"`
	ActiveSessionID           pgtype.UUID        `json:"active_session_id"`
	ActiveGameID              pgtype.Text        `json:"active_game_id"`
	ExpectedRoomVersion       int64              `json:"expected_room_version"`
	ExpectedMembershipVersion int64              `json:"expected_membership_version"`
}

// FinishPartyRoomCAS
//
//	UPDATE party_rooms
//	SET status = 'post_game',
//	    participant_admission = 'closed',
//	    last_finished_session_id = active_session_id,
//	    last_finished_game_id = active_game_id,
//	    active_session_id = NULL,
//	    active_game_id = NULL,
//	    room_version = $1,
//	    updated_at = $2
//	WHERE room_id = $3
//	  AND status = 'playing'
//	  AND active_session_id = $4
//	  AND active_game_id = $5
//	  AND room_version = $6
//	  AND membership_version = $7
//	RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at,
//	    last_finished_session_id, last_finished_game_id
func (q *Queries) FinishPartyRoomCAS(ctx context.Context, arg FinishPartyRoomCASParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, finishPartyRoomCAS,
		arg.RoomVersion,
		arg.UpdatedAt,
		arg.RoomID,
		arg.ActiveSessionID,
		arg.ActiveGameID,
		arg.ExpectedRoomVersion,
		arg.ExpectedMembershipVersion,
	)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFinishedSessionID,
		&i.LastFinishedGameID,
	)
	return i, err
}

const getPartyRoomByCodeForShare = `-- name: GetPartyRoomByCodeForShare :one
SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at,
    last_finished_session_id, last_finished_game_id
FROM party_rooms
WHERE room_code = $1
FOR SHARE
`

type GetPartyRoomByCodeForShareParams struct {
	RoomCode string `json:"room_code"`
}

// GetPartyRoomByCodeForShare
//
//	SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at,
//	    last_finished_session_id, last_finished_game_id
//	FROM party_rooms
//	WHERE room_code = $1
//	FOR SHARE
func (q *Queries) GetPartyRoomByCodeForShare(ctx context.Context, arg GetPartyRoomByCodeForShareParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, getPartyRoomByCodeForShare, arg.RoomCode)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFinishedSessionID,
		&i.LastFinishedGameID,
	)
	return i, err
}

const getPartyRoomForShare = `-- name: GetPartyRoomForShare :one
SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at,
    last_finished_session_id, last_finished_game_id
FROM party_rooms
WHERE room_id = $1
FOR SHARE
`

type GetPartyRoomForShareParams struct {
	RoomID pgtype.UUID `json:"room_id"`
}

// GetPartyRoomForShare
//
//	SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at,
//	    last_finished_session_id, last_finished_game_id
//	FROM party_rooms
//	WHERE room_id = $1
//	FOR SHARE
func (q *Queries) GetPartyRoomForShare(ctx context.Context, arg GetPartyRoomForShareParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, getPartyRoomForShare, arg.RoomID)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFinishedSessionID,
		&i.LastFinishedGameID,
	)
	return i, err
}

const getPartyRoomForUpdate = `-- name: GetPartyRoomForUpdate :one
SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at,
    last_finished_session_id, last_finished_game_id
FROM party_rooms
WHERE room_id = $1
FOR UPDATE
`

type GetPartyRoomForUpdateParams struct {
	RoomID pgtype.UUID `json:"room_id"`
}

// GetPartyRoomForUpdate
//
//	SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at,
//	    last_finished_session_id, last_finished_game_id
//	FROM party_rooms
//	WHERE room_id = $1
//	FOR UPDATE
func (q *Queries) GetPartyRoomForUpdate(ctx context.Context, arg GetPartyRoomForUpdateParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, getPartyRoomForUpdate, arg.RoomID)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFinishedSessionID,
		&i.LastFinishedGameID,
	)
	return i, err
}

const getRoomMemberRole = `-- name: GetRoomMemberRole :one
SELECT role
FROM room_members
WHERE room_id = $1
  AND user_id = $2
`

type GetRoomMemberRoleParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// GetRoomMemberRole
//
//	SELECT role
//	FROM room_members
//	WHERE room_id = $1
//	  AND user_id = $2
func (q *Queries) GetRoomMemberRole(ctx context.Context, arg GetRoomMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getRoomMemberRole, arg.RoomID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listMyRoomCards = `-- name: ListMyRoomCards :many
SELECT room.room_id,
    room.room_code,
    room.visibility,
    host.username AS host_username,
    room.status,
    room.host_user_id = $1 AS is_host,
    room.participant_capacity,
    counts.participant_count,
    counts.spectator_count,
    counts.waiting_count,
    room.participant_admission,
    room.spectator_admission,
    room.active_game_id,
    room.last_finished_game_id,
    viewer.role AS viewer_role,
    viewer.requested_role AS viewer_requested_role,
    room.updated_at
FROM room_members AS viewer
JOIN party_rooms AS room
  ON room.room_id = viewer.room_id
JOIN users AS host
  ON host.user_id = room.host_user_id
JOIN LATERAL (
    SELECT count(*) FILTER (WHERE member.role = 'participant') AS participant_count,
        count(*) FILTER (WHERE member.role = 'spectator') AS spectator_count,
        count(*) FILTER (WHERE member.role = 'waiting') AS waiting_count
    FROM room_members AS member
    WHERE member.room_id = room.room_id
) AS counts ON true
WHERE viewer.user_id = $1
  AND room.status <> 'closed'
  AND (
      NOT $2::boolean
      OR (
          room.host_user_id = $1,
          room.updated_at,
          room.room_id
      ) < (
          $3::boolean,
          $4::timestamptz,
          $5::uuid
      )
  )
ORDER BY (room.host_user_id = $1) DESC, room.updated_at DESC, room.room_id DESC
LIMIT $6
`

type ListMyRoomCardsParams struct {
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	HasAfter       bool               `json:"has_after"`
	AfterIsHost    bool               `json:"after_is_host"`
	AfterUpdatedAt pgtype.Timestamptz `json:"after_updated_at"`
	AfterRoomID    pgtype.UUID        `json:"after_room_id"`
	PageLimit      int32              `json:"page_limit"`
}

type ListMyRoomCardsRow struct {
	RoomID               pgtype.UUID        `json:"room_id"`
	RoomCode             string             `json:"room_code"`
	Visibility           string             `json:"visibility"`
	HostUsername         pgtype.Text        `json:"host_username"`
	Status               string             `json:"status"`
	IsHost               bool               `json:"is_host"`
	ParticipantCapacity  int32              `json:"participant_capacity"`
	ParticipantCount     int64              `json:"participant_count"`
	SpectatorCount       int64              `json:"spectator_count"`
	WaitingCount         int64              `json:"waiting_count"`
	ParticipantAdmission string             `json:"participant_admission"`
	SpectatorAdmission   string             `json:"spectator_admission"`
	ActiveGameID         pgtype.Text        `json:"active_game_id"`
	LastFinishedGameID   pgtype.Text        `json:"last_finished_game_id"`
	ViewerRole           string             `json:"viewer_role"`
	ViewerRequestedRole  pgtype.Text        `json:"viewer_requested_role"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// ListMyRoomCards
//
//	SELECT room.room_id,
//	    room.room_code,
//	    room.visibility,
//	    host.username AS host_username,
//	    room.status,
//	    room.host_user_id = $1 AS is_host,
//	    room.participant_capacity,
//	    counts.participant_count,
//	    counts.spectator_count,
//	    counts.waiting_count,
//	    room.participant_admission,
//	    room.spectator_admission,
//	    room.active_game_id,
//	    room.last_finished_game_id,
//	    viewer.role AS viewer_role,
//	    viewer.requested_role AS viewer_requested_role,
//	    room.updated_at
//	FROM room_members AS viewer
//	JOIN party_rooms AS room
//	  ON room.room_id = viewer.room_id
//	JOIN users AS host
//	  ON host.user_id = room.host_user_id
//	JOIN LATERAL (
//	    SELECT count(*) FILTER (WHERE member.role = 'participant') AS participant_count,
//	        count(*) FILTER (WHERE member.role = 'spectator') AS spectator_count,
//	        count(*) FILTER (WHERE member.role = 'waiting') AS waiting_count
//	    FROM room_members AS member
//	    WHERE member.room_id = room.room_id
//	) AS counts ON true
//	WHERE viewer.user_id = $1
//	  AND room.status <> 'closed'
//	  AND (
//	      NOT $2::boolean
//	      OR (
//	          room.host_user_id = $1,
//	          room.updated_at,
//	          room.room_id
//	      ) < (
//	          $3::boolean,
//	          $4::timestamptz,
//	          $5::uuid
//	      )
//	  )
//	ORDER BY (room.host_user_id = $1) DESC, room.updated_at DESC, room.room_id DESC
//	LIMIT $6
func (q *Queries) ListMyRoomCards(ctx context.Context, arg ListMyRoomCardsParams) ([]ListMyRoomCardsRow, error) {
	rows, err := q.db.Query(ctx, listMyRoomCards,
		arg.ActorUserID,
		arg.HasAfter,
		arg.AfterIsHost,
		arg.AfterUpdatedAt,
		arg.AfterRoomID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyRoomCardsRow{}
	for rows.Next() {
		var i ListMyRoomCardsRow
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomCode,
			&i.Visibility,
			&i.HostUsername,
			&i.Status,
			&i.IsHost,
			&i.ParticipantCapacity,
			&i.ParticipantCount,
			&i.SpectatorCount,
			&i.WaitingCount,
			&i.ParticipantAdmission,
			&i.SpectatorAdmission,
			&i.ActiveGameID,
			&i.LastFinishedGameID,
			&i.ViewerRole,
			&i.ViewerRequestedRole,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicRoomCards = `-- name: ListPublicRoomCards :many
SELECT room.room_id,
    host.username AS host_username,
    room.status,
    room.participant_capacity,
    counts.participant_count,
    counts.spectator_count,
    counts.waiting_count,
    room.participant_admission,
    room.spectator_admission,
    room.active_game_id,
    viewer.role AS viewer_role,
    viewer.requested_role AS viewer_requested_role,
    room.updated_at
FROM party_rooms AS room
JOIN users AS host
  ON host.user_id = room.host_user_id
 AND host.status = 'active'
JOIN LATERAL (
    SELECT count(*) FILTER (WHERE member.role = 'participant') AS participant_count,
        count(*) FILTER (WHERE member.role = 'spectator') AS spectator_count,
        count(*) FILTER (WHERE member.role = 'waiting') AS waiting_count
    FROM room_members AS member
    WHERE member.room_id = room.room_id
) AS counts ON true
LEFT JOIN room_members AS viewer
  ON viewer.room_id = room.room_id
 AND viewer.user_id = $1
WHERE room.visibility = 'public'
  AND room.status <> 'closed'
  AND (
      (NOT $2::boolean AND NOT $3::boolean AND NOT $4::boolean)
      OR ($2::boolean AND room.status = 'lobby')
      OR ($3::boolean AND room.status = 'playing')
      OR ($4::boolean AND room.status = 'post_game')
  )
  AND ($5::text = '' OR room.active_game_id = $5::text)
  AND (
      NOT $6::boolean
      OR (
          room.status IN ('lobby', 'post_game')
          AND room.participant_admission IN ('open', 'approval')
          AND counts.participant_count < room.participant_capacity
      )
  )
  AND (
      NOT $7::boolean
      OR (room.updated_at, room.room_id) < ($8::timestamptz, $9::uuid)
  )
ORDER BY room.updated_at DESC, room.room_id DESC
LIMIT $10
`

type ListPublicRoomCardsParams struct {
	ActorUserID             pgtype.UUID        `json:"actor_user_id"`
	IncludeLobby            bool               `json:"include_lobby"`
	IncludePlaying          bool               `json:"include_playing"`
	IncludePostGame         bool               `json:"include_post_game"`
	GameID                  string             `json:"game_id"`
	ParticipantJoinableOnly bool               `json:"participant_joinable_only"`
	HasAfter                bool               `json:"has_after"`
	AfterUpdatedAt          pgtype.Timestamptz `json:"after_updated_at"`
	AfterRoomID             pgtype.UUID        `json:"after_room_id"`
	PageLimit               int32              `json:"page_limit"`
}

type ListPublicRoomCardsRow struct {
	RoomID               pgtype.UUID        `json:"room_id"`
	HostUsername         pgtype.Text        `json:"host_username"`
	Status               string             `json:"status"`
	ParticipantCapacity  int32              `json:"participant_capacity"`
	ParticipantCount     int64              `json:"participant_count"`
	SpectatorCount       int64              `json:"spectator_count"`
	WaitingCount         int64              `json:"waiting_count"`
	ParticipantAdmission string             `json:"participant_admission"`
	SpectatorAdmission   string             `json:"spectator_admission"`
	ActiveGameID         pgtype.Text        `json:"active_game_id"`
	ViewerRole           pgtype.Text        `json:"viewer_role"`
	ViewerRequestedRole  pgtype.Text        `json:"viewer_requested_role"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// ListPublicRoomCards
//
//	SELECT room.room_id,
//	    host.username AS host_username,
//	    room.status,
//	    room.participant_capacity,
//	    counts.participant_count,
//	    counts.spectator_count,
//	    counts.waiting_count,
//	    room.participant_admission,
//	    room.spectator_admission,
//	    room.active_game_id,
//	    viewer.role AS viewer_role,
//	    viewer.requested_role AS viewer_requested_role,
//	    room.updated_at
//	FROM party_rooms AS room
//	JOIN users AS host
//	  ON host.user_id = room.host_user_id
//	 AND host.status = 'active'
//	JOIN LATERAL (
//	    SELECT count(*) FILTER (WHERE member.role = 'participant') AS participant_count,
//	        count(*) FILTER (WHERE member.role = 'spectator') AS spectator_count,
//	        count(*) FILTER (WHERE member.role = 'waiting') AS waiting_count
//	    FROM room_members AS member
//	    WHERE member.room_id = room.room_id
//	) AS counts ON true
//	LEFT JOIN room_members AS viewer
//	  ON viewer.room_id = room.room_id
//	 AND viewer.user_id = $1
//	WHERE room.visibility = 'public'
//	  AND room.status <> 'closed'
//	  AND (
//	      (NOT $2::boolean AND NOT $3::boolean AND NOT $4::boolean)
//	      OR ($2::boolean AND room.status = 'lobby')
//	      OR ($3::boolean AND room.status = 'playing')
//	      OR ($4::boolean AND room.status = 'post_game')
//	  )
//	  AND ($5::text = '' OR room.active_game_id = $5::text)
//	  AND (
//	      NOT $6::boolean
//	      OR (
//	          room.status IN ('lobby', 'post_game')
//	          AND room.participant_admission IN ('open', 'approval')
//	          AND counts.participant_count < room.participant_capacity
//	      )
//	  )
//	  AND (
//	      NOT $7::boolean
//	      OR (room.updated_at, room.room_id) < ($8::timestamptz, $9::uuid)
//	  )
//	ORDER BY room.updated_at DESC, room.room_id DESC
//	LIMIT $10
func (q *Queries) ListPublicRoomCards(ctx context.Context, arg ListPublicRoomCardsParams) ([]ListPublicRoomCardsRow, error) {
	rows, err := q.db.Query(ctx, listPublicRoomCards,
		arg.ActorUserID,
		arg.IncludeLobby,
		arg.IncludePlaying,
		arg.IncludePostGame,
		arg.GameID,
		arg.ParticipantJoinableOnly,
		arg.HasAfter,
		arg.AfterUpdatedAt,
		arg.AfterRoomID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicRoomCardsRow{}
	for rows.Next() {
		var i ListPublicRoomCardsRow
		if err := rows.Scan(
			&i.RoomID,
			&i.HostUsername,
			&i.Status,
			&i.ParticipantCapacity,
			&i.ParticipantCount,
			&i.SpectatorCount,
			&i.WaitingCount,
			&i.ParticipantAdmission,
			&i.SpectatorAdmission,
			&i.ActiveGameID,
			&i.ViewerRole,
			&i.ViewerRequestedRole,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT room_id, user_id, role, requested_role, seat_index, joined_at, last_seen_at
FROM room_members
WHERE room_id = $1
ORDER BY joined_at, user_id
`

type ListRoomMembersParams struct {
	RoomID pgtype.UUID `json:"room_id"`
}

// ListRoomMembers
//
//	SELECT room_id, user_id, role, requested_role, seat_index, joined_at, last_seen_at
//	FROM room_members
//	WHERE room_id = $1
//	ORDER BY joined_at, user_id
func (q *Queries) ListRoomMembers(ctx context.Context, arg ListRoomMembersParams) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomMember{}
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.RequestedRole,
			&i.SeatIndex,
			&i.JoinedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartyRoomCAS = `-- name: UpdatePartyRoomCAS :one
UPDATE party_rooms
SET visibility = $1,
    status = $2,
    host_user_id = $3,
    participant_capacity = $4,
    participant_admission = $5,
    spectator_admission = $6,
    active_session_id = $7,
    active_game_id = $8,
    last_finished_session_id = $9,
    last_finished_game_id = $10,
    room_version = $11,
    membership_version = $12,
    updated_at = $13
WHERE room_id = $14
  AND room_code = $15
  AND room_version = $16
  AND membership_version = $17
RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at,
    last_finished_session_id, last_finished_game_id
`

type UpdatePartyRoomCASParams struct {
	Visibility                string             `json:"visibility"`
	Status                    string             `json:"status"`
	HostUserID                pgtype.UUID        `json:"host_user_id"`
	ParticipantCapacity       int32              `json:"participant_capacity"`
	ParticipantAdmission      string             `json:"participant_admission"`
	SpectatorAdmission        string             `json:"spectator_admission"`
	ActiveSessionID           pgtype.UUID        `json:"active_session_id"`
	ActiveGameID              pgtype.Text        `json:"active_game_id"`
	LastFinishedSessionID     pgtype.UUID        `json:"last_finished_session_id"`
	LastFinishedGameID        pgtype.Text        `json:"last_finished_game_id"`
	RoomVersion               int64              `json:"room_version"`
	MembershipVersion         int64              `json:"membership_version"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	RoomID                    pgtype.UUID        `json:"room_id"`
	RoomCode                  string             `json:"room_code"`
	ExpectedRoomVersion       int64              `json:"expected_room_version"`
	ExpectedMembershipVersion int64              `json:"expected_membership_version"`
}

// UpdatePartyRoomCAS
//
//	UPDATE party_rooms
//	SET visibility = $1,
//	    status = $2,
//	    host_user_id = $3,
//	    participant_capacity = $4,
//	    participant_admission = $5,
//	    spectator_admission = $6,
//	    active_session_id = $7,
//	    active_game_id = $8,
//	    last_finished_session_id = $9,
//	    last_finished_game_id = $10,
//	    room_version = $11,
//	    membership_version = $12,
//	    updated_at = $13
//	WHERE room_id = $14
//	  AND room_code = $15
//	  AND room_version = $16
//	  AND membership_version = $17
//	RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at,
//	    last_finished_session_id, last_finished_game_id
func (q *Queries) UpdatePartyRoomCAS(ctx context.Context, arg UpdatePartyRoomCASParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, updatePartyRoomCAS,
		arg.Visibility,
		arg.Status,
		arg.HostUserID,
		arg.ParticipantCapacity,
		arg.ParticipantAdmission,
		arg.SpectatorAdmission,
		arg.ActiveSessionID,
		arg.ActiveGameID,
		arg.LastFinishedSessionID,
		arg.LastFinishedGameID,
		arg.RoomVersion,
		arg.MembershipVersion,
		arg.UpdatedAt,
		arg.RoomID,
		arg.RoomCode,
		arg.ExpectedRoomVersion,
		arg.ExpectedMembershipVersion,
	)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFinishedSessionID,
		&i.LastFinishedGameID,
	)
	return i, err
}
