// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPartyRoom = `-- name: CreatePartyRoom :one
INSERT INTO party_rooms (
    room_id,
    room_code,
    visibility,
    status,
    host_user_id,
    participant_capacity,
    participant_admission,
    spectator_admission,
    active_session_id,
    active_game_id,
    room_version,
    membership_version,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at
`

type CreatePartyRoomParams struct {
	RoomID               pgtype.UUID        `json:"room_id"`
	RoomCode             string             `json:"room_code"`
	Visibility           string             `json:"visibility"`
	Status               string             `json:"status"`
	HostUserID           pgtype.UUID        `json:"host_user_id"`
	ParticipantCapacity  int32              `json:"participant_capacity"`
	ParticipantAdmission string             `json:"participant_admission"`
	SpectatorAdmission   string             `json:"spectator_admission"`
	ActiveSessionID      pgtype.UUID        `json:"active_session_id"`
	ActiveGameID         pgtype.Text        `json:"active_game_id"`
	RoomVersion          int64              `json:"room_version"`
	MembershipVersion    int64              `json:"membership_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// CreatePartyRoom
//
//	INSERT INTO party_rooms (
//	    room_id,
//	    room_code,
//	    visibility,
//	    status,
//	    host_user_id,
//	    participant_capacity,
//	    participant_admission,
//	    spectator_admission,
//	    active_session_id,
//	    active_game_id,
//	    room_version,
//	    membership_version,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    $12,
//	    $13,
//	    $14
//	)
//	RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at
func (q *Queries) CreatePartyRoom(ctx context.Context, arg CreatePartyRoomParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, createPartyRoom,
		arg.RoomID,
		arg.RoomCode,
		arg.Visibility,
		arg.Status,
		arg.HostUserID,
		arg.ParticipantCapacity,
		arg.ParticipantAdmission,
		arg.SpectatorAdmission,
		arg.ActiveSessionID,
		arg.ActiveGameID,
		arg.RoomVersion,
		arg.MembershipVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoomMember = `-- name: CreateRoomMember :exec
INSERT INTO room_members (
    room_id,
    user_id,
    role,
    requested_role,
    seat_index,
    joined_at,
    last_seen_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateRoomMemberParams struct {
	RoomID        pgtype.UUID        `json:"room_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Role          string             `json:"role"`
	RequestedRole pgtype.Text        `json:"requested_role"`
	SeatIndex     pgtype.Int4        `json:"seat_index"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
}

// CreateRoomMember
//
//	INSERT INTO room_members (
//	    room_id,
//	    user_id,
//	    role,
//	    requested_role,
//	    seat_index,
//	    joined_at,
//	    last_seen_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7
//	)
func (q *Queries) CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error {
	_, err := q.db.Exec(ctx, createRoomMember,
		arg.RoomID,
		arg.UserID,
		arg.Role,
		arg.RequestedRole,
		arg.SeatIndex,
		arg.JoinedAt,
		arg.LastSeenAt,
	)
	return err
}

const deleteRoomMembers = `-- name: DeleteRoomMembers :exec
DELETE FROM room_members WHERE room_id = $1
`

type DeleteRoomMembersParams struct {
	RoomID pgtype.UUID `json:"room_id"`
}

// DeleteRoomMembers
//
//	DELETE FROM room_members WHERE room_id = $1
func (q *Queries) DeleteRoomMembers(ctx context.Context, arg DeleteRoomMembersParams) error {
	_, err := q.db.Exec(ctx, deleteRoomMembers, arg.RoomID)
	return err
}

const getPartyRoomByCodeForShare = `-- name: GetPartyRoomByCodeForShare :one
SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at
FROM party_rooms
WHERE room_code = $1
FOR SHARE
`

type GetPartyRoomByCodeForShareParams struct {
	RoomCode string `json:"room_code"`
}

// GetPartyRoomByCodeForShare
//
//	SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at
//	FROM party_rooms
//	WHERE room_code = $1
//	FOR SHARE
func (q *Queries) GetPartyRoomByCodeForShare(ctx context.Context, arg GetPartyRoomByCodeForShareParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, getPartyRoomByCodeForShare, arg.RoomCode)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyRoomForShare = `-- name: GetPartyRoomForShare :one
SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at
FROM party_rooms
WHERE room_id = $1
FOR SHARE
`

type GetPartyRoomForShareParams struct {
	RoomID pgtype.UUID `json:"room_id"`
}

// GetPartyRoomForShare
//
//	SELECT room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at
//	FROM party_rooms
//	WHERE room_id = $1
//	FOR SHARE
func (q *Queries) GetPartyRoomForShare(ctx context.Context, arg GetPartyRoomForShareParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, getPartyRoomForShare, arg.RoomID)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT room_id, user_id, role, requested_role, seat_index, joined_at, last_seen_at
FROM room_members
WHERE room_id = $1
ORDER BY joined_at, user_id
`

type ListRoomMembersParams struct {
	RoomID pgtype.UUID `json:"room_id"`
}

// ListRoomMembers
//
//	SELECT room_id, user_id, role, requested_role, seat_index, joined_at, last_seen_at
//	FROM room_members
//	WHERE room_id = $1
//	ORDER BY joined_at, user_id
func (q *Queries) ListRoomMembers(ctx context.Context, arg ListRoomMembersParams) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomMember{}
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.RequestedRole,
			&i.SeatIndex,
			&i.JoinedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartyRoomCAS = `-- name: UpdatePartyRoomCAS :one
UPDATE party_rooms
SET visibility = $1,
    status = $2,
    host_user_id = $3,
    participant_capacity = $4,
    participant_admission = $5,
    spectator_admission = $6,
    active_session_id = $7,
    active_game_id = $8,
    room_version = $9,
    membership_version = $10,
    updated_at = $11
WHERE room_id = $12
  AND room_code = $13
  AND room_version = $14
  AND membership_version = $15
RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
    participant_admission, spectator_admission, active_session_id, active_game_id,
    room_version, membership_version, created_at, updated_at
`

type UpdatePartyRoomCASParams struct {
	Visibility                string             `json:"visibility"`
	Status                    string             `json:"status"`
	HostUserID                pgtype.UUID        `json:"host_user_id"`
	ParticipantCapacity       int32              `json:"participant_capacity"`
	ParticipantAdmission      string             `json:"participant_admission"`
	SpectatorAdmission        string             `json:"spectator_admission"`
	ActiveSessionID           pgtype.UUID        `json:"active_session_id"`
	ActiveGameID              pgtype.Text        `json:"active_game_id"`
	RoomVersion               int64              `json:"room_version"`
	MembershipVersion         int64              `json:"membership_version"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	RoomID                    pgtype.UUID        `json:"room_id"`
	RoomCode                  string             `json:"room_code"`
	ExpectedRoomVersion       int64              `json:"expected_room_version"`
	ExpectedMembershipVersion int64              `json:"expected_membership_version"`
}

// UpdatePartyRoomCAS
//
//	UPDATE party_rooms
//	SET visibility = $1,
//	    status = $2,
//	    host_user_id = $3,
//	    participant_capacity = $4,
//	    participant_admission = $5,
//	    spectator_admission = $6,
//	    active_session_id = $7,
//	    active_game_id = $8,
//	    room_version = $9,
//	    membership_version = $10,
//	    updated_at = $11
//	WHERE room_id = $12
//	  AND room_code = $13
//	  AND room_version = $14
//	  AND membership_version = $15
//	RETURNING room_id, room_code, visibility, status, host_user_id, participant_capacity,
//	    participant_admission, spectator_admission, active_session_id, active_game_id,
//	    room_version, membership_version, created_at, updated_at
func (q *Queries) UpdatePartyRoomCAS(ctx context.Context, arg UpdatePartyRoomCASParams) (PartyRoom, error) {
	row := q.db.QueryRow(ctx, updatePartyRoomCAS,
		arg.Visibility,
		arg.Status,
		arg.HostUserID,
		arg.ParticipantCapacity,
		arg.ParticipantAdmission,
		arg.SpectatorAdmission,
		arg.ActiveSessionID,
		arg.ActiveGameID,
		arg.RoomVersion,
		arg.MembershipVersion,
		arg.UpdatedAt,
		arg.RoomID,
		arg.RoomCode,
		arg.ExpectedRoomVersion,
		arg.ExpectedMembershipVersion,
	)
	var i PartyRoom
	err := row.Scan(
		&i.RoomID,
		&i.RoomCode,
		&i.Visibility,
		&i.Status,
		&i.HostUserID,
		&i.ParticipantCapacity,
		&i.ParticipantAdmission,
		&i.SpectatorAdmission,
		&i.ActiveSessionID,
		&i.ActiveGameID,
		&i.RoomVersion,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
